// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package iam

import (
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
	"time"
)

type AccountChange struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	AuthFactors []*objects.AuthFactor `json:"auth_factors,omitempty"`
	Policies    []*objects.Policy     `json:"policies,omitempty"`
	Policy      *objects.Policy       `json:"policy,omitempty"`
	User        *objects.User         `json:"user"`
	UserResult  *objects.User         `json:"user_result,omitempty"`
}

const (
	AccountChangeActivityCreate           = 1
	AccountChangeActivityMFAFactorEnable  = 10
	AccountChangeActivityMFAFactorDisable = 11
	AccountChangeActivityUnlock           = 12
	AccountChangeActivityEnable           = 2
	AccountChangeActivityPasswordChange   = 3
	AccountChangeActivityPasswordReset    = 4
	AccountChangeActivityDisable          = 5
	AccountChangeActivityDelete           = 6
	AccountChangeActivityAttachPolicy     = 7
	AccountChangeActivityDetachPolicy     = 8
	AccountChangeActivityLock             = 9
)

func NewAccountChange(activityID int) *AccountChange {
	return &AccountChange{
		Event: ocsf.Event{
			CategoryUID: 3,
			ClassUID:    3001,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(3, 3001, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "iam",
			Class:       "account_change",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}
