// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package iam

import (
	"fmt"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
	"time"
)

type Authentication struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	AccountSwitchType   string                       `json:"account_switch_type,omitempty"`
	AccountSwitchTypeId int                          `json:"account_switch_type_id,omitempty"`
	AuthFactors         []*objects.AuthFactor        `json:"auth_factors,omitempty"`
	AuthProtocol        string                       `json:"auth_protocol,omitempty"`
	AuthProtocolId      int                          `json:"auth_protocol_id,omitempty"`
	AuthenticationToken *objects.AuthenticationToken `json:"authentication_token,omitempty"`
	Certificate         *objects.Certificate         `json:"certificate,omitempty"`
	DstEndpoint         *objects.NetworkEndpoint     `json:"dst_endpoint,omitempty"`
	IsCleartext         bool                         `json:"is_cleartext,omitempty"`
	IsMfa               bool                         `json:"is_mfa,omitempty"`
	IsNewLogon          bool                         `json:"is_new_logon,omitempty"`
	IsRemote            bool                         `json:"is_remote,omitempty"`
	LogonProcess        *objects.Process             `json:"logon_process,omitempty"`
	LogonType           string                       `json:"logon_type,omitempty"`
	LogonTypeId         int                          `json:"logon_type_id,omitempty"`
	Service             *objects.Service             `json:"service,omitempty"`
	Session             *objects.Session             `json:"session,omitempty"`
	StatusDetail        string                       `json:"status_detail"`
	User                *objects.User                `json:"user"`
}

const (
	AuthenticationActivityLogon                = 1
	AuthenticationActivityLogoff               = 2
	AuthenticationActivityAuthenticationTicket = 3
	AuthenticationActivityServiceTicketRequest = 4
	AuthenticationActivityServiceTicketRenew   = 5
	AuthenticationActivityPreauth              = 6
	AuthenticationActivityAccountSwitch        = 7
)

func NewAuthentication(activityID int) *Authentication {
	return &Authentication{
		Event: ocsf.Event{
			CategoryUID: 3,
			ClassUID:    3002,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(3, 3002, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "iam",
			Class:       "authentication",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

// Validate checks that all required fields are properly set
func (e *Authentication) Validate() error {
	if e.StatusDetail == "" {
		return fmt.Errorf("required field status_detail is empty")
	}
	return nil
}
