// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package iam

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Authorize Session - Authorize Session events report privileges or groups assigned to a new user session, usually at login time.
// OCSF Class UID: 3003
//
// This is a generated struct representing the OCSF event class.
type AuthorizeSession struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	// The Endpoint for which the user session was targeted.
	DstEndpoint *objects.NetworkEndpoint `json:"dst_endpoint,omitempty"`
	// Group that was assigned to the new user session.
	Group *objects.Group `json:"group,omitempty"`
	// The list of sensitive privileges, assigned to the new user session.
	Privileges []string `json:"privileges,omitempty"`
	// The user session with the assigned privileges.
	Session *objects.Session `json:"session,omitempty"`
	// The user to which new privileges were assigned.
	User *objects.User `json:"user"`
}

// Activity IDs for Authorize Session
const (
	AuthorizeSessionActivityAssignPrivileges = 1 // Assign special privileges to a new logon.
	AuthorizeSessionActivityAssignGroups = 2 // Assign special groups to a new logon.
)

// NewAuthorizeSession creates a new Authorize Session event
func NewAuthorizeSession(activityID int) *AuthorizeSession {
	return &AuthorizeSession{
		Event: ocsf.Event{
			CategoryUID: 3,
			ClassUID:    3003,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(3, 3003, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "iam",
			Class:       "authorize_session",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

