// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package iam

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Authentication - Authentication events report authentication session activities, including user attempts to log on or log off, regardless of success, as well as other key stages within the authentication process. These events are typically generated by authentication services, such as Kerberos, OIDC, or SAML, and may include information about the user, the authentication method used, and the status of the authentication attempt.
// OCSF Class UID: 3002
//
// This is a generated struct representing the OCSF event class.
type Authentication struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	AccountSwitchType string `json:"account_switch_type,omitempty"`
	AccountSwitchTypeId int `json:"account_switch_type_id,omitempty"`
	// Describes a category of methods used for identity verification in an authentication attempt.
	AuthFactors []*objects.AuthFactor `json:"auth_factors,omitempty"`
	AuthProtocol string `json:"auth_protocol,omitempty"`
	AuthProtocolId int `json:"auth_protocol_id,omitempty"`
	// The authentication token, ticket, or assertion, e.g. `Kerberos`, `OIDC`, `SAML`.
	AuthenticationToken *objects.AuthenticationToken `json:"authentication_token,omitempty"`
	// The certificate associated with the authentication or pre-authentication (Kerberos).
	Certificate *objects.Certificate `json:"certificate,omitempty"`
	// The endpoint to which the authentication was targeted.
	DstEndpoint *objects.NetworkEndpoint `json:"dst_endpoint,omitempty"`
	IsCleartext bool `json:"is_cleartext,omitempty"`
	IsMfa bool `json:"is_mfa,omitempty"`
	IsNewLogon bool `json:"is_new_logon,omitempty"`
	// The attempted authentication is over a remote connection.
	IsRemote bool `json:"is_remote,omitempty"`
	LogonProcess *objects.Process `json:"logon_process,omitempty"`
	LogonType string `json:"logon_type,omitempty"`
	LogonTypeId int `json:"logon_type_id,omitempty"`
	// The service or gateway to which the user or process is being authenticated
	Service *objects.Service `json:"service,omitempty"`
	Session *objects.Session `json:"session,omitempty"`
	// The details about the authentication request. For example, possible details for Windows logon or logoff events are:<ul><li>Success</li><ul><li>LOGOFF_USER_INITIATED</li><li>LOGOFF_OTHER</li></ul><li>Failure</li><ul><li>USER_DOES_NOT_EXIST</li><li>INVALID_CREDENTIALS</li><li>ACCOUNT_DISABLED</li><li>ACCOUNT_LOCKED_OUT</li><li>PASSWORD_EXPIRED</li></ul></ul>
	StatusDetail string `json:"status_detail"`
	// The subject (user/role or account) to authenticate.
	User *objects.User `json:"user"`
}

// Activity IDs for Authentication
const (
	AuthenticationActivityLogon = 1 // A new logon session was requested.
	AuthenticationActivityLogoff = 2 // A logon session was terminated and no longer exists.
	AuthenticationActivityAuthenticationTicket = 3 // A Kerberos authentication ticket (TGT) was requested.
	AuthenticationActivityServiceTicketRequest = 4 // A Kerberos service ticket was requested.
	AuthenticationActivityServiceTicketRenew = 5 // A Kerberos service ticket was renewed.
	AuthenticationActivityPreauth = 6 // A preauthentication stage was engaged.
	AuthenticationActivityAccountSwitch = 7 // A utility or service switched the user account. See the <code>account_switch_type_id</code> attribute for more details.
)

// NewAuthentication creates a new Authentication event
func NewAuthentication(activityID int) *Authentication {
	return &Authentication{
		Event: ocsf.Event{
			CategoryUID: 3,
			ClassUID:    3002,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(3, 3002, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "iam",
			Class:       "authentication",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

