// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package iam

import (
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
	"time"
)

type UserAccess struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Privileges []string                   `json:"privileges"`
	Resource   *objects.ResourceDetails   `json:"resource,omitempty"`
	Resources  []*objects.ResourceDetails `json:"resources,omitempty"`
	User       *objects.User              `json:"user"`
}

const (
	UserAccessActivityAssignPrivileges = 1
	UserAccessActivityRevokePrivileges = 2
)

func NewUserAccess(activityID int) *UserAccess {
	return &UserAccess{
		Event: ocsf.Event{
			CategoryUID: 3,
			ClassUID:    3005,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(3, 3005, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "iam",
			Class:       "user_access",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}
