// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package findings

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/common/ocsf"
	"github.com/telhawk-systems/telhawk-stack/common/ocsf/objects"
)

type IamAnalysisFinding struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	AccessAnalysisResult *objects.AccessAnalysisResult `json:"access_analysis_result,omitempty"`
	Applications []*objects.Application `json:"applications,omitempty"`
	IdentityActivityMetrics *objects.IdentityActivityMetrics `json:"identity_activity_metrics,omitempty"`
	PermissionAnalysisResults []*objects.PermissionAnalysisResult `json:"permission_analysis_results,omitempty"`
	Remediation *objects.Remediation `json:"remediation,omitempty"`
	Resources []*objects.ResourceDetails `json:"resources,omitempty"`
	User *objects.User `json:"user,omitempty"`
}

func NewIamAnalysisFinding(activityID int) *IamAnalysisFinding {
	return &IamAnalysisFinding{
		Event: ocsf.Event{
			CategoryUID: 2,
			ClassUID:    2008,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(2, 2008, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "findings",
			Class:       "iam_analysis_finding",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

// Validate checks that all required fields are properly set
func (e *IamAnalysisFinding) Validate() error {
	// No required string fields to validate
	return nil
}

