// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package objects

// Account - The Account object contains details about the account that initiated or performed a specific activity within a system or application. Additionally, the Account object refers to logical Cloud and Software-as-a-Service (SaaS) based containers such as AWS Accounts, Azure Subscriptions, Oracle Cloud Compartments, Google Cloud Projects, and otherwise.
type Account struct {
	// The list of labels associated to the account.
	Labels []string `json:"labels,omitempty"`
	// The name of the account (e.g. ` GCP Project name `, ` Linux Account name ` or ` AWS Account name`).
	Name string `json:"name"`
	// The list of tags; `{key:value}` pairs associated to the account.
	Tags []*KeyValueObject `json:"tags,omitempty"`
	// The account type, normalized to the caption of 'account_type_id'. In the case of 'Other', it is defined by the event source.
	Type string `json:"type,omitempty"`
	// The normalized account type identifier.
	TypeId int `json:"type_id,omitempty"`
	// The unique identifier of the account (e.g. ` AWS Account ID `, ` OCID `, ` GCP Project ID `, ` Azure Subscription ID `, ` Google Workspace Customer ID `, or ` M365 Tenant UID`).
	Uid string `json:"uid"`
}
