// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type Advisory struct {
	Object
	AvgTimespan    *Timespan `json:"avg_timespan,omitempty"`
	Bulletin       string    `json:"bulletin,omitempty"`
	Classification string    `json:"classification,omitempty"`
	CreatedTime    int64     `json:"created_time,omitempty"`
	Desc           string    `json:"desc,omitempty"`
	InstallState   string    `json:"install_state,omitempty"`
	InstallStateId int       `json:"install_state_id,omitempty"`
	IsSuperseded   bool      `json:"is_superseded,omitempty"`
	ModifiedTime   int64     `json:"modified_time,omitempty"`
	Os             *Os       `json:"os,omitempty"`
	Product        *Product  `json:"product,omitempty"`
	References     []string  `json:"references,omitempty"`
	RelatedCves    []*Cve    `json:"related_cves,omitempty"`
	RelatedCwes    []*Cwe    `json:"related_cwes,omitempty"`
	Size           int64     `json:"size,omitempty"`
	SrcUrl         string    `json:"src_url,omitempty"`
	Title          string    `json:"title,omitempty"`
	Uid            string    `json:"uid"`
}
