// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Affected Software Package - The Affected Package object describes details about a software package identified as affected by a vulnerability/vulnerabilities.
type AffectedPackage struct {
	FixedInVersion string `json:"fixed_in_version,omitempty"`
	// The installation path of the affected package.
	Path string `json:"path,omitempty"`
	Remediation *Remediation `json:"remediation,omitempty"`
}
