// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Affected Code - The Affected Code object describes details about a code block identified as vulnerable.
type AffectedCode struct {
	// The column number of the last part of the assessed code identified as vulnerable.
	EndColumn int `json:"end_column,omitempty"`
	EndLine int `json:"end_line,omitempty"`
	// Details about the file that contains the affected code block.
	File *File `json:"file"`
	// Details about the user that owns the affected file.
	Owner *User `json:"owner,omitempty"`
	Remediation *Remediation `json:"remediation,omitempty"`
	// Details about the specific rule, e.g., those defined as part of a larger `policy`, that triggered the finding.
	Rule *Rule `json:"rule,omitempty"`
	// The column number of the first part of the assessed code identified as vulnerable.
	StartColumn int `json:"start_column,omitempty"`
	StartLine int `json:"start_line,omitempty"`
}
