// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// Analytic - The Analytic object contains details about the analytic technique used to analyze and derive insights from the data or information that led to the creation of a finding or conclusion.
type Analytic struct {
	// The algorithm used by the underlying analytic to generate the finding.
	Algorithm string `json:"algorithm,omitempty"`
	// The analytic category.
	Category string `json:"category,omitempty"`
	// The description of the analytic that generated the finding.
	Desc string `json:"desc,omitempty"`
	// The name of the analytic that generated the finding.
	Name string `json:"name"`
	// Other analytics related to this analytic.
	RelatedAnalytics []*Analytic `json:"related_analytics,omitempty"`
	// The Analytic state.
	State string `json:"state,omitempty"`
	// The Analytic state identifier.
	StateId int `json:"state_id,omitempty"`
	// The analytic type.
	Type string `json:"type,omitempty"`
	// The analytic type ID.
	TypeId int `json:"type_id"`
	// The unique identifier of the analytic that generated the finding.
	Uid string `json:"uid"`
	// The analytic version. For example: `1.1`.
	Version string `json:"version,omitempty"`
}
