// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type Analytic struct {
	Algorithm        string      `json:"algorithm,omitempty"`
	Category         string      `json:"category,omitempty"`
	Desc             string      `json:"desc,omitempty"`
	Name             string      `json:"name"`
	RelatedAnalytics []*Analytic `json:"related_analytics,omitempty"`
	State            string      `json:"state,omitempty"`
	StateId          int         `json:"state_id,omitempty"`
	Type             string      `json:"type,omitempty"`
	TypeId           int         `json:"type_id"`
	Uid              string      `json:"uid"`
	Version          string      `json:"version,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *Analytic) Validate() error {
	// No required string fields to validate
	return nil
}
