// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// API - The API, or Application Programming Interface, object represents  information pertaining to an API request and response.
type Api struct {
	// The information pertaining to the API group.
	Group *Group `json:"group,omitempty"`
	Operation string `json:"operation"`
	// Details pertaining to the API request.
	Request *Request `json:"request,omitempty"`
	// Details pertaining to the API response.
	Response *Response `json:"response,omitempty"`
	// The information pertaining to the API service.
	Service *Service `json:"service,omitempty"`
	// The version of the API service.
	Version string `json:"version,omitempty"`
}
