// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// Assessment - The Assessment object describes a point-in-time assessment, check, or evaluation of a specific configuration or signal against an asset, entity, person, or otherwise. For example, this can encapsulate `os_signals` from CrowdStrike Falcon Zero Trust Assessments, or account for `Datastore` configurations from Cyera, or capture details of Microsoft Intune configuration policies.
type Assessment struct {
	// The category that the assessment is part of. For example: `Prevention` or `Windows 10`.
	Category string `json:"category,omitempty"`
	// The description of the assessment criteria, or a description of the specific configuration or signal the assessment is targeting.
	Desc string `json:"desc,omitempty"`
	// Determines whether the assessment against the specific configuration or signal meets the assessments criteria. For example, if the assessment checks if a `Datastore` is encrypted or not, having encryption would be evaluated as `true`.
	MeetsCriteria bool `json:"meets_criteria"`
	// The name of the configuration or signal being assessed. For example: `Kernel Mode Code Integrity (KMCI)` or `publicAccessibilityState`.
	Name string `json:"name,omitempty"`
	// The details of any policy associated with an assessment.
	Policy *Policy `json:"policy,omitempty"`
	// The unique identifier of the configuration or signal being assessed. For example: the `signal_id`.
	Uid string `json:"uid,omitempty"`
}
