// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Authentication Token - The Authentication Token object represents standardized authentication tokens, tickets, or assertions that conform to established authentication protocols such as Kerberos, OIDC, and SAML. These tokens are issued by authentication servers and identity providers and carry protocol-specific metadata, lifecycle information, and security attributes defined by their respective specifications.
type AuthenticationToken struct {
	// The time that the authentication token was created.
	CreatedTime int64 `json:"created_time,omitempty"`
	// The encryption details of the authentication token.
	EncryptionDetails *EncryptionDetails `json:"encryption_details,omitempty"`
	// The expiration time of the authentication token.
	ExpirationTime int64 `json:"expiration_time,omitempty"`
	// Indicates whether the authentication token is renewable.
	IsRenewable bool `json:"is_renewable,omitempty"`
	KerberosFlags string `json:"kerberos_flags,omitempty"`
	// The type of the authentication token.
	Type string `json:"type,omitempty"`
	// The normalized authentication token type identifier.
	TypeId int `json:"type_id,omitempty"`
}
