// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Authentication Factor - An Authentication Factor object describes a category of methods used for identity verification in an authentication attempt.
type AuthFactor struct {
	// Device used to complete an authentication request.
	Device *Device `json:"device,omitempty"`
	// The email address used in an email-based authentication factor.
	EmailAddr string `json:"email_addr,omitempty"`
	FactorType string `json:"factor_type,omitempty"`
	FactorTypeId int `json:"factor_type_id"`
	IsHotp bool `json:"is_hotp,omitempty"`
	IsTotp bool `json:"is_totp,omitempty"`
	// The phone number used for a telephony-based authentication request.
	PhoneNumber string `json:"phone_number,omitempty"`
	// The name of provider for an authentication factor.
	Provider string `json:"provider,omitempty"`
	SecurityQuestions []string `json:"security_questions,omitempty"`
}
