// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

import "fmt"

type Certificate struct {
	CreatedTime    int64          `json:"created_time,omitempty"`
	ExpirationTime int64          `json:"expiration_time,omitempty"`
	Fingerprints   []*Fingerprint `json:"fingerprints,omitempty"`
	IsSelfSigned   bool           `json:"is_self_signed,omitempty"`
	Issuer         string         `json:"issuer"`
	Sans           []*San         `json:"sans,omitempty"`
	SerialNumber   string         `json:"serial_number"`
	Subject        string         `json:"subject,omitempty"`
	Uid            string         `json:"uid,omitempty"`
	Version        string         `json:"version,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *Certificate) Validate() error {
	if o.Issuer == "" {
		return fmt.Errorf("required field issuer is empty")
	}
	if o.SerialNumber == "" {
		return fmt.Errorf("required field serial_number is empty")
	}
	return nil
}
