// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// Classifier Details - The Classifier Details object describes details about the classifier used for data classification.
type ClassifierDetails struct {
	// The name of the classifier.
	Name string `json:"name,omitempty"`
	// The type of the classifier.
	Type string `json:"type"`
	// The unique identifier of the classifier.
	Uid string `json:"uid,omitempty"`
}
