// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Cloud - The Cloud object contains information about a cloud or Software-as-a-Service account or similar construct, such as AWS Account ID, regions, organizations, folders, compartments, tenants, etc.
type Cloud struct {
	Account *Account `json:"account,omitempty"`
	CloudPartition string `json:"cloud_partition,omitempty"`
	Org *Organization `json:"org,omitempty"`
	ProjectUid string `json:"project_uid,omitempty"`
	// The unique name of the Cloud services provider, such as AWS, MS Azure, GCP, etc.
	Provider string `json:"provider"`
	// The name of the cloud region, as defined by the cloud provider.
	Region string `json:"region,omitempty"`
	// The availability zone in the cloud region, as defined by the cloud provider.
	Zone string `json:"zone,omitempty"`
}
