// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type Compliance struct {
	Object
	Assessments          []*Assessment     `json:"assessments,omitempty"`
	Category             string            `json:"category,omitempty"`
	Checks               []*Check          `json:"checks,omitempty"`
	ComplianceReferences []*KbArticle      `json:"compliance_references,omitempty"`
	ComplianceStandards  []*KbArticle      `json:"compliance_standards,omitempty"`
	Control              string            `json:"control,omitempty"`
	ControlParameters    []*KeyValueObject `json:"control_parameters,omitempty"`
	Desc                 string            `json:"desc,omitempty"`
	Requirements         []string          `json:"requirements,omitempty"`
	Standards            []string          `json:"standards,omitempty"`
	Status               string            `json:"status,omitempty"`
	StatusCode           string            `json:"status_code,omitempty"`
	StatusDetail         string            `json:"status_detail,omitempty"`
	StatusDetails        []string          `json:"status_details,omitempty"`
	StatusId             int               `json:"status_id,omitempty"`
}
