// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// Container - The Container object describes an instance of a specific container. A container is a prepackaged, portable system image that runs isolated on an existing system using a container runtime like containerd.
type Container struct {
	// Commit hash of image created for docker or the SHA256 hash of the container. For example: `13550340a8681c84c861aac2e5b440161c2b33a3e4f302ac680ca5b686de48de`.
	Hash *Fingerprint `json:"hash,omitempty"`
	// The container image used as a template to run the container.
	Image *Image `json:"image,omitempty"`
	// The list of labels associated to the container.
	Labels []string `json:"labels,omitempty"`
	// The container name.
	Name string `json:"name,omitempty"`
	NetworkDriver string `json:"network_driver,omitempty"`
	Orchestrator string `json:"orchestrator,omitempty"`
	PodUuid string `json:"pod_uuid,omitempty"`
	Runtime string `json:"runtime,omitempty"`
	// The size of the container image.
	Size int64 `json:"size,omitempty"`
	// The tag used by the container. It can indicate version, format, OS.
	Tag string `json:"tag,omitempty"`
	// The list of tags; `{key:value}` pairs associated to the container.
	Tags []*KeyValueObject `json:"tags,omitempty"`
	// The full container unique identifier for this instantiation of the container. For example: `ac2ea168264a08f9aaca0dfc82ff3551418dfd22d02b713142a6843caa2f61bf`.
	Uid string `json:"uid,omitempty"`
}
