// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// CVE - The Common Vulnerabilities and Exposures (CVE) object represents publicly disclosed cybersecurity vulnerabilities defined in CVE Program catalog (<a target='_blank' href='https://cve.mitre.org/'>CVE</a>). There is one CVE Record for each vulnerability in the catalog.
type Cve struct {
	// The Record Creation Date identifies when the CVE ID was issued to a CVE Numbering Authority (CNA) or the CVE Record was published on the CVE List. Note that the Record Creation Date does not necessarily indicate when this vulnerability was discovered, shared with the affected vendor, publicly disclosed, or updated in CVE.
	CreatedTime int64 `json:"created_time,omitempty"`
	Cvss []*Cvss `json:"cvss,omitempty"`
	Cwe *Cwe `json:"cwe,omitempty"`
	CweUid string `json:"cwe_uid,omitempty"`
	CweUrl string `json:"cwe_url,omitempty"`
	// A brief description of the CVE Record.
	Desc string `json:"desc,omitempty"`
	Epss *Epss `json:"epss,omitempty"`
	// The Record Modified Date identifies when the CVE record was last updated.
	ModifiedTime int64 `json:"modified_time,omitempty"`
	// The product where the vulnerability was discovered.
	Product *Product `json:"product,omitempty"`
	// A list of reference URLs with additional information about the CVE Record.
	References []string `json:"references,omitempty"`
	// Describes the Common Weakness Enumeration <a target='_blank' href='https://cwe.mitre.org/'>(CWE)</a> details related to the CVE Record.
	RelatedCwes []*Cwe `json:"related_cwes,omitempty"`
	// A title or a brief phrase summarizing the CVE record.
	Title string `json:"title,omitempty"`
	// <p>The vulnerability type as selected from a large dropdown menu during CVE refinement.</p>Most frequently used vulnerability types are: `DoS`, `Code Execution`, `Overflow`, `Memory Corruption`, `Sql Injection`, `XSS`, `Directory Traversal`, `Http Response Splitting`, `Bypass something`, `Gain Information`, `Gain Privileges`, `CSRF`, `File Inclusion`. For more information see <a target='_blank' href='https://www.cvedetails.com/vulnerabilities-by-types.php'>Vulnerabilities By Type</a> distributions.
	Type string `json:"type,omitempty"`
	// The Common Vulnerabilities and Exposures unique number assigned to a specific computer vulnerability. A CVE Identifier begins with 4 digits representing the year followed by a sequence of digits that acts as a unique identifier. For example: `CVE-2021-12345`.
	Uid string `json:"uid"`
}
