// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

import "fmt"

type Cve struct {
	Object
	CreatedTime  int64    `json:"created_time,omitempty"`
	Cvss         []*Cvss  `json:"cvss,omitempty"`
	Cwe          *Cwe     `json:"cwe,omitempty"`
	CweUid       string   `json:"cwe_uid,omitempty"`
	CweUrl       string   `json:"cwe_url,omitempty"`
	Desc         string   `json:"desc,omitempty"`
	Epss         *Epss    `json:"epss,omitempty"`
	ModifiedTime int64    `json:"modified_time,omitempty"`
	Product      *Product `json:"product,omitempty"`
	References   []string `json:"references,omitempty"`
	RelatedCwes  []*Cwe   `json:"related_cwes,omitempty"`
	Title        string   `json:"title,omitempty"`
	Type         string   `json:"type,omitempty"`
	Uid          string   `json:"uid"`
}

// Validate checks that all required fields are properly set
func (o *Cve) Validate() error {
	if o.Uid == "" {
		return fmt.Errorf("required field uid is empty")
	}
	return nil
}
