// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// CVSS Score - The Common Vulnerability Scoring System (<a target='_blank' href='https://www.first.org/cvss/'>CVSS</a>) object provides a way to capture the principal characteristics of a vulnerability and produce a numerical score reflecting its severity.
type Cvss struct {
	// The CVSS base score. For example: `9.1`.
	BaseScore float64 `json:"base_score"`
	Depth string `json:"depth,omitempty"`
	// The Common Vulnerability Scoring System metrics. This attribute contains information on the CVE's impact. If the CVE has been analyzed, this attribute will contain any CVSSv2 or CVSSv3 information associated with the vulnerability. For example: `{ {"Access Vector", "Network"}, {"Access Complexity", "Low"}, ...}`.
	Metrics []*Metric `json:"metrics,omitempty"`
	// The CVSS overall score, impacted by base, temporal, and environmental metrics. For example: `9.1`.
	OverallScore float64 `json:"overall_score,omitempty"`
	// <p>The Common Vulnerability Scoring System (CVSS) Qualitative Severity Rating. A textual representation of the numeric score.</p><strong>CVSS v2.0</strong><ul><li>Low (0.0 – 3.9)</li><li>Medium (4.0 – 6.9)</li><li>High (7.0 – 10.0)</li></ul></p><strong>CVSS v3.0</strong><ul><li>None (0.0)</li><li>Low (0.1 - 3.9)</li><li>Medium (4.0 - 6.9)</li><li>High (7.0 - 8.9)</li><li>Critical (9.0 - 10.0)</li></ul>
	Severity string `json:"severity,omitempty"`
	// The source URL for the CVSS score. For example: `https://nvd.nist.gov/vuln/detail/CVE-2021-44228`
	SrcUrl string `json:"src_url,omitempty"`
	VectorString string `json:"vector_string,omitempty"`
	// The vendor that provided the CVSS score. For example: `NVD, REDHAT` etc.
	VendorName string `json:"vendor_name,omitempty"`
	// The CVSS version. For example: `3.1`.
	Version string `json:"version"`
}
