// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package objects

// MITRE D3FEND™ Technique - The MITRE D3FEND™ Technique object describes the leaf defensive technique ID and/or name associated to a countermeasure.
type D3fTechnique struct {
	// The name of the defensive technique. For example: `IO Port Restriction`.
	Name string `json:"name"`
	// The versioned permalink of the defensive technique. For example: `https://d3fend.mitre.org/technique/d3f:IOPortRestriction/`.
	SrcUrl string `json:"src_url,omitempty"`
	// The unique identifier of the defensive technique. For example: `D3-IOPR`.
	Uid string `json:"uid"`
}
