// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// Data Security - The Data Security object describes the characteristics, techniques and content of a Data Loss Prevention (DLP), Data Loss Detection (DLD), Data Classification, or similar tools' finding, alert, or detection mechanism(s).
type DataSecurity struct {
	DataLifecycleState string `json:"data_lifecycle_state,omitempty"`
	DataLifecycleStateId int `json:"data_lifecycle_state_id,omitempty"`
	DetectionPattern string `json:"detection_pattern,omitempty"`
	DetectionSystem string `json:"detection_system,omitempty"`
	DetectionSystemId int `json:"detection_system_id,omitempty"`
	PatternMatch string `json:"pattern_match,omitempty"`
	// Details about the policy that triggered the finding.
	Policy *Policy `json:"policy,omitempty"`
}
