// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Data Classification - The Data Classification object includes information about data classification levels and data category types.
type DataClassification struct {
	// The name of the data classification category that data matched into, e.g. Financial, Personal, Governmental, etc.
	Category string `json:"category,omitempty"`
	// The normalized identifier of the data classification category.
	CategoryId int `json:"category_id,omitempty"`
	ClassifierDetails *ClassifierDetails `json:"classifier_details,omitempty"`
	Confidentiality string `json:"confidentiality,omitempty"`
	ConfidentialityId int `json:"confidentiality_id,omitempty"`
	// Details about the data discovered by classification job.
	DiscoveryDetails []*DiscoveryDetails `json:"discovery_details,omitempty"`
	// Details about the data policy that governs data handling and security measures related to classification.
	Policy *Policy `json:"policy,omitempty"`
	// Size of the data classified.
	Size int64 `json:"size,omitempty"`
	// The source URL pointing towards the full classification job details.
	SrcUrl string `json:"src_url,omitempty"`
	// The resultant status of the classification job normalized to the caption of the `status_id` value. In the case of 'Other', it is defined by the event source.
	Status string `json:"status,omitempty"`
	// The contextual description of the `status, status_id` value.
	StatusDetails []string `json:"status_details,omitempty"`
	// The normalized status identifier of the classification job.
	StatusId int `json:"status_id,omitempty"`
	// The total count of discovered entities, by the classification job.
	Total int `json:"total,omitempty"`
	// The unique identifier of the classification job.
	Uid string `json:"uid,omitempty"`
}
