// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type DataSecurity struct {
	DataClassification
	DataLifecycleState   string  `json:"data_lifecycle_state,omitempty"`
	DataLifecycleStateId int     `json:"data_lifecycle_state_id,omitempty"`
	DetectionPattern     string  `json:"detection_pattern,omitempty"`
	DetectionSystem      string  `json:"detection_system,omitempty"`
	DetectionSystemId    int     `json:"detection_system_id,omitempty"`
	PatternMatch         string  `json:"pattern_match,omitempty"`
	Policy               *Policy `json:"policy,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *DataSecurity) Validate() error {
	// No required string fields to validate
	return nil
}
