// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// DCE/RPC - The DCE/RPC, or Distributed Computing Environment/Remote Procedure Call, object describes the remote procedure call system for distributed computing environments.
type DceRpc struct {
	// The request command (e.g. REQUEST, BIND).
	Command string `json:"command,omitempty"`
	// The reply to the request command (e.g. RESPONSE, BINDACK or FAULT).
	CommandResponse string `json:"command_response,omitempty"`
	// The list of interface flags.
	Flags []string `json:"flags"`
	Opnum int `json:"opnum,omitempty"`
	RpcInterface *RpcInterface `json:"rpc_interface"`
}
