// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// DCE/RPC - The DCE/RPC, or Distributed Computing Environment/Remote Procedure Call, object describes the remote procedure call system for distributed computing environments.
type DceRpc struct {
	// The request command (e.g. REQUEST, BIND).
	Command string `json:"command,omitempty"`
	// The reply to the request command (e.g. RESPONSE, BINDACK or FAULT).
	CommandResponse string `json:"command_response,omitempty"`
	// The list of interface flags.
	Flags []string `json:"flags"`
	Opnum int `json:"opnum,omitempty"`
	RpcInterface *RpcInterface `json:"rpc_interface"`
}
