// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type DeviceHwInfo struct {
	Object
	BiosDate          string        `json:"bios_date,omitempty"`
	BiosManufacturer  string        `json:"bios_manufacturer,omitempty"`
	BiosVer           string        `json:"bios_ver,omitempty"`
	Chassis           string        `json:"chassis,omitempty"`
	CpuArchitecture   string        `json:"cpu_architecture,omitempty"`
	CpuArchitectureId int           `json:"cpu_architecture_id,omitempty"`
	CpuBits           int           `json:"cpu_bits,omitempty"`
	CpuCores          int           `json:"cpu_cores,omitempty"`
	CpuCount          int           `json:"cpu_count,omitempty"`
	CpuSpeed          int           `json:"cpu_speed,omitempty"`
	CpuType           string        `json:"cpu_type,omitempty"`
	DesktopDisplay    *Display      `json:"desktop_display,omitempty"`
	KeyboardInfo      *KeyboardInfo `json:"keyboard_info,omitempty"`
	RamSize           int           `json:"ram_size,omitempty"`
	SerialNumber      string        `json:"serial_number,omitempty"`
	Uuid              string        `json:"uuid,omitempty"`
	VendorName        string        `json:"vendor_name,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *DeviceHwInfo) Validate() error {
	// No required string fields to validate
	return nil
}
