// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// Device Hardware Info - The Device Hardware Information object contains details and specifications of the physical components that make up a device. This information provides an overview of the hardware capabilities, configuration, and characteristics of the device.
type DeviceHwInfo struct {
	BiosDate string `json:"bios_date,omitempty"`
	BiosManufacturer string `json:"bios_manufacturer,omitempty"`
	BiosVer string `json:"bios_ver,omitempty"`
	Chassis string `json:"chassis,omitempty"`
	CpuArchitecture string `json:"cpu_architecture,omitempty"`
	CpuArchitectureId int `json:"cpu_architecture_id,omitempty"`
	CpuBits int `json:"cpu_bits,omitempty"`
	CpuCores int `json:"cpu_cores,omitempty"`
	CpuCount int `json:"cpu_count,omitempty"`
	CpuSpeed int `json:"cpu_speed,omitempty"`
	CpuType string `json:"cpu_type,omitempty"`
	DesktopDisplay *Display `json:"desktop_display,omitempty"`
	KeyboardInfo *KeyboardInfo `json:"keyboard_info,omitempty"`
	RamSize int `json:"ram_size,omitempty"`
	// The device manufacturer serial number.
	SerialNumber string `json:"serial_number,omitempty"`
	// The device manufacturer assigned universally unique hardware identifier. For SMBIOS compatible devices such as those running Linux and Windows, it is the UUID member of the System Information structure in the SMBIOS information. For macOS devices, it is the Hardware UUID (also known as IOPlatformUUID in the I/O Registry).
	Uuid string `json:"uuid,omitempty"`
	// The device manufacturer.
	VendorName string `json:"vendor_name,omitempty"`
}
