// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// Digital Signature - The Digital Signature object contains information about the cryptographic mechanism used to verify the authenticity, integrity, and origin of the file or application.
type DigitalSignature struct {
	// The digital signature algorithm used to create the signature, normalized to the caption of 'algorithm_id'. In the case of 'Other', it is defined by the event source.
	Algorithm string `json:"algorithm,omitempty"`
	// The identifier of the normalized digital signature algorithm.
	AlgorithmId int `json:"algorithm_id"`
	Certificate *Certificate `json:"certificate,omitempty"`
	// The time when the digital signature was created.
	CreatedTime int64 `json:"created_time,omitempty"`
	DeveloperUid string `json:"developer_uid,omitempty"`
	Digest *Fingerprint `json:"digest,omitempty"`
	// The digital signature state defines the signature state, normalized to the caption of 'state_id'. In the case of 'Other', it is defined by the event source.
	State string `json:"state,omitempty"`
	// The normalized identifier of the signature state.
	StateId int `json:"state_id,omitempty"`
}
