// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// Discovery Details - The Discovery Details object describes results of a discovery task/job.
type DiscoveryDetails struct {
	// The number of discovered entities of the specified type.
	Count int `json:"count,omitempty"`
	// Details about where in the target entity, specified information was discovered. Only the attributes, relevant to the target entity type should be populated.
	OccurrenceDetails *OccurrenceDetails `json:"occurrence_details,omitempty"`
	// Details about where in the target entity, specified information was discovered. Only the attributes, relevant to the target entity type should be populated.
	Occurrences []*OccurrenceDetails `json:"occurrences,omitempty"`
	// The specific type of information that was discovered. e.g.` name, phone_number, etc.`
	Type string `json:"type,omitempty"`
	// Optionally, the specific value of discovered information.
	Value string `json:"value,omitempty"`
}
