// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package objects

// Display - The Display object contains information about the physical or virtual display connected to a computer system.
type Display struct {
	ColorDepth int `json:"color_depth,omitempty"`
	PhysicalHeight int `json:"physical_height,omitempty"`
	PhysicalOrientation int `json:"physical_orientation,omitempty"`
	PhysicalWidth int `json:"physical_width,omitempty"`
	ScaleFactor int `json:"scale_factor,omitempty"`
}
