// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type Display struct {
	ColorDepth          int `json:"color_depth,omitempty"`
	PhysicalHeight      int `json:"physical_height,omitempty"`
	PhysicalOrientation int `json:"physical_orientation,omitempty"`
	PhysicalWidth       int `json:"physical_width,omitempty"`
	ScaleFactor         int `json:"scale_factor,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *Display) Validate() error {
	// No required string fields to validate
	return nil
}
