// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// DNS Query - The DNS query object represents a specific request made to the Domain Name System (DNS) to retrieve information about a domain or perform a DNS operation. This object encapsulates the necessary attributes and methods to construct and send DNS queries, specify the query type (e.g., A, AAAA, MX).
type DnsQuery struct {
	// The hostname or domain being queried. For example: `www.example.com`
	Hostname string `json:"hostname"`
	Opcode string `json:"opcode,omitempty"`
	OpcodeId int `json:"opcode_id,omitempty"`
}
