// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

import "fmt"

type DnsQuery struct {
	Hostname string `json:"hostname"`
	Opcode   string `json:"opcode,omitempty"`
	OpcodeId int    `json:"opcode_id,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *DnsQuery) Validate() error {
	if o.Hostname == "" {
		return fmt.Errorf("required field hostname is empty")
	}
	return nil
}
