// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// DNS Answer - The DNS Answer object represents a specific response provided by the Domain Name System (DNS) when querying for information about a domain or performing a DNS operation. It encapsulates the relevant details and data returned by the DNS server in response to a query.
type DnsAnswer struct {
	// The class of DNS data contained in this resource record. See <a target='_blank' href='https://www.rfc-editor.org/rfc/rfc1035.txt'>RFC1035</a>. For example: `IN`.
	Class string `json:"class,omitempty"`
	// The list of DNS answer header flag IDs.
	FlagIds []int `json:"flag_ids,omitempty"`
	// The list of DNS answer header flags.
	Flags []string `json:"flags,omitempty"`
	Rdata string `json:"rdata"`
	Ttl int `json:"ttl,omitempty"`
	// The type of data contained in this resource record. See <a target='_blank' href='https://www.rfc-editor.org/rfc/rfc1035.txt'>RFC1035</a>. For example: `CNAME`.
	Type string `json:"type,omitempty"`
}
