// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

import "fmt"

type DnsAnswer struct {
	Class   string   `json:"class,omitempty"`
	FlagIds []int    `json:"flag_ids,omitempty"`
	Flags   []string `json:"flags,omitempty"`
	Rdata   string   `json:"rdata"`
	Ttl     int      `json:"ttl,omitempty"`
	Type    string   `json:"type,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *DnsAnswer) Validate() error {
	if o.Rdata == "" {
		return fmt.Errorf("required field rdata is empty")
	}
	return nil
}
