// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type Edge struct {
	Data       string `json:"data,omitempty"`
	IsDirected bool   `json:"is_directed,omitempty"`
	Name       string `json:"name,omitempty"`
	Relation   string `json:"relation,omitempty"`
	Source     string `json:"source"`
	Target     string `json:"target"`
	Uid        string `json:"uid,omitempty"`
}
