// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Email - The Email object describes the email metadata such as sender, recipients, and direction, and can include embedded URLs and files.
type Email struct {
	Cc []string `json:"cc,omitempty"`
	CcMailboxes []string `json:"cc_mailboxes,omitempty"`
	DeliveredTo string `json:"delivered_to,omitempty"`
	DeliveredToList []string `json:"delivered_to_list,omitempty"`
	// The files embedded or attached to the email.
	Files []*File `json:"files,omitempty"`
	From string `json:"from,omitempty"`
	FromList []string `json:"from_list,omitempty"`
	FromMailbox string `json:"from_mailbox,omitempty"`
	FromMailboxes []string `json:"from_mailboxes,omitempty"`
	HttpHeaders []*HttpHeader `json:"http_headers,omitempty"`
	IsRead bool `json:"is_read,omitempty"`
	MessageUid string `json:"message_uid,omitempty"`
	RawHeader string `json:"raw_header,omitempty"`
	ReplyTo string `json:"reply_to,omitempty"`
	ReplyToList []string `json:"reply_to_list,omitempty"`
	ReplyToMailboxes []string `json:"reply_to_mailboxes,omitempty"`
	ReturnPath string `json:"return_path,omitempty"`
	Sender string `json:"sender,omitempty"`
	SenderMailbox string `json:"sender_mailbox,omitempty"`
	// The size in bytes of the email, including attachments.
	Size int64 `json:"size,omitempty"`
	SmtpFrom string `json:"smtp_from,omitempty"`
	SmtpTo []string `json:"smtp_to,omitempty"`
	// The email header Subject value, as defined by RFC 5322.
	Subject string `json:"subject,omitempty"`
	To []string `json:"to,omitempty"`
	ToMailboxes []string `json:"to_mailboxes,omitempty"`
	// The unique identifier of the email thread.
	Uid string `json:"uid,omitempty"`
	// The URLs embedded in the email.
	Urls []*Url `json:"urls,omitempty"`
	XOriginatingIp []string `json:"x_originating_ip,omitempty"`
}
