// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package objects

// Email Authentication - The Email Authentication object describes the Sender Policy Framework (SPF), DomainKeys Identified Mail (DKIM) and Domain-based Message Authentication, Reporting and Conformance (DMARC) attributes of an email.
type EmailAuth struct {
	Dkim string `json:"dkim,omitempty"`
	DkimDomain string `json:"dkim_domain,omitempty"`
	DkimSignature string `json:"dkim_signature,omitempty"`
	Dmarc string `json:"dmarc,omitempty"`
	DmarcOverride string `json:"dmarc_override,omitempty"`
	DmarcPolicy string `json:"dmarc_policy,omitempty"`
	Spf string `json:"spf,omitempty"`
}
