// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Encryption Details - Details about the encryption methodology utilized.
type EncryptionDetails struct {
	// The encryption algorithm used, normalized to the caption of 'algorithm_id
	Algorithm string `json:"algorithm,omitempty"`
	// The encryption algorithm used.
	AlgorithmId int `json:"algorithm_id,omitempty"`
	// The length of the encryption key used.
	KeyLength int `json:"key_length,omitempty"`
	// The unique identifier of the key used for encryption. For example, AWS KMS Key ARN.
	KeyUid string `json:"key_uid,omitempty"`
	// The type of the encryption used.
	Type string `json:"type,omitempty"`
}
