// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type EncryptionDetails struct {
	Object
	Algorithm   string `json:"algorithm,omitempty"`
	AlgorithmId int    `json:"algorithm_id,omitempty"`
	KeyLength   int    `json:"key_length,omitempty"`
	KeyUid      string `json:"key_uid,omitempty"`
	Type        string `json:"type,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *EncryptionDetails) Validate() error {
	// No required string fields to validate
	return nil
}
