// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// Endpoint Connection - The Endpoint Connection object contains information detailing a connection attempt to an endpoint.
type EndpointConnection struct {
	// A numerical response status code providing details about the connection.
	Code int `json:"code,omitempty"`
	// Provides characteristics of the network endpoint.
	NetworkEndpoint *NetworkEndpoint `json:"network_endpoint,omitempty"`
}
