// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// Endpoint - The Endpoint object describes a physical or virtual device that connects to and exchanges information with a computer network. Some examples of endpoints are mobile devices, desktop computers, virtual machines, embedded devices, and servers. Internet-of-Things devices—like cameras, lighting, refrigerators, security systems, smart speakers, and thermostats—are also endpoints.
type Endpoint struct {
	AgentList []*Agent `json:"agent_list,omitempty"`
	// The name of the domain that the endpoint belongs to or that corresponds to the endpoint.
	Domain string `json:"domain,omitempty"`
	// The fully qualified name of the endpoint.
	Hostname string `json:"hostname,omitempty"`
	HwInfo *DeviceHwInfo `json:"hw_info,omitempty"`
	InstanceUid string `json:"instance_uid,omitempty"`
	InterfaceName string `json:"interface_name,omitempty"`
	InterfaceUid string `json:"interface_uid,omitempty"`
	// The IP address of the endpoint, in either IPv4 or IPv6 format.
	Ip string `json:"ip,omitempty"`
	// The geographical location of the endpoint.
	Location *Location `json:"location,omitempty"`
	// The Media Access Control (MAC) address of the endpoint.
	Mac string `json:"mac,omitempty"`
	// The short name of the endpoint.
	Name string `json:"name"`
	// The endpoint operating system.
	Os *Os `json:"os,omitempty"`
	// The identity of the service or user account that owns the endpoint or was last logged into it.
	Owner *User `json:"owner,omitempty"`
	SubnetUid string `json:"subnet_uid,omitempty"`
	// The endpoint type. For example: `unknown`, `server`, `desktop`, `laptop`, `tablet`, `mobile`, `virtual`, `browser`, or `other`.
	Type string `json:"type,omitempty"`
	// The endpoint type ID.
	TypeId int `json:"type_id,omitempty"`
	// The unique identifier of the endpoint.
	Uid string `json:"uid"`
	VlanUid string `json:"vlan_uid,omitempty"`
	VpcUid string `json:"vpc_uid,omitempty"`
	Zone string `json:"zone,omitempty"`
}
