// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

import "fmt"

type Endpoint struct {
	AgentList     []*Agent      `json:"agent_list,omitempty"`
	Domain        string        `json:"domain,omitempty"`
	Hostname      string        `json:"hostname,omitempty"`
	HwInfo        *DeviceHwInfo `json:"hw_info,omitempty"`
	InstanceUid   string        `json:"instance_uid,omitempty"`
	InterfaceName string        `json:"interface_name,omitempty"`
	InterfaceUid  string        `json:"interface_uid,omitempty"`
	Ip            string        `json:"ip,omitempty"`
	Location      *Location     `json:"location,omitempty"`
	Mac           string        `json:"mac,omitempty"`
	Name          string        `json:"name"`
	Os            *Os           `json:"os,omitempty"`
	Owner         *User         `json:"owner,omitempty"`
	SubnetUid     string        `json:"subnet_uid,omitempty"`
	Type          string        `json:"type,omitempty"`
	TypeId        int           `json:"type_id,omitempty"`
	Uid           string        `json:"uid"`
	VlanUid       string        `json:"vlan_uid,omitempty"`
	VpcUid        string        `json:"vpc_uid,omitempty"`
	Zone          string        `json:"zone,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *Endpoint) Validate() error {
	if o.Uid == "" {
		return fmt.Errorf("required field uid is empty")
	}
	if o.Name == "" {
		return fmt.Errorf("required field name is empty")
	}
	return nil
}
