// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type Epss struct {
	Object
	CreatedTime int64   `json:"created_time,omitempty"`
	Percentile  float64 `json:"percentile,omitempty"`
	Score       string  `json:"score"`
	Version     string  `json:"version,omitempty"`
}
