// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Schema Extension - The OCSF Schema Extension object provides detailed information about the schema extension used to construct the event. The schema extensions are registered in the <a target='_blank' href='https://github.com/ocsf/ocsf-schema/blob/main/extensions.md'>extensions.md</a> file.
type Extension struct {
	// The schema extension name. For example: `dev`.
	Name string `json:"name"`
	// The schema extension unique identifier. For example: `999`.
	Uid string `json:"uid"`
	// The schema extension version. For example: `1.0.0-alpha.2`.
	Version string `json:"version"`
}
