// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Feature - The Feature object provides information about the software product feature that generated a specific event. It encompasses details related to the capabilities, components, user interface (UI) design, and performance upgrades associated with the feature.
type Feature struct {
	// The name of the feature.
	Name string `json:"name"`
	// The unique identifier of the feature.
	Uid string `json:"uid"`
	// The version of the feature.
	Version string `json:"version,omitempty"`
}
