// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

import "fmt"

type File struct {
	AccessedTime       int64              `json:"accessed_time,omitempty"`
	Accessor           *User              `json:"accessor,omitempty"`
	Attributes         int                `json:"attributes,omitempty"`
	CompanyName        string             `json:"company_name,omitempty"`
	Confidentiality    string             `json:"confidentiality,omitempty"`
	ConfidentialityId  int                `json:"confidentiality_id,omitempty"`
	CreatedTime        int64              `json:"created_time,omitempty"`
	Creator            *User              `json:"creator,omitempty"`
	Desc               string             `json:"desc,omitempty"`
	DriveType          string             `json:"drive_type,omitempty"`
	DriveTypeId        int                `json:"drive_type_id,omitempty"`
	EncryptionDetails  *EncryptionDetails `json:"encryption_details,omitempty"`
	Ext                string             `json:"ext,omitempty"`
	Hashes             []*Fingerprint     `json:"hashes,omitempty"`
	InternalName       string             `json:"internal_name,omitempty"`
	IsDeleted          bool               `json:"is_deleted,omitempty"`
	IsEncrypted        bool               `json:"is_encrypted,omitempty"`
	IsPublic           bool               `json:"is_public,omitempty"`
	IsReadonly         bool               `json:"is_readonly,omitempty"`
	IsSystem           bool               `json:"is_system,omitempty"`
	MimeType           string             `json:"mime_type,omitempty"`
	ModifiedTime       int64              `json:"modified_time,omitempty"`
	Modifier           *User              `json:"modifier,omitempty"`
	Name               string             `json:"name"`
	Owner              *User              `json:"owner,omitempty"`
	ParentFolder       string             `json:"parent_folder,omitempty"`
	Path               string             `json:"path,omitempty"`
	Product            *Product           `json:"product,omitempty"`
	SecurityDescriptor string             `json:"security_descriptor,omitempty"`
	Signature          *DigitalSignature  `json:"signature,omitempty"`
	Size               int64              `json:"size,omitempty"`
	StorageClass       string             `json:"storage_class,omitempty"`
	Tags               []*KeyValueObject  `json:"tags,omitempty"`
	Type               string             `json:"type,omitempty"`
	TypeId             int                `json:"type_id"`
	Uid                string             `json:"uid,omitempty"`
	Uri                string             `json:"uri,omitempty"`
	Url                *Url               `json:"url,omitempty"`
	Version            string             `json:"version,omitempty"`
	Volume             string             `json:"volume,omitempty"`
	Xattributes        *Object            `json:"xattributes,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *File) Validate() error {
	if o.Name == "" {
		return fmt.Errorf("required field name is empty")
	}
	return nil
}
