// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// Finding Information - The Finding Information object describes metadata related to a security finding generated by a security tool or system.
type FindingInfo struct {
	Analytic *Analytic `json:"analytic,omitempty"`
	AttackGraph *Graph `json:"attack_graph,omitempty"`
	// The <a target='_blank' href='https://attack.mitre.org'>MITRE ATT&CK®</a> technique and associated tactics related to the finding.
	Attacks []*Attack `json:"attacks,omitempty"`
	// The time when the finding was created.
	CreatedTime int64 `json:"created_time,omitempty"`
	DataSources []string `json:"data_sources,omitempty"`
	// The description of the reported finding.
	Desc string `json:"desc,omitempty"`
	// The time when the finding was first observed. e.g. The time when a vulnerability was first observed. <p>It can differ from the `created_time` timestamp, which reflects the time this finding was created.</p>
	FirstSeenTime int64 `json:"first_seen_time,omitempty"`
	KillChain []*KillChainPhase `json:"kill_chain,omitempty"`
	// The time when the finding was most recently observed. e.g. The time when a vulnerability was most recently observed. <p>It can differ from the `modified_time` timestamp, which reflects the time this finding was last modified.</p>
	LastSeenTime int64 `json:"last_seen_time,omitempty"`
	// The time when the finding was last modified.
	ModifiedTime int64 `json:"modified_time,omitempty"`
	// Details about the product that reported the finding.
	Product *Product `json:"product,omitempty"`
	// The unique identifier of the product that reported the finding.
	ProductUid string `json:"product_uid,omitempty"`
	// Other analytics related to this finding.
	RelatedAnalytics []*Analytic `json:"related_analytics,omitempty"`
	RelatedEvents []*RelatedEvent `json:"related_events,omitempty"`
	RelatedEventsCount int `json:"related_events_count,omitempty"`
	// The URL pointing to the source of the finding.
	SrcUrl string `json:"src_url,omitempty"`
	// The list of tags; `{key:value}` pairs associated with the finding.
	Tags []*KeyValueObject `json:"tags,omitempty"`
	// A title or a brief phrase summarizing the reported finding.
	Title string `json:"title,omitempty"`
	// The list of key traits or characteristics extracted from the finding.
	Traits []*Trait `json:"traits,omitempty"`
	// One or more types of the reported finding.
	Types []string `json:"types,omitempty"`
	// The unique identifier of the reported finding.
	Uid string `json:"uid"`
	// The alternative unique identifier of the reported finding.
	UidAlt string `json:"uid_alt,omitempty"`
}
