// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type Finding struct {
	Object
	CreatedTime    int64           `json:"created_time,omitempty"`
	Desc           string          `json:"desc,omitempty"`
	FirstSeenTime  int64           `json:"first_seen_time,omitempty"`
	LastSeenTime   int64           `json:"last_seen_time,omitempty"`
	ModifiedTime   int64           `json:"modified_time,omitempty"`
	Product        *Product        `json:"product,omitempty"`
	ProductUid     string          `json:"product_uid,omitempty"`
	RelatedEvents  []*RelatedEvent `json:"related_events,omitempty"`
	Remediation    *Remediation    `json:"remediation,omitempty"`
	SrcUrl         string          `json:"src_url,omitempty"`
	SupportingData string          `json:"supporting_data,omitempty"`
	Title          string          `json:"title"`
	Types          []string        `json:"types,omitempty"`
	Uid            string          `json:"uid"`
}
