// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

import "fmt"

type FindingInfo struct {
	Analytic           *Analytic         `json:"analytic,omitempty"`
	AttackGraph        *Graph            `json:"attack_graph,omitempty"`
	Attacks            []*Attack         `json:"attacks,omitempty"`
	CreatedTime        int64             `json:"created_time,omitempty"`
	DataSources        []string          `json:"data_sources,omitempty"`
	Desc               string            `json:"desc,omitempty"`
	FirstSeenTime      int64             `json:"first_seen_time,omitempty"`
	KillChain          []*KillChainPhase `json:"kill_chain,omitempty"`
	LastSeenTime       int64             `json:"last_seen_time,omitempty"`
	ModifiedTime       int64             `json:"modified_time,omitempty"`
	Product            *Product          `json:"product,omitempty"`
	ProductUid         string            `json:"product_uid,omitempty"`
	RelatedAnalytics   []*Analytic       `json:"related_analytics,omitempty"`
	RelatedEvents      []*RelatedEvent   `json:"related_events,omitempty"`
	RelatedEventsCount int               `json:"related_events_count,omitempty"`
	SrcUrl             string            `json:"src_url,omitempty"`
	Tags               []*KeyValueObject `json:"tags,omitempty"`
	Title              string            `json:"title,omitempty"`
	Traits             []*Trait          `json:"traits,omitempty"`
	Types              []string          `json:"types,omitempty"`
	Uid                string            `json:"uid"`
	UidAlt             string            `json:"uid_alt,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *FindingInfo) Validate() error {
	if o.Uid == "" {
		return fmt.Errorf("required field uid is empty")
	}
	return nil
}
