// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// Finding - The Finding object describes metadata related to a security finding generated by a security tool or system.
type Finding struct {
	// The time when the finding was created.
	CreatedTime int64 `json:"created_time,omitempty"`
	// The description of the reported finding.
	Desc string `json:"desc,omitempty"`
	// The time when the finding was first observed.
	FirstSeenTime int64 `json:"first_seen_time,omitempty"`
	// The time when the finding was most recently observed.
	LastSeenTime int64 `json:"last_seen_time,omitempty"`
	// The time when the finding was last modified.
	ModifiedTime int64 `json:"modified_time,omitempty"`
	// Details about the product that reported the finding.
	Product *Product `json:"product,omitempty"`
	// The unique identifier of the product that reported the finding.
	ProductUid string `json:"product_uid,omitempty"`
	RelatedEvents []*RelatedEvent `json:"related_events,omitempty"`
	Remediation *Remediation `json:"remediation,omitempty"`
	// The URL pointing to the source of the finding.
	SrcUrl string `json:"src_url,omitempty"`
	SupportingData string `json:"supporting_data,omitempty"`
	// A title or a brief phrase summarizing the reported finding.
	Title string `json:"title"`
	// One or more types of the reported finding.
	Types []string `json:"types,omitempty"`
	// The unique identifier of the reported finding.
	Uid string `json:"uid"`
}
