// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Firewall Rule - The Firewall Rule object represents a specific rule within a firewall policy or event. It contains information about a rule's configuration, properties, and associated actions that define how network traffic is handled by the firewall.
type FirewallRule struct {
	// The rule trigger condition for the rule. For example: SQL_INJECTION.
	Condition string `json:"condition,omitempty"`
	// The rule response time duration, usually used for challenge completion time.
	Duration int64 `json:"duration,omitempty"`
	MatchDetails []string `json:"match_details,omitempty"`
	MatchLocation string `json:"match_location,omitempty"`
	RateLimit int `json:"rate_limit,omitempty"`
	Sensitivity string `json:"sensitivity,omitempty"`
}
