// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type FunctionInvocation struct {
	Error       string       `json:"error,omitempty"`
	Parameters  []*Parameter `json:"parameters,omitempty"`
	ReturnValue string       `json:"return_value,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *FunctionInvocation) Validate() error {
	// No required string fields to validate
	return nil
}
