// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type HttpCookie struct {
	Object
	Domain         string `json:"domain,omitempty"`
	ExpirationTime int64  `json:"expiration_time,omitempty"`
	HttpOnly       bool   `json:"http_only,omitempty"`
	IsHttpOnly     bool   `json:"is_http_only,omitempty"`
	IsSecure       bool   `json:"is_secure,omitempty"`
	Name           string `json:"name"`
	Path           string `json:"path,omitempty"`
	Samesite       string `json:"samesite,omitempty"`
	Secure         bool   `json:"secure,omitempty"`
	Value          string `json:"value"`
}
