// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// HTTP Request - The HTTP Request object represents the attributes of a request made to a web server. It encapsulates the details and metadata associated with an HTTP request, including the request method, headers, URL, query parameters, body content, and other relevant information.
type HttpRequest struct {
	Args string `json:"args,omitempty"`
	// The actual length of the HTTP request body, in number of bytes, independent of a potentially existing Content-Length header.
	BodyLength int `json:"body_length,omitempty"`
	HttpHeaders []*HttpHeader `json:"http_headers,omitempty"`
	// The <a target='_blank' href='https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods'>HTTP request method</a> indicates the desired action to be performed for a given resource.
	HttpMethod string `json:"http_method,omitempty"`
	// The length of the entire HTTP request, in number of bytes.
	Length int `json:"length,omitempty"`
	Referrer string `json:"referrer,omitempty"`
	// The unique identifier of the http request.
	Uid string `json:"uid,omitempty"`
	// The URL object that pertains to the request.
	Url *Url `json:"url,omitempty"`
	UserAgent string `json:"user_agent,omitempty"`
	// The Hypertext Transfer Protocol (HTTP) version.
	Version string `json:"version,omitempty"`
	XForwardedFor []string `json:"x_forwarded_for,omitempty"`
}
