// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// HTTP Cookie - The HTTP Cookie object, also known as a web cookie or browser cookie, contains details and values pertaining to a small piece of data that a server sends to a user's web browser. This data is then stored by the browser and sent back to the server with subsequent requests, allowing the server to remember and track certain information about the user's browsing session or preferences.
type HttpCookie struct {
	// The domain name for the server from which the http_cookie is served.
	Domain string `json:"domain,omitempty"`
	// The expiration time of the HTTP cookie.
	ExpirationTime int64 `json:"expiration_time,omitempty"`
	HttpOnly bool `json:"http_only,omitempty"`
	IsHttpOnly bool `json:"is_http_only,omitempty"`
	IsSecure bool `json:"is_secure,omitempty"`
	// The HTTP cookie name.
	Name string `json:"name"`
	// The path of the HTTP cookie.
	Path string `json:"path,omitempty"`
	Samesite string `json:"samesite,omitempty"`
	Secure bool `json:"secure,omitempty"`
	// The HTTP cookie value.
	Value string `json:"value"`
}
