// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// HTTP Header - The HTTP Header object represents the headers sent in an HTTP request or response. HTTP headers are key-value pairs that convey additional information about the HTTP message, including details about the content, caching, authentication, encoding, and other aspects of the communication.
type HttpHeader struct {
	// The name of the HTTP header.
	Name string `json:"name"`
	// The value of the HTTP header.
	Value string `json:"value"`
}
