// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type Idp struct {
	AuthFactors  []*AuthFactor `json:"auth_factors,omitempty"`
	Domain       string        `json:"domain,omitempty"`
	Fingerprint  *Fingerprint  `json:"fingerprint,omitempty"`
	HasMfa       bool          `json:"has_mfa,omitempty"`
	Issuer       string        `json:"issuer,omitempty"`
	Name         string        `json:"name,omitempty"`
	ProtocolName string        `json:"protocol_name,omitempty"`
	Scim         *Scim         `json:"scim,omitempty"`
	Sso          *Sso          `json:"sso,omitempty"`
	State        string        `json:"state,omitempty"`
	StateId      int           `json:"state_id,omitempty"`
	TenantUid    string        `json:"tenant_uid,omitempty"`
	Uid          string        `json:"uid,omitempty"`
	UrlString    string        `json:"url_string,omitempty"`
}
