// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// JA4+ Fingerprint - The JA4+ fingerprint object provides detailed fingerprint information about various aspects of network traffic which is both machine and human readable.
type Ja4Fingerprint struct {
	SectionA string `json:"section_a,omitempty"`
	SectionB string `json:"section_b,omitempty"`
	SectionC string `json:"section_c,omitempty"`
	SectionD string `json:"section_d,omitempty"`
	// The JA4+ fingerprint type as defined by <a href='https://blog.foxio.io/ja4+-network-fingerprinting target='_blank'>FoxIO</a>, normalized to the caption of 'type_id'. In the case of 'Other', it is defined by the event source.
	Type string `json:"type,omitempty"`
	// The identifier of the JA4+ fingerprint type.
	TypeId int `json:"type_id"`
	// The JA4+ fingerprint value.
	Value string `json:"value"`
}
