// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package objects

// Job - The Job object provides information about a scheduled job or task, including its name, command line, and state. It encompasses attributes that describe the properties and status of the scheduled job.
type Job struct {
	// The job command line.
	CmdLine string `json:"cmd_line,omitempty"`
	// The time when the job was created.
	CreatedTime int64 `json:"created_time,omitempty"`
	// The description of the job.
	Desc string `json:"desc,omitempty"`
	// The file that pertains to the job.
	File *File `json:"file,omitempty"`
	// The time when the job was last run.
	LastRunTime int64 `json:"last_run_time,omitempty"`
	// The name of the job.
	Name string `json:"name"`
	// The time when the job will next be run.
	NextRunTime int64 `json:"next_run_time,omitempty"`
	// The run state of the job.
	RunState string `json:"run_state,omitempty"`
	// The run state ID of the job.
	RunStateId int `json:"run_state_id,omitempty"`
	// The user that created the job.
	User *User `json:"user,omitempty"`
}
