// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type KbArticle struct {
	Object
	AvgTimespan    *Timespan `json:"avg_timespan,omitempty"`
	Bulletin       string    `json:"bulletin,omitempty"`
	Classification string    `json:"classification,omitempty"`
	CreatedTime    int64     `json:"created_time,omitempty"`
	InstallState   string    `json:"install_state,omitempty"`
	InstallStateId int       `json:"install_state_id,omitempty"`
	IsSuperseded   bool      `json:"is_superseded,omitempty"`
	Os             *Os       `json:"os,omitempty"`
	Product        *Product  `json:"product,omitempty"`
	Severity       string    `json:"severity,omitempty"`
	Size           int64     `json:"size,omitempty"`
	SrcUrl         string    `json:"src_url,omitempty"`
	Title          string    `json:"title,omitempty"`
	Uid            string    `json:"uid,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *KbArticle) Validate() error {
	// No required string fields to validate
	return nil
}
