// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// Kernel Extension - The Kernel Extension object describes a kernel driver that has been loaded or unloaded into the operating system (OS) kernel.
type KernelDriver struct {
	// The driver/extension file object.
	File *File `json:"file"`
}
