// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Kernel Resource - The Kernel Resource object provides information about a specific kernel resource, including its name and type. It describes essential attributes associated with a resource managed by the kernel of an operating system.
type Kernel struct {
	IsSystem bool `json:"is_system,omitempty"`
	// The name of the kernel resource.
	Name string `json:"name"`
	// The full path of the kernel resource.
	Path string `json:"path,omitempty"`
	SystemCall string `json:"system_call,omitempty"`
	// The type of the kernel resource.
	Type string `json:"type,omitempty"`
	// The type of the kernel resource.
	TypeId int `json:"type_id"`
}
