// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Kernel Extension - The Kernel Extension object describes a kernel driver that has been loaded or unloaded into the operating system (OS) kernel.
type KernelDriver struct {
	// The driver/extension file object.
	File *File `json:"file"`
}
