// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// Key:Value object - A generic object allowing to define a `{key:value}` pair.
type KeyValueObject struct {
	// The name of the key.
	Name string `json:"name"`
	// The value associated to the key.
	Value string `json:"value,omitempty"`
	// Optional, the values associated to the key. You can populate this attribute, when you have multiple values for the same key.
	Values []string `json:"values,omitempty"`
}
