// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Keyboard Information - The Keyboard Information object contains details and attributes related to a computer or device keyboard. It encompasses information that describes the characteristics, capabilities, and configuration of the keyboard.
type KeyboardInfo struct {
	FunctionKeys int `json:"function_keys,omitempty"`
	Ime string `json:"ime,omitempty"`
	KeyboardLayout string `json:"keyboard_layout,omitempty"`
	KeyboardSubtype int `json:"keyboard_subtype,omitempty"`
	KeyboardType string `json:"keyboard_type,omitempty"`
}
