// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// Keyboard Information - The Keyboard Information object contains details and attributes related to a computer or device keyboard. It encompasses information that describes the characteristics, capabilities, and configuration of the keyboard.
type KeyboardInfo struct {
	FunctionKeys int `json:"function_keys,omitempty"`
	Ime string `json:"ime,omitempty"`
	KeyboardLayout string `json:"keyboard_layout,omitempty"`
	KeyboardSubtype int `json:"keyboard_subtype,omitempty"`
	KeyboardType string `json:"keyboard_type,omitempty"`
}
