// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type KeyboardInfo struct {
	Object
	FunctionKeys    int    `json:"function_keys,omitempty"`
	Ime             string `json:"ime,omitempty"`
	KeyboardLayout  string `json:"keyboard_layout,omitempty"`
	KeyboardSubtype int    `json:"keyboard_subtype,omitempty"`
	KeyboardType    string `json:"keyboard_type,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *KeyboardInfo) Validate() error {
	// No required string fields to validate
	return nil
}
