// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Kill Chain Phase - The Kill Chain Phase object represents a single phase of a cyber attack, including the initial reconnaissance and planning stages up to the final objective of the attacker. It provides a detailed description of each phase and its associated activities within the broader context of a cyber attack. See <a target='_blank' href='https://www.lockheedmartin.com/en-us/capabilities/cyber/cyber-kill-chain.html'>Cyber Kill Chain®</a>.
type KillChainPhase struct {
	Phase string `json:"phase,omitempty"`
	PhaseId int `json:"phase_id"`
}
