// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type LoadBalancer struct {
	Classification      string                `json:"classification,omitempty"`
	Code                int                   `json:"code,omitempty"`
	DstEndpoint         *NetworkEndpoint      `json:"dst_endpoint,omitempty"`
	EndpointConnections []*EndpointConnection `json:"endpoint_connections,omitempty"`
	ErrorMessage        string                `json:"error_message,omitempty"`
	Ip                  string                `json:"ip,omitempty"`
	Message             string                `json:"message,omitempty"`
	Metrics             []*Metric             `json:"metrics,omitempty"`
	Name                string                `json:"name"`
	StatusDetail        string                `json:"status_detail,omitempty"`
	Uid                 string                `json:"uid"`
}
