// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package objects

// Load Balancer - The load balancer object describes the load balancer entity and contains additional information regarding the distribution of traffic across a network.
type LoadBalancer struct {
	// The request classification as defined by the load balancer.
	Classification string `json:"classification,omitempty"`
	// The numeric response status code detailing the connection from the load balancer to the destination target.
	Code int `json:"code,omitempty"`
	// The destination to which the load balancer is distributing traffic.
	DstEndpoint *NetworkEndpoint `json:"dst_endpoint,omitempty"`
	// An object detailing the load balancer connection attempts and responses.
	EndpointConnections []*EndpointConnection `json:"endpoint_connections,omitempty"`
	// The load balancer error message.
	ErrorMessage string `json:"error_message,omitempty"`
	// The IP address of the load balancer node that handled the client request. Note: the load balancer may have other IP addresses, and this is not an IP address of the target/distribution endpoint - see `dst_endpoint`.
	Ip string `json:"ip,omitempty"`
	// The load balancer message.
	Message string `json:"message,omitempty"`
	// General purpose metrics associated with the load balancer.
	Metrics []*Metric `json:"metrics,omitempty"`
	// The name of the load balancer.
	Name string `json:"name"`
	// The status detail contains additional status information about the load balancer distribution event.
	StatusDetail string `json:"status_detail,omitempty"`
	// The unique identifier for the load balancer.
	Uid string `json:"uid"`
}
