// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type Logger struct {
	Device          *Device  `json:"device,omitempty"`
	EventUid        string   `json:"event_uid,omitempty"`
	IsTruncated     bool     `json:"is_truncated,omitempty"`
	LogFormat       string   `json:"log_format,omitempty"`
	LogLevel        string   `json:"log_level,omitempty"`
	LogName         string   `json:"log_name,omitempty"`
	LogProvider     string   `json:"log_provider,omitempty"`
	LogVersion      string   `json:"log_version,omitempty"`
	LoggedTime      int64    `json:"logged_time,omitempty"`
	Name            string   `json:"name,omitempty"`
	Product         *Product `json:"product,omitempty"`
	TransmitTime    int64    `json:"transmit_time,omitempty"`
	Uid             string   `json:"uid,omitempty"`
	UntruncatedSize int      `json:"untruncated_size,omitempty"`
	Version         string   `json:"version,omitempty"`
}
