// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// Logger - The Logger object represents the device and product where events are stored with times for receipt and transmission.  This may be at the source device where the event occurred, a remote scanning device, intermediate hops, or the ultimate destination.
type Logger struct {
	// The device where the events are logged.
	Device *Device `json:"device,omitempty"`
	// The unique identifier of the event assigned by the logger.
	EventUid string `json:"event_uid,omitempty"`
	// Indicates whether the OCSF event data has been truncated due to size limitations. When `true`, some event data may have been omitted to fit within system constraints.
	IsTruncated bool `json:"is_truncated,omitempty"`
	LogLevel string `json:"log_level,omitempty"`
	LogName string `json:"log_name,omitempty"`
	LogProvider string `json:"log_provider,omitempty"`
	LogVersion string `json:"log_version,omitempty"`
	LoggedTime int64 `json:"logged_time,omitempty"`
	// The name of the logging product instance.
	Name string `json:"name,omitempty"`
	// The product logging the event.  This may be the event source product, a management server product, a scanning product, a SIEM, etc.
	Product *Product `json:"product,omitempty"`
	// The time when the event was transmitted from the logging device to it's next destination.
	TransmitTime int64 `json:"transmit_time,omitempty"`
	// The unique identifier of the logging product instance.
	Uid string `json:"uid,omitempty"`
	// The original size of the OCSF event data in kilobytes before any truncation occurred. This field is typically populated when `is_truncated` is `true` to indicate the full size of the original event.
	UntruncatedSize int `json:"untruncated_size,omitempty"`
	// The version of the logging product.
	Version string `json:"version,omitempty"`
}
