// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// Long String - This object is a used to capture strings which may be truncated by a security product due to their length.
type LongString struct {
	// Indicates that `value` has been truncated. May be omitted if truncation has not occurred.
	IsTruncated bool `json:"is_truncated,omitempty"`
	// The size in bytes of the string represented by `value` before truncation. Should be omitted if truncation has not occurred.
	UntruncatedSize int `json:"untruncated_size,omitempty"`
	// The string value, truncated if `is_truncated` is `true`.
	Value string `json:"value"`
}
