// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package objects

// Metadata - The Metadata object describes the metadata associated with the event.
type Metadata struct {
	CorrelationUid string `json:"correlation_uid,omitempty"`
	Debug []string `json:"debug,omitempty"`
	EventCode string `json:"event_code,omitempty"`
	Extension *Extension `json:"extension,omitempty"`
	Extensions []*Extension `json:"extensions,omitempty"`
	// Indicates whether the OCSF event data has been truncated due to size limitations. When `true`, some event data may have been omitted to fit within system constraints.
	IsTruncated bool `json:"is_truncated,omitempty"`
	// The list of labels attached to the event. For example: `["sample", "dev"]`
	Labels []string `json:"labels,omitempty"`
	LogLevel string `json:"log_level,omitempty"`
	LogName string `json:"log_name,omitempty"`
	LogProvider string `json:"log_provider,omitempty"`
	LogVersion string `json:"log_version,omitempty"`
	LoggedTime int64 `json:"logged_time,omitempty"`
	Loggers []*Logger `json:"loggers,omitempty"`
	// The time when the event was last modified or enriched.
	ModifiedTime int64 `json:"modified_time,omitempty"`
	OriginalTime string `json:"original_time,omitempty"`
	ProcessedTime int64 `json:"processed_time,omitempty"`
	Product *Product `json:"product"`
	Profiles []string `json:"profiles,omitempty"`
	// The entity from which the event or finding was first reported.
	Reporter *Reporter `json:"reporter,omitempty"`
	Sequence int `json:"sequence,omitempty"`
	// The list of tags; `{key:value}` pairs associated to the event.
	Tags []*KeyValueObject `json:"tags,omitempty"`
	TenantUid string `json:"tenant_uid,omitempty"`
	TransformationInfoList []*TransformationInfo `json:"transformation_info_list,omitempty"`
	// The logging system-assigned unique identifier of an event instance.
	Uid string `json:"uid,omitempty"`
	// The original size of the OCSF event data in kilobytes before any truncation occurred. This field is typically populated when `is_truncated` is `true` to indicate the full size of the original event.
	UntruncatedSize int `json:"untruncated_size,omitempty"`
	// The version of the OCSF schema, using Semantic Versioning Specification (<a target='_blank' href='https://semver.org'>SemVer</a>). For example: `1.0.0.` Event consumers use the version to determine the available event attributes.
	Version string `json:"version"`
}
