// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type Metadata struct {
	Object
	CorrelationUid         string                `json:"correlation_uid,omitempty"`
	Debug                  []string              `json:"debug,omitempty"`
	EventCode              string                `json:"event_code,omitempty"`
	Extension              *Extension            `json:"extension,omitempty"`
	Extensions             []*Extension          `json:"extensions,omitempty"`
	IsTruncated            bool                  `json:"is_truncated,omitempty"`
	Labels                 []string              `json:"labels,omitempty"`
	LogFormat              string                `json:"log_format,omitempty"`
	LogLevel               string                `json:"log_level,omitempty"`
	LogName                string                `json:"log_name,omitempty"`
	LogProvider            string                `json:"log_provider,omitempty"`
	LogSource              string                `json:"log_source,omitempty"`
	LogVersion             string                `json:"log_version,omitempty"`
	LoggedTime             int64                 `json:"logged_time,omitempty"`
	Loggers                []*Logger             `json:"loggers,omitempty"`
	ModifiedTime           int64                 `json:"modified_time,omitempty"`
	OriginalEventUid       string                `json:"original_event_uid,omitempty"`
	OriginalTime           string                `json:"original_time,omitempty"`
	ProcessedTime          int64                 `json:"processed_time,omitempty"`
	Product                *Product              `json:"product"`
	Profiles               []string              `json:"profiles,omitempty"`
	Reporter               *Reporter             `json:"reporter,omitempty"`
	Sequence               int                   `json:"sequence,omitempty"`
	Source                 string                `json:"source,omitempty"`
	Tags                   []*KeyValueObject     `json:"tags,omitempty"`
	TenantUid              string                `json:"tenant_uid,omitempty"`
	TransformationInfoList []*TransformationInfo `json:"transformation_info_list,omitempty"`
	TransmitTime           int64                 `json:"transmit_time,omitempty"`
	Type                   string                `json:"type,omitempty"`
	Uid                    string                `json:"uid,omitempty"`
	UntruncatedSize        int                   `json:"untruncated_size,omitempty"`
	Version                string                `json:"version"`
}
