// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Metric - The Metric object defines a simple name/value pair entity for a metric.
type Metric struct {
	// The name of the metric.
	Name string `json:"name"`
	// The value of the metric.
	Value string `json:"value"`
}
