// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type Module struct {
	Object
	BaseAddress        string              `json:"base_address,omitempty"`
	File               *File               `json:"file,omitempty"`
	FunctionInvocation *FunctionInvocation `json:"function_invocation,omitempty"`
	FunctionName       string              `json:"function_name,omitempty"`
	LoadType           string              `json:"load_type,omitempty"`
	LoadTypeId         int                 `json:"load_type_id,omitempty"`
	StartAddress       string              `json:"start_address,omitempty"`
	Type               string              `json:"type,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *Module) Validate() error {
	// No required string fields to validate
	return nil
}
