// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type NetworkTraffic struct {
	Object
	Bytes       int64 `json:"bytes,omitempty"`
	BytesIn     int64 `json:"bytes_in,omitempty"`
	BytesMissed int64 `json:"bytes_missed,omitempty"`
	BytesOut    int64 `json:"bytes_out,omitempty"`
	Chunks      int64 `json:"chunks,omitempty"`
	ChunksIn    int64 `json:"chunks_in,omitempty"`
	ChunksOut   int64 `json:"chunks_out,omitempty"`
	Packets     int64 `json:"packets,omitempty"`
	PacketsIn   int64 `json:"packets_in,omitempty"`
	PacketsOut  int64 `json:"packets_out,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *NetworkTraffic) Validate() error {
	// No required string fields to validate
	return nil
}
