// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// Network Connection Information - The Network Connection Information object describes characteristics of an OSI Transport Layer communication, including TCP and UDP.
type NetworkConnectionInfo struct {
	Boundary string `json:"boundary,omitempty"`
	BoundaryId int `json:"boundary_id,omitempty"`
	CommunityUid string `json:"community_uid,omitempty"`
	Direction string `json:"direction,omitempty"`
	DirectionId int `json:"direction_id"`
	FlagHistory string `json:"flag_history,omitempty"`
	// The IP protocol name in lowercase, as defined by the Internet Assigned Numbers Authority (IANA). For example: `tcp` or `udp`.
	ProtocolName string `json:"protocol_name,omitempty"`
	ProtocolNum int `json:"protocol_num,omitempty"`
	// The Internet Protocol version.
	ProtocolVer string `json:"protocol_ver,omitempty"`
	// The Internet Protocol version identifier.
	ProtocolVerId int `json:"protocol_ver_id,omitempty"`
	Session *Session `json:"session,omitempty"`
	TcpFlags int `json:"tcp_flags,omitempty"`
	// The unique identifier of the connection.
	Uid string `json:"uid,omitempty"`
}
