// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type NetworkEndpoint struct {
	Endpoint
	AutonomousSystem *AutonomousSystem `json:"autonomous_system,omitempty"`
	IntermediateIps  []string          `json:"intermediate_ips,omitempty"`
	Isp              string            `json:"isp,omitempty"`
	IspOrg           string            `json:"isp_org,omitempty"`
	NetworkScope     string            `json:"network_scope,omitempty"`
	NetworkScopeId   int               `json:"network_scope_id,omitempty"`
	Port             string            `json:"port,omitempty"`
	ProxyEndpoint    *NetworkProxy     `json:"proxy_endpoint,omitempty"`
	SvcName          string            `json:"svc_name,omitempty"`
	Type             string            `json:"type"`
	TypeId           int               `json:"type_id"`
	Uid              string            `json:"uid"`
}
