// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type NetworkConnectionInfo struct {
	Boundary      string   `json:"boundary,omitempty"`
	BoundaryId    int      `json:"boundary_id,omitempty"`
	CommunityUid  string   `json:"community_uid,omitempty"`
	Direction     string   `json:"direction,omitempty"`
	DirectionId   int      `json:"direction_id"`
	FlagHistory   string   `json:"flag_history,omitempty"`
	ProtocolName  string   `json:"protocol_name,omitempty"`
	ProtocolNum   int      `json:"protocol_num,omitempty"`
	ProtocolVer   string   `json:"protocol_ver,omitempty"`
	ProtocolVerId int      `json:"protocol_ver_id,omitempty"`
	Session       *Session `json:"session,omitempty"`
	TcpFlags      int      `json:"tcp_flags,omitempty"`
	Uid           string   `json:"uid,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *NetworkConnectionInfo) Validate() error {
	// No required string fields to validate
	return nil
}
