// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Network Endpoint - The Network Endpoint object describes characteristics of a network endpoint. These can be a source or destination of a network connection.
type NetworkEndpoint struct {
	AutonomousSystem *AutonomousSystem `json:"autonomous_system,omitempty"`
	IntermediateIps []string `json:"intermediate_ips,omitempty"`
	Isp string `json:"isp,omitempty"`
	IspOrg string `json:"isp_org,omitempty"`
	NetworkScope string `json:"network_scope,omitempty"`
	NetworkScopeId int `json:"network_scope_id,omitempty"`
	// The port used for communication within the network connection.
	Port string `json:"port,omitempty"`
	// The network proxy information pertaining to a specific endpoint. This can be used to describe information pertaining to network address translation (NAT).
	ProxyEndpoint *NetworkProxy `json:"proxy_endpoint,omitempty"`
	SvcName string `json:"svc_name,omitempty"`
	// The network endpoint type. For example: `unknown`, `server`, `desktop`, `laptop`, `tablet`, `mobile`, `virtual`, `browser`, or `other`.
	Type string `json:"type"`
	// The network endpoint type ID.
	TypeId int `json:"type_id"`
	Uid string `json:"uid"`
}
