// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Network Traffic - The Network Traffic object describes characteristics of network traffic. Network traffic refers to data moving across a network at a given point of time.
type NetworkTraffic struct {
	Bytes int64 `json:"bytes,omitempty"`
	BytesIn int64 `json:"bytes_in,omitempty"`
	BytesMissed int64 `json:"bytes_missed,omitempty"`
	BytesOut int64 `json:"bytes_out,omitempty"`
	// The total number of chunks (in and out).
	Chunks int64 `json:"chunks,omitempty"`
	// The number of chunks sent from the destination to the source.
	ChunksIn int64 `json:"chunks_in,omitempty"`
	// The number of chunks sent from the source to the destination.
	ChunksOut int64 `json:"chunks_out,omitempty"`
	Packets int64 `json:"packets,omitempty"`
	PacketsIn int64 `json:"packets_in,omitempty"`
	PacketsOut int64 `json:"packets_out,omitempty"`
}
