// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Network Proxy Endpoint - The network proxy endpoint object describes a proxy server, which acts as an intermediary between a client requesting a resource and the server providing that resource.
type NetworkProxy struct {
}
