// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

import "fmt"

type Node struct {
	Object
	Data string `json:"data,omitempty"`
	Desc string `json:"desc,omitempty"`
	Name string `json:"name,omitempty"`
	Type string `json:"type,omitempty"`
	Uid  string `json:"uid"`
}

// Validate checks that all required fields are properly set
func (o *Node) Validate() error {
	if o.Uid == "" {
		return fmt.Errorf("required field uid is empty")
	}
	return nil
}
