// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Object - An unordered collection of attributes. It defines a set of attributes available in all objects. It can be also used as a generic object to log objects that are not otherwise defined by the schema.
type Object struct {
}
