// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// OSINT - The OSINT (Open Source Intelligence) object contains details related to an indicator such as the indicator itself, related indicators, geolocation, registrar information, subdomains, analyst commentary, and other contextual information. This information can be used to further enrich a detection or finding by providing decisioning support to other analysts and engineers.
type Osint struct {
	// Any pertinent DNS answers information related to an indicator or OSINT analysis.
	Answers []*DnsAnswer `json:"answers,omitempty"`
	// MITRE ATT&CK Tactics, Techniques, and/or Procedures (TTPs) pertinent to an indicator or OSINT analysis.
	Attacks []*Attack `json:"attacks,omitempty"`
	// Any pertinent autonomous system information related to an indicator or OSINT analysis.
	AutonomousSystem *AutonomousSystem `json:"autonomous_system,omitempty"`
	Campaign *Campaign `json:"campaign,omitempty"`
	// Categorizes the threat indicator based on its functional or operational role.
	Category string `json:"category,omitempty"`
	// Analyst commentary or source commentary about an indicator or OSINT analysis.
	Comment string `json:"comment,omitempty"`
	// The confidence of an indicator being malicious and/or pertinent, normalized to the caption of the confidence_id value. In the case of 'Other', it is defined by the event source or analyst.
	Confidence string `json:"confidence,omitempty"`
	// The normalized confidence refers to the accuracy of collected information related to the OSINT or how pertinent an indicator or analysis is to a specific event or finding. A low confidence means that the information collected or analysis conducted lacked detail or is not accurate enough to qualify an indicator as fully malicious.
	ConfidenceId int `json:"confidence_id,omitempty"`
	// The timestamp when the indicator was initially created or identified.
	CreatedTime int64 `json:"created_time,omitempty"`
	// The identifier of the user, system, or organization that contributed the indicator.
	Creator *User `json:"creator,omitempty"`
	// A detailed explanation of the indicator, including its context, purpose, and relevance.
	Desc string `json:"desc,omitempty"`
	// The specific detection pattern or signature associated with the indicator.
	DetectionPattern string `json:"detection_pattern,omitempty"`
	DetectionPatternType string `json:"detection_pattern_type,omitempty"`
	DetectionPatternTypeId int `json:"detection_pattern_type_id,omitempty"`
	// Any email information pertinent to an indicator or OSINT analysis.
	Email *Email `json:"email,omitempty"`
	// Any email authentication information pertinent to an indicator or OSINT analysis.
	EmailAuth *EmailAuth `json:"email_auth,omitempty"`
	// The expiration date of the indicator, after which it is no longer considered reliable.
	ExpirationTime int64 `json:"expiration_time,omitempty"`
	ExternalUid string `json:"external_uid,omitempty"`
	// Any pertinent file information related to an indicator or OSINT analysis.
	File *File `json:"file,omitempty"`
	IntrusionSets []string `json:"intrusion_sets,omitempty"`
	// Lockheed Martin Kill Chain Phases pertinent to an indicator or OSINT analysis.
	KillChain []*KillChainPhase `json:"kill_chain,omitempty"`
	// Tags or keywords associated with the indicator to enhance searchability.
	Labels []string `json:"labels,omitempty"`
	// Any pertinent geolocation information related to an indicator or OSINT analysis.
	Location *Location `json:"location,omitempty"`
	Malware []*Malware `json:"malware,omitempty"`
	// The timestamp of the last modification or update to the indicator.
	ModifiedTime int64 `json:"modified_time,omitempty"`
	// The `name` is a pointer/reference to an attribute within the OCSF event data. For example: file.name.
	Name string `json:"name,omitempty"`
	// Provides a reference to an external source of information related to the CTI being represented. This may include a URL, a document, or some other type of reference that provides additional context or information about the CTI.
	References []string `json:"references,omitempty"`
	// Any analytics related to an indicator or OSINT analysis.
	RelatedAnalytics []*Analytic `json:"related_analytics,omitempty"`
	// Related reputational analysis from third-party engines and analysts for a given indicator or OSINT analysis.
	Reputation *Reputation `json:"reputation,omitempty"`
	// A numerical representation of the threat indicator’s risk level.
	RiskScore int `json:"risk_score,omitempty"`
	// Any pertinent script information related to an indicator or OSINT analysis.
	Script *Script `json:"script,omitempty"`
	// Represents the severity level of the threat indicator, typically reflecting its potential impact or damage.
	Severity string `json:"severity,omitempty"`
	// The normalized severity level of the threat indicator, typically reflecting its potential impact or damage.
	SeverityId int `json:"severity_id,omitempty"`
	// Any digital signatures or hashes related to an indicator or OSINT analysis.
	Signatures []*DigitalSignature `json:"signatures,omitempty"`
	// The source URL of an indicator or OSINT analysis, e.g., a URL back to a TIP, report, or otherwise.
	SrcUrl string `json:"src_url,omitempty"`
	// Any pertinent subdomain information - such as those generated by a Domain Generation Algorithm - related to an indicator or OSINT analysis.
	Subdomains []string `json:"subdomains,omitempty"`
	// A CIDR or network block related to an indicator or OSINT analysis.
	Subnet string `json:"subnet,omitempty"`
	ThreatActor *ThreatActor `json:"threat_actor,omitempty"`
	// The <a target='_blank' href='https://www.first.org/tlp/'>Traffic Light Protocol</a> was created to facilitate greater sharing of potentially sensitive information and more effective collaboration. TLP provides a simple and intuitive schema for indicating with whom potentially sensitive information can be shared.
	Tlp string `json:"tlp,omitempty"`
	// The OSINT indicator type.
	Type string `json:"type,omitempty"`
	// The OSINT indicator type ID.
	TypeId int `json:"type_id"`
	// The unique identifier for the OSINT object.
	Uid string `json:"uid,omitempty"`
	// The timestamp indicating when the associated indicator or intelligence was added to the system or repository.
	UploadedTime int64 `json:"uploaded_time,omitempty"`
	// The actual indicator value in scope, e.g., a SHA-256 hash hexdigest or a domain name.
	Value string `json:"value"`
	// The vendor name of a tool which generates intelligence or provides indicators.
	VendorName string `json:"vendor_name,omitempty"`
	// Any vulnerabilities related to an indicator or OSINT analysis.
	Vulnerabilities []*Vulnerability `json:"vulnerabilities,omitempty"`
	// Any pertinent WHOIS information related to an indicator or OSINT analysis.
	Whois *Whois `json:"whois,omitempty"`
}
