// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type PeripheralDevice struct {
	Class        string   `json:"class,omitempty"`
	Model        string   `json:"model,omitempty"`
	Name         string   `json:"name"`
	SerialNumber string   `json:"serial_number,omitempty"`
	Type         string   `json:"type,omitempty"`
	TypeId       int      `json:"type_id,omitempty"`
	Uid          string   `json:"uid,omitempty"`
	VendorIdList []string `json:"vendor_id_list,omitempty"`
	VendorName   string   `json:"vendor_name,omitempty"`
}
