// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Peripheral Device - The peripheral device object describes the properties of external, connectable, and detachable hardware.
type PeripheralDevice struct {
	// The class of the peripheral device.
	Class string `json:"class,omitempty"`
	// The peripheral device model.
	Model string `json:"model,omitempty"`
	// The name of the peripheral device.
	Name string `json:"name"`
	// The peripheral device serial number.
	SerialNumber string `json:"serial_number,omitempty"`
	// The Peripheral Device type, normalized to the caption of the `type_id` value. In the case of 'Other', it is defined by the source.
	Type string `json:"type,omitempty"`
	// The normalized peripheral device type ID.
	TypeId int `json:"type_id,omitempty"`
	// The unique identifier of the peripheral device.
	Uid string `json:"uid,omitempty"`
	// The list of vendor IDs for the peripheral device.
	VendorIdList []string `json:"vendor_id_list,omitempty"`
	// The primary vendor name for the peripheral device.
	VendorName string `json:"vendor_name,omitempty"`
}
