// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type Policy struct {
	Data      string `json:"data,omitempty"`
	Desc      string `json:"desc,omitempty"`
	Group     *Group `json:"group,omitempty"`
	IsApplied bool   `json:"is_applied,omitempty"`
	Name      string `json:"name"`
	Type      string `json:"type,omitempty"`
	Uid       string `json:"uid"`
	Version   string `json:"version,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *Policy) Validate() error {
	// No required string fields to validate
	return nil
}
