// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package objects

// Port Information - The Port Information object describes a port and its associated protocol details.
type PortInfo struct {
	// The port number. For example: `80`, `443`, `22`.
	Port string `json:"port"`
	// The IP protocol name in lowercase, as defined by the Internet Assigned Numbers Authority (IANA). For example: `tcp` or `udp`.
	ProtocolName string `json:"protocol_name,omitempty"`
	ProtocolNum int `json:"protocol_num,omitempty"`
}
