// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Port Information - The Port Information object describes a port and its associated protocol details.
type PortInfo struct {
	// The port number. For example: `80`, `443`, `22`.
	Port string `json:"port"`
	// The IP protocol name in lowercase, as defined by the Internet Assigned Numbers Authority (IANA). For example: `tcp` or `udp`.
	ProtocolName string `json:"protocol_name,omitempty"`
	ProtocolNum int `json:"protocol_num,omitempty"`
}
