// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type PortInfo struct {
	Port         int    `json:"port"`
	ProtocolName string `json:"protocol_name,omitempty"`
	ProtocolNum  int    `json:"protocol_num,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *PortInfo) Validate() error {
	// No required string fields to validate
	return nil
}
