// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Process Entity - The Process Entity object provides critical fields for referencing a process.
type ProcessEntity struct {
	CmdLine string `json:"cmd_line,omitempty"`
	Cpid string `json:"cpid,omitempty"`
	// The time when the process was created/started.
	CreatedTime int64 `json:"created_time,omitempty"`
	// The friendly name of the process, for example: `Notepad++`.
	Name string `json:"name"`
	// The process file path.
	Path string `json:"path,omitempty"`
	Pid int `json:"pid,omitempty"`
	// A unique identifier for this process assigned by the producer (tool).  Facilitates correlation of a process event with other events for that process.
	Uid string `json:"uid"`
}
