// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

import "fmt"

type ProcessEntity struct {
	CmdLine     string `json:"cmd_line,omitempty"`
	Cpid        string `json:"cpid,omitempty"`
	CreatedTime int64  `json:"created_time,omitempty"`
	Name        string `json:"name"`
	Path        string `json:"path,omitempty"`
	Pid         int    `json:"pid,omitempty"`
	Uid         string `json:"uid"`
}

// Validate checks that all required fields are properly set
func (o *ProcessEntity) Validate() error {
	if o.Name == "" {
		return fmt.Errorf("required field name is empty")
	}
	if o.Uid == "" {
		return fmt.Errorf("required field uid is empty")
	}
	return nil
}
