// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

import "fmt"

type Product struct {
	CpeName    string   `json:"cpe_name,omitempty"`
	Feature    *Feature `json:"feature,omitempty"`
	Lang       string   `json:"lang,omitempty"`
	Name       string   `json:"name"`
	Path       string   `json:"path,omitempty"`
	Uid        string   `json:"uid"`
	UrlString  string   `json:"url_string,omitempty"`
	VendorName string   `json:"vendor_name,omitempty"`
	Version    string   `json:"version,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *Product) Validate() error {
	if o.Name == "" {
		return fmt.Errorf("required field name is empty")
	}
	if o.Uid == "" {
		return fmt.Errorf("required field uid is empty")
	}
	return nil
}
