// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type ProgrammaticCredential struct {
	Object
	LastUsedTime int64  `json:"last_used_time,omitempty"`
	Type         string `json:"type,omitempty"`
	Uid          string `json:"uid"`
}
