// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// Query Information - The query info object holds information related to data access within a datastore. To access, manipulate, delete, or retrieve data from a datastore, a query must be written using a specific syntax.
type QueryInfo struct {
	// The size of the data returned from the query.
	Bytes int64 `json:"bytes,omitempty"`
	// The data returned from the query execution.
	Data string `json:"data,omitempty"`
	// The query name for a saved or scheduled query.
	Name string `json:"name"`
	// A string representing the query code being run. For example: `SELECT * FROM my_table`
	QueryString string `json:"query_string"`
	// The time when the query was run.
	QueryTime int64 `json:"query_time,omitempty"`
	// The unique identifier of the query.
	Uid string `json:"uid"`
}
