// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

import "fmt"

type QueryInfo struct {
	Bytes       int64  `json:"bytes,omitempty"`
	Data        string `json:"data,omitempty"`
	Name        string `json:"name"`
	QueryString string `json:"query_string"`
	QueryTime   int64  `json:"query_time,omitempty"`
	Uid         string `json:"uid"`
}

// Validate checks that all required fields are properly set
func (o *QueryInfo) Validate() error {
	if o.Name == "" {
		return fmt.Errorf("required field name is empty")
	}
	if o.QueryString == "" {
		return fmt.Errorf("required field query_string is empty")
	}
	if o.Uid == "" {
		return fmt.Errorf("required field uid is empty")
	}
	return nil
}
