// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type RelatedEvent struct {
	Object
	Attacks       []*Attack         `json:"attacks,omitempty"`
	Count         int               `json:"count,omitempty"`
	CreatedTime   int64             `json:"created_time,omitempty"`
	Desc          string            `json:"desc,omitempty"`
	FirstSeenTime int64             `json:"first_seen_time,omitempty"`
	KillChain     []*KillChainPhase `json:"kill_chain,omitempty"`
	LastSeenTime  int64             `json:"last_seen_time,omitempty"`
	ModifiedTime  int64             `json:"modified_time,omitempty"`
	Observables   []*Observable     `json:"observables,omitempty"`
	Product       *Product          `json:"product,omitempty"`
	ProductUid    string            `json:"product_uid,omitempty"`
	Severity      string            `json:"severity,omitempty"`
	SeverityId    int               `json:"severity_id,omitempty"`
	Status        string            `json:"status,omitempty"`
	Tags          []*KeyValueObject `json:"tags,omitempty"`
	Title         string            `json:"title,omitempty"`
	Traits        []*Trait          `json:"traits,omitempty"`
	Type          string            `json:"type,omitempty"`
	TypeName      string            `json:"type_name,omitempty"`
	TypeUid       int64             `json:"type_uid,omitempty"`
	Uid           string            `json:"uid"`
}
