// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package objects

// Remediation - The Remediation object describes the recommended remediation steps to address identified issue(s).
type Remediation struct {
	// An array of Center for Internet Security (CIS) Controls that can be optionally mapped to provide additional remediation details.
	CisControls []*CisControl `json:"cis_controls,omitempty"`
	// The description of the remediation strategy.
	Desc string `json:"desc"`
	KbArticleList []*KbArticle `json:"kb_article_list,omitempty"`
	KbArticles []string `json:"kb_articles,omitempty"`
	// A list of supporting URL/s, references that help describe the remediation strategy.
	References []string `json:"references,omitempty"`
}
