// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Reporter - The entity from which an event or finding was reported.
type Reporter struct {
	// The hostname of the entity from which the event or finding was reported.
	Hostname string `json:"hostname,omitempty"`
	// The IP address of the entity from which the event or finding was reported.
	Ip string `json:"ip,omitempty"`
	// The name of the entity from which the event or finding was reported.
	Name string `json:"name,omitempty"`
	// The organization properties of the entity that reported the event or finding.
	Org *Organization `json:"org,omitempty"`
	// The unique identifier of the entity from which the event or finding was reported.
	Uid string `json:"uid,omitempty"`
}
