// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type Reporter struct {
	Hostname string        `json:"hostname,omitempty"`
	Ip       string        `json:"ip,omitempty"`
	Name     string        `json:"name,omitempty"`
	Org      *Organization `json:"org,omitempty"`
	Uid      string        `json:"uid,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *Reporter) Validate() error {
	// No required string fields to validate
	return nil
}
