// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Reputation - The Reputation object describes the reputation/risk score of an entity (e.g. device, user, domain).
type Reputation struct {
	// The reputation score as reported by the event source.
	BaseScore float64 `json:"base_score"`
	// The provider of the reputation information.
	Provider string `json:"provider,omitempty"`
	Score string `json:"score,omitempty"`
	ScoreId int `json:"score_id"`
}
