// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Request Elements - The Request Elements object describes characteristics of an API request.
type Request struct {
	Containers []*Container `json:"containers,omitempty"`
	// The additional data that is associated with the api request.
	Data string `json:"data,omitempty"`
	// The communication flags that are associated with the api request.
	Flags []string `json:"flags,omitempty"`
	// The unique request identifier.
	Uid string `json:"uid"`
}
