// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

import "fmt"

type Request struct {
	Object
	Containers []*Container `json:"containers,omitempty"`
	Data       string       `json:"data,omitempty"`
	Flags      []string     `json:"flags,omitempty"`
	Uid        string       `json:"uid"`
}

// Validate checks that all required fields are properly set
func (o *Request) Validate() error {
	if o.Uid == "" {
		return fmt.Errorf("required field uid is empty")
	}
	return nil
}
