// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// Request Elements - The Request Elements object describes characteristics of an API request.
type Request struct {
	Containers []*Container `json:"containers,omitempty"`
	// The additional data that is associated with the api request.
	Data string `json:"data,omitempty"`
	// The communication flags that are associated with the api request.
	Flags []string `json:"flags,omitempty"`
	// The unique request identifier.
	Uid string `json:"uid"`
}
