// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package objects

// Resource Details - The Resource Details object describes details about resources that were affected by the activity/event.
type ResourceDetails struct {
	AgentList []*Agent `json:"agent_list,omitempty"`
	CloudPartition string `json:"cloud_partition,omitempty"`
	// The criticality of the resource as defined by the event source.
	Criticality string `json:"criticality,omitempty"`
	// The name of the related resource group.
	Group *Group `json:"group,omitempty"`
	// The fully qualified name of the resource.
	Hostname string `json:"hostname,omitempty"`
	// The IP address of the resource, in either IPv4 or IPv6 format.
	Ip string `json:"ip,omitempty"`
	IsBackedUp bool `json:"is_backed_up,omitempty"`
	Name string `json:"name,omitempty"`
	// The namespace is useful when similar entities exist that you need to keep separate.
	Namespace string `json:"namespace,omitempty"`
	// The identity of the service or user account that owns the resource.
	Owner *User `json:"owner,omitempty"`
	// The cloud region of the resource.
	Region string `json:"region,omitempty"`
	// A graph representation showing how this resource relates to and interacts with other entities in the environment. This can include parent/child relationships, dependencies, or other connections.
	ResourceRelationship *Graph `json:"resource_relationship,omitempty"`
	// The role of the resource in the context of the event or finding, normalized to the caption of the role_id value. In the case of 'Other', it is defined by the event source.
	Role string `json:"role,omitempty"`
	// The normalized identifier of the resource's role in the context of the event or finding.
	RoleId int `json:"role_id,omitempty"`
	// The version of the resource. For example `1.2.3`.
	Version string `json:"version,omitempty"`
	// The specific availability zone within a cloud region where the resource is located.
	Zone string `json:"zone,omitempty"`
}
