// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type ResourceDetails struct {
	AgentList            []*Agent `json:"agent_list,omitempty"`
	CloudPartition       string   `json:"cloud_partition,omitempty"`
	Criticality          string   `json:"criticality,omitempty"`
	Group                *Group   `json:"group,omitempty"`
	Hostname             string   `json:"hostname,omitempty"`
	Ip                   string   `json:"ip,omitempty"`
	IsBackedUp           bool     `json:"is_backed_up,omitempty"`
	Name                 string   `json:"name,omitempty"`
	Namespace            string   `json:"namespace,omitempty"`
	Owner                *User    `json:"owner,omitempty"`
	Region               string   `json:"region,omitempty"`
	ResourceRelationship *Graph   `json:"resource_relationship,omitempty"`
	Role                 string   `json:"role,omitempty"`
	RoleId               int      `json:"role_id,omitempty"`
	Version              string   `json:"version,omitempty"`
	Zone                 string   `json:"zone,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *ResourceDetails) Validate() error {
	// No required string fields to validate
	return nil
}
