// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type Response struct {
	Code         int          `json:"code,omitempty"`
	Containers   []*Container `json:"containers,omitempty"`
	Data         string       `json:"data,omitempty"`
	Error        string       `json:"error,omitempty"`
	ErrorMessage string       `json:"error_message,omitempty"`
	Flags        []string     `json:"flags,omitempty"`
	Message      string       `json:"message,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *Response) Validate() error {
	// No required string fields to validate
	return nil
}
