// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// RPC Interface - The RPC Interface represents the remote procedure call interface used in the DCE/RPC session.
type RpcInterface struct {
	AckReason int `json:"ack_reason,omitempty"`
	AckResult int `json:"ack_result,omitempty"`
	// The unique identifier of the particular remote procedure or service.
	Uuid string `json:"uuid"`
	// The version of the DCE/RPC protocol being used in the session.
	Version string `json:"version"`
}
