// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

import "fmt"

type RpcInterface struct {
	AckReason int    `json:"ack_reason,omitempty"`
	AckResult int    `json:"ack_result,omitempty"`
	Uuid      string `json:"uuid"`
	Version   string `json:"version"`
}

// Validate checks that all required fields are properly set
func (o *RpcInterface) Validate() error {
	if o.Uuid == "" {
		return fmt.Errorf("required field uuid is empty")
	}
	if o.Version == "" {
		return fmt.Errorf("required field version is empty")
	}
	return nil
}
