// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Subject Alternative Name - The Subject Alternative name (SAN) object describes a SAN secured by a digital certificate
type San struct {
	// Name of SAN (e.g. The actual IP Address or domain.)
	Name string `json:"name"`
	// Type descriptor of SAN (e.g. IP Address/domain/etc.)
	Type string `json:"type"`
}
