// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package objects

// Software Bill of Materials - The Software Bill of Materials object describes characteristics of a generated SBOM.
type Sbom struct {
	// The time when the SBOM was created.
	CreatedTime int64 `json:"created_time,omitempty"`
	// The software package or library that is being discovered or inventoried by an SBOM.
	Package *Package `json:"package"`
	// Details about the upstream product that generated the SBOM e.g. `cdxgen` or `Syft`.
	Product *Product `json:"product,omitempty"`
	SoftwareComponents []*SoftwareComponent `json:"software_components"`
	// The type of SBOM, normalized to the caption of the `type_id` value. In the case of 'Other', it is defined by the source.
	Type string `json:"type,omitempty"`
	// The type of SBOM.
	TypeId int `json:"type_id,omitempty"`
	// A unique identifier for the SBOM or the SBOM generation by a source tool, such as the SPDX `metadata.component.bom-ref`.
	Uid string `json:"uid,omitempty"`
	// The specification (spec) version of the particular SBOM, e.g., `1.6`.
	Version string `json:"version,omitempty"`
}
