// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// Scan - The Scan object describes characteristics of a proactive scan.
type Scan struct {
	// The administrator-supplied or application-generated name of the scan. For example: "Home office weekly user database scan", "Scan folders for viruses", "Full system virus scan"
	Name string `json:"name"`
	// The type of scan.
	Type string `json:"type,omitempty"`
	// The type id of the scan.
	TypeId int `json:"type_id"`
	// The application-defined unique identifier assigned to an instance of a scan.
	Uid string `json:"uid"`
}
