// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// Security State - The Security State object describes the security related state of a managed entity.
type SecurityState struct {
	// The security state, normalized to the caption of the state_id value. In the case of 'Other', it is defined by the source.
	State string `json:"state,omitempty"`
	// The security state of the managed entity.
	StateId int `json:"state_id,omitempty"`
}
