// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package objects

// Service - The Service object describes characteristics of a service, ` e.g. AWS EC2. `
type Service struct {
	// The list of labels associated with the service.
	Labels []string `json:"labels,omitempty"`
	// The name of the service.
	Name string `json:"name"`
	// The list of tags; `{key:value}` pairs associated to the service.
	Tags []*KeyValueObject `json:"tags,omitempty"`
	// The unique identifier of the service.
	Uid string `json:"uid"`
	// The version of the service.
	Version string `json:"version,omitempty"`
}
