// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package objects

// Session - The Session object describes details about an authenticated session. e.g. Session Creation Time, Session Issuer.
type Session struct {
	// The number of identical sessions spawned from the same source IP, destination IP, application, and content/threat type seen over a period of time.
	Count int `json:"count,omitempty"`
	// The time when the session was created.
	CreatedTime int64 `json:"created_time,omitempty"`
	CredentialUid string `json:"credential_uid,omitempty"`
	// The reason which triggered the session expiration.
	ExpirationReason string `json:"expiration_reason,omitempty"`
	// The session expiration time.
	ExpirationTime int64 `json:"expiration_time,omitempty"`
	IsMfa bool `json:"is_mfa,omitempty"`
	IsRemote bool `json:"is_remote,omitempty"`
	IsVpn bool `json:"is_vpn,omitempty"`
	// The identifier of the session issuer.
	Issuer string `json:"issuer,omitempty"`
	// The Pseudo Terminal associated with the session. Ex: the tty or pts value.
	Terminal string `json:"terminal,omitempty"`
	// The unique identifier of the session.
	Uid string `json:"uid,omitempty"`
	// The alternate unique identifier of the session. e.g. AWS ARN - `arn:aws:sts::123344444444:assumed-role/Admin/example-session`.
	UidAlt string `json:"uid_alt,omitempty"`
	// The universally unique identifier of the session.
	Uuid string `json:"uuid,omitempty"`
}
