// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type Span struct {
	Object
	Duration   int64    `json:"duration,omitempty"`
	EndTime    int64    `json:"end_time"`
	Message    string   `json:"message,omitempty"`
	Operation  string   `json:"operation,omitempty"`
	ParentUid  string   `json:"parent_uid,omitempty"`
	Service    *Service `json:"service,omitempty"`
	StartTime  int64    `json:"start_time"`
	StatusCode string   `json:"status_code,omitempty"`
	Uid        string   `json:"uid"`
}
