// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// Startup Item - The startup item object describes an application component that has associated startup criteria and configurations.
type StartupItem struct {
	// The startup item kernel driver resource.
	Driver *KernelDriver `json:"driver,omitempty"`
	// The startup item job resource.
	Job *Job `json:"job,omitempty"`
	// The unique name of the startup item.
	Name string `json:"name"`
	// The startup item process resource.
	Process *Process `json:"process,omitempty"`
	// The list of normalized identifiers that describe the startup items' properties when it is running.  Use this field to capture extended information about the process, which may depend on the type of startup item.  E.g., A Windows service that interacts with the desktop.
	RunModeIds []int `json:"run_mode_ids,omitempty"`
	// The list of run_modes, normalized to the captions of the run_mode_id values.  In the case of 'Other', they are defined by the event source.
	RunModes []string `json:"run_modes,omitempty"`
	// The run state of the startup item.
	RunState string `json:"run_state,omitempty"`
	// The run state ID of the startup item.
	RunStateId int `json:"run_state_id,omitempty"`
	// The start type of the startup item.
	StartType string `json:"start_type,omitempty"`
	// The start type ID of the startup item.
	StartTypeId int `json:"start_type_id"`
	// The startup item type.
	Type string `json:"type,omitempty"`
	// The startup item type identifier.
	TypeId int `json:"type_id,omitempty"`
}
