// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package objects

// MITRE Sub-technique - The MITRE Sub-technique object describes the ATT&CK® or ATLAS™ Sub-technique ID and/or name associated to an attack.
type SubTechnique struct {
	// The name of the attack sub-technique. For example: `Scanning IP Blocks` or `User Execution: Unsafe ML Artifacts`.
	Name string `json:"name"`
	// The versioned permalink of the attack sub-technique. For example: `https://attack.mitre.org/versions/v14/techniques/T1595/001/`.
	SrcUrl string `json:"src_url,omitempty"`
	// The unique identifier of the attack sub-technique. For example: `T1595.001` or `AML.T0011.000`.
	Uid string `json:"uid"`
}
