// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

import "fmt"

type Table struct {
	CreatedTime  int64    `json:"created_time,omitempty"`
	Desc         string   `json:"desc,omitempty"`
	Groups       []*Group `json:"groups,omitempty"`
	ModifiedTime int64    `json:"modified_time,omitempty"`
	Name         string   `json:"name"`
	Size         int64    `json:"size,omitempty"`
	Uid          string   `json:"uid"`
}

// Validate checks that all required fields are properly set
func (o *Table) Validate() error {
	if o.Uid == "" {
		return fmt.Errorf("required field uid is empty")
	}
	if o.Name == "" {
		return fmt.Errorf("required field name is empty")
	}
	return nil
}
