// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// MITRE Technique - The MITRE Technique object describes the ATT&CK® or ATLAS™ Technique ID and/or name associated to an attack.
type Technique struct {
	// The name of the attack technique. For example: `Active Scanning` or `AI Model Inference API Access`.
	Name string `json:"name"`
	// The versioned permalink of the attack technique. For example: `https://attack.mitre.org/versions/v14/techniques/T1595/`.
	SrcUrl string `json:"src_url,omitempty"`
	// The unique identifier of the attack technique. For example: `T1595` or `AML.T0040`.
	Uid string `json:"uid"`
}
