// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// Threat Actor - Threat actor is responsible for the observed malicious activity.
type ThreatActor struct {
	// The name of the threat actor.
	Name string `json:"name"`
	// The classification of the threat actor based on their motivations, capabilities, or affiliations. Common types include nation-state actors, cybercriminal groups, hacktivists, or insider threats.
	Type string `json:"type,omitempty"`
	// The normalized datastore resource type identifier.
	TypeId int `json:"type_id,omitempty"`
}
