// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type Timespan struct {
	Object
	Duration       int64  `json:"duration,omitempty"`
	DurationDays   int    `json:"duration_days,omitempty"`
	DurationHours  int    `json:"duration_hours,omitempty"`
	DurationMins   int    `json:"duration_mins,omitempty"`
	DurationMonths int    `json:"duration_months,omitempty"`
	DurationSecs   int    `json:"duration_secs,omitempty"`
	DurationWeeks  int    `json:"duration_weeks,omitempty"`
	DurationYears  int    `json:"duration_years,omitempty"`
	EndTime        int64  `json:"end_time,omitempty"`
	StartTime      int64  `json:"start_time,omitempty"`
	Type           string `json:"type,omitempty"`
	TypeId         int    `json:"type_id,omitempty"`
}
