// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package objects

// Transport Layer Security (TLS) - The Transport Layer Security (TLS) object describes the negotiated TLS protocol used for secure communications over an establish network connection.
type Tls struct {
	Alert int `json:"alert,omitempty"`
	Certificate *Certificate `json:"certificate,omitempty"`
	CertificateChain []string `json:"certificate_chain,omitempty"`
	Cipher string `json:"cipher,omitempty"`
	ClientCiphers []string `json:"client_ciphers,omitempty"`
	ExtensionList []*TlsExtension `json:"extension_list,omitempty"`
	HandshakeDur int `json:"handshake_dur,omitempty"`
	Ja3Hash *Fingerprint `json:"ja3_hash,omitempty"`
	Ja3sHash *Fingerprint `json:"ja3s_hash,omitempty"`
	KeyLength int `json:"key_length,omitempty"`
	Sans []*San `json:"sans,omitempty"`
	ServerCiphers []string `json:"server_ciphers,omitempty"`
	Sni string `json:"sni,omitempty"`
	TlsExtensionList []*TlsExtension `json:"tls_extension_list,omitempty"`
	// The TLS protocol version.
	Version string `json:"version"`
}
