// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

// TLS Extension - The TLS Extension object describes additional attributes that extend the base Transport Layer Security (TLS) object.
type TlsExtension struct {
	// The data contains information specific to the particular extension type.
	Data string `json:"data,omitempty"`
	// The TLS extension type. For example: `Server Name`.
	Type string `json:"type,omitempty"`
	// The TLS extension type identifier. See <a target='_blank' href='https://datatracker.ietf.org/doc/html/rfc8446#page-35'>The Transport Layer Security (TLS) extension page</a>.
	TypeId int `json:"type_id"`
}
