// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type Trait struct {
	Category string   `json:"category,omitempty"`
	Name     string   `json:"name"`
	Type     string   `json:"type,omitempty"`
	Uid      string   `json:"uid"`
	Values   []string `json:"values,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *Trait) Validate() error {
	// No required string fields to validate
	return nil
}
