// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type TransformationInfo struct {
	Lang      string   `json:"lang,omitempty"`
	Name      string   `json:"name,omitempty"`
	Product   *Product `json:"product,omitempty"`
	Time      int64    `json:"time,omitempty"`
	Uid       string   `json:"uid,omitempty"`
	UrlString string   `json:"url_string,omitempty"`
}
