// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// Unmanned Aerial System - The Unmanned Aerial System object describes the characteristics, Position Location Information (PLI), and other metadata of Unmanned Aerial Systems (UAS) and other unmanned and drone systems used in Remote ID. Remote ID is defined in the Standard Specification for Remote ID and Tracking (ASTM Designation: F3411-22a) <a target='_blank' href='https://cdn.standards.iteh.ai/samples/112830/71297057ac42432880a203654f213709/ASTM-F3411-22a.pdf'>ASTM F3411-22a</a>.
type UnmannedAerialSystem struct {
	HwInfo *DeviceHwInfo `json:"hw_info,omitempty"`
	Location *Location `json:"location,omitempty"`
	// The name of the unmanned system as reported by tracking or sensing hardware.
	Name string `json:"name,omitempty"`
	// The serial number of the unmanned system. This is expressed in `CTA-2063-A` format.
	SerialNumber string `json:"serial_number,omitempty"`
	// The type of the UAS. For example, Helicopter, Gyroplane, Rocket, etc.
	Type string `json:"type,omitempty"`
	// The UAS type identifier.
	TypeId int `json:"type_id,omitempty"`
	// The primary identification identifier for an unmanned system. This can be a Serial Number (in `CTA-2063-A` format, the Registration ID (provided by the `CAA`, a UTM, or a unique Session ID.
	Uid string `json:"uid,omitempty"`
	// A secondary identification identifier for an unmanned system. This can be a Serial Number (in `CTA-2063-A` format, the Registration ID (provided by the `CAA`, a UTM, or a unique Session ID.
	UidAlt string `json:"uid_alt,omitempty"`
	// The Unmanned Aircraft System Traffic Management (UTM) provided universal unique ID (UUID) traceable to a non-obfuscated ID where this UTM UUID acts as a 'session id' to protect exposure of operationally sensitive information.
	Uuid string `json:"uuid,omitempty"`
}
