// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package objects

// Uniform Resource Locator - The Uniform Resource Locator (URL) object describes the characteristics of a URL.
type Url struct {
	Categories []string `json:"categories,omitempty"`
	CategoryIds []int `json:"category_ids,omitempty"`
	// The domain portion of the URL. For example: `example.com` in `https://sub.example.com`.
	Domain string `json:"domain,omitempty"`
	// The URL host as extracted from the URL. For example: `www.example.com` from `www.example.com/download/trouble`.
	Hostname string `json:"hostname,omitempty"`
	// The URL path as extracted from the URL. For example: `/download/trouble` from `www.example.com/download/trouble`.
	Path string `json:"path,omitempty"`
	// The URL port. For example: `80`.
	Port string `json:"port,omitempty"`
	QueryString string `json:"query_string,omitempty"`
	// The context in which a resource was retrieved in a web request.
	ResourceType string `json:"resource_type,omitempty"`
	Scheme string `json:"scheme,omitempty"`
	Subdomain string `json:"subdomain,omitempty"`
	// The URL string. See RFC 1738. For example: `http://www.example.com/download/trouble.exe`. Note: The URL path should not populate the URL string.
	UrlString string `json:"url_string,omitempty"`
}
