// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type User struct {
	Account                 *Account                  `json:"account,omitempty"`
	CredentialUid           string                    `json:"credential_uid,omitempty"`
	DisplayName             string                    `json:"display_name,omitempty"`
	Domain                  string                    `json:"domain,omitempty"`
	EmailAddr               string                    `json:"email_addr,omitempty"`
	ForwardAddr             string                    `json:"forward_addr,omitempty"`
	FullName                string                    `json:"full_name,omitempty"`
	Groups                  []*Group                  `json:"groups,omitempty"`
	HasMfa                  bool                      `json:"has_mfa,omitempty"`
	LdapPerson              *LdapPerson               `json:"ldap_person,omitempty"`
	Name                    string                    `json:"name,omitempty"`
	Org                     *Organization             `json:"org,omitempty"`
	PhoneNumber             string                    `json:"phone_number,omitempty"`
	ProgrammaticCredentials []*ProgrammaticCredential `json:"programmatic_credentials,omitempty"`
	RiskLevel               string                    `json:"risk_level,omitempty"`
	RiskLevelId             int                       `json:"risk_level_id,omitempty"`
	RiskScore               int                       `json:"risk_score,omitempty"`
	Type                    string                    `json:"type,omitempty"`
	TypeId                  int                       `json:"type_id,omitempty"`
	Uid                     string                    `json:"uid,omitempty"`
	UidAlt                  string                    `json:"uid_alt,omitempty"`
}
