// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type VendorAttributes struct {
	Severity   string `json:"severity,omitempty"`
	SeverityId int    `json:"severity_id,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *VendorAttributes) Validate() error {
	// No required string fields to validate
	return nil
}
