// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

import "fmt"

type WebResource struct {
	Data      string `json:"data,omitempty"`
	Desc      string `json:"desc,omitempty"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	Uid       string `json:"uid"`
	UrlString string `json:"url_string,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *WebResource) Validate() error {
	if o.Name == "" {
		return fmt.Errorf("required field name is empty")
	}
	if o.Type == "" {
		return fmt.Errorf("required field type is empty")
	}
	if o.Uid == "" {
		return fmt.Errorf("required field uid is empty")
	}
	return nil
}
