// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type Whois struct {
	Object
	AutonomousSystem *AutonomousSystem `json:"autonomous_system,omitempty"`
	CreatedTime      int64             `json:"created_time,omitempty"`
	DnssecStatus     string            `json:"dnssec_status,omitempty"`
	DnssecStatusId   int               `json:"dnssec_status_id,omitempty"`
	Domain           string            `json:"domain,omitempty"`
	DomainContacts   []*DomainContact  `json:"domain_contacts,omitempty"`
	EmailAddr        string            `json:"email_addr,omitempty"`
	Isp              string            `json:"isp,omitempty"`
	IspOrg           string            `json:"isp_org,omitempty"`
	LastSeenTime     int64             `json:"last_seen_time,omitempty"`
	NameServers      []string          `json:"name_servers,omitempty"`
	PhoneNumber      string            `json:"phone_number,omitempty"`
	Registrar        string            `json:"registrar,omitempty"`
	Status           string            `json:"status,omitempty"`
	Subdomains       []string          `json:"subdomains,omitempty"`
	Subnet           string            `json:"subnet,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *Whois) Validate() error {
	// No required string fields to validate
	return nil
}
