// Code generated by ocsf-generator. DO NOT EDIT.

package objects

// WHOIS - The resources of a WHOIS record for a given domain. This can include domain names, IP address blocks, autonomous system information, and/or contact and registration information for a domain.
type Whois struct {
	// The autonomous system information associated with a domain.
	AutonomousSystem *AutonomousSystem `json:"autonomous_system,omitempty"`
	// When the domain was registered or WHOIS entry was created.
	CreatedTime int64 `json:"created_time,omitempty"`
	DnssecStatus string `json:"dnssec_status,omitempty"`
	DnssecStatusId int `json:"dnssec_status_id,omitempty"`
	// The domain name corresponding to the WHOIS record.
	Domain string `json:"domain,omitempty"`
	DomainContacts []*DomainContact `json:"domain_contacts,omitempty"`
	// The email address for the registrar's abuse contact
	EmailAddr string `json:"email_addr,omitempty"`
	Isp string `json:"isp,omitempty"`
	IspOrg string `json:"isp_org,omitempty"`
	// When the WHOIS record was last updated or seen at.
	LastSeenTime int64 `json:"last_seen_time,omitempty"`
	NameServers []string `json:"name_servers,omitempty"`
	// The phone number for the registrar's abuse contact
	PhoneNumber string `json:"phone_number,omitempty"`
	Registrar string `json:"registrar,omitempty"`
	// The status of a domain and its ability to be transferred, e.g., `clientTransferProhibited`.
	Status string `json:"status,omitempty"`
	Subdomains []string `json:"subdomains,omitempty"`
	// The IP address block (CIDR) associated with a domain.
	Subnet string `json:"subnet,omitempty"`
}
