// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package discovery

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/common/ocsf"
	"github.com/telhawk-systems/telhawk-stack/common/ocsf/objects"
)

type JobQuery struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Job *objects.Job `json:"job"`
}

func NewJobQuery(activityID int) *JobQuery {
	return &JobQuery{
		Event: ocsf.Event{
			CategoryUID: 5,
			ClassUID:    5010,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(5, 5010, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "discovery",
			Class:       "job_query",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

// Validate checks that all required fields are properly set
func (e *JobQuery) Validate() error {
	// No required string fields to validate
	return nil
}

