// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package application

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/common/ocsf"
	"github.com/telhawk-systems/telhawk-stack/common/ocsf/objects"
)

type ApplicationLifecycle struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	App *objects.Product `json:"app"`
}

const (
	ApplicationLifecycleActivityInstall = 1
	ApplicationLifecycleActivityRemove = 2
	ApplicationLifecycleActivityStart = 3
	ApplicationLifecycleActivityStop = 4
	ApplicationLifecycleActivityRestart = 5
	ApplicationLifecycleActivityEnable = 6
	ApplicationLifecycleActivityDisable = 7
	ApplicationLifecycleActivityUpdate = 8
)

func NewApplicationLifecycle(activityID int) *ApplicationLifecycle {
	return &ApplicationLifecycle{
		Event: ocsf.Event{
			CategoryUID: 6,
			ClassUID:    6002,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(6, 6002, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "application",
			Class:       "application_lifecycle",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

// Validate checks that all required fields are properly set
func (e *ApplicationLifecycle) Validate() error {
	// No required string fields to validate
	return nil
}

