// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package findings

import (
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
	"time"
)

type ApplicationSecurityPostureFinding struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Application     *objects.Application       `json:"application,omitempty"`
	Compliance      *objects.Compliance        `json:"compliance,omitempty"`
	Remediation     *objects.Remediation       `json:"remediation,omitempty"`
	Resources       []*objects.ResourceDetails `json:"resources,omitempty"`
	Vulnerabilities []*objects.Vulnerability   `json:"vulnerabilities,omitempty"`
}

func NewApplicationSecurityPostureFinding(activityID int) *ApplicationSecurityPostureFinding {
	return &ApplicationSecurityPostureFinding{
		Event: ocsf.Event{
			CategoryUID: 2,
			ClassUID:    2007,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(2, 2007, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "findings",
			Class:       "application_security_posture_finding",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}
