// Code generated by ocsf-generator. DO NOT EDIT.

package findings

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Compliance Finding - Compliance Finding events describe results of evaluations performed against resources, to check compliance with various Industry Frameworks or Security Standards such as <code>NIST SP 800-53, CIS AWS Foundations Benchmark v1.4.0, ISO/IEC 27001</code> etc. Note: if the event producer is a security control, the <code>security_control</code> profile should be applied and its <code>attacks</code> information, if present, should be duplicated into the <code>finding_info</code> object. <br><strong>Note: </strong>If the Finding is an incident, i.e. requires incident workflow, also apply the <code>incident</code> profile or aggregate this finding into an <code>Incident Finding</code>.
// OCSF Class UID: 2003
//
// This is a generated struct representing the OCSF event class.
type ComplianceFinding struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Compliance *objects.Compliance `json:"compliance"`
	// Describes various evidence artifacts associated with the compliance finding.
	Evidences []*objects.Evidences `json:"evidences,omitempty"`
	Remediation *objects.Remediation `json:"remediation,omitempty"`
	// Describes details about the resource that is the subject of the compliance check.
	Resource *objects.ResourceDetails `json:"resource,omitempty"`
	// Describes details about the resource/resources that are the subject of the compliance check.
	Resources []*objects.ResourceDetails `json:"resources,omitempty"`
}

// NewComplianceFinding creates a new Compliance Finding event
func NewComplianceFinding(activityID int) *ComplianceFinding {
	return &ComplianceFinding{
		Event: ocsf.Event{
			CategoryUID: 2,
			ClassUID:    2003,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(2, 2003, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "findings",
			Class:       "compliance_finding",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

