// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package findings

import (
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
	"time"
)

type DataSecurityFinding struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	ActivityName    string                     `json:"activity_name,omitempty"`
	Actor           *objects.Actor             `json:"actor,omitempty"`
	Confidence      string                     `json:"confidence,omitempty"`
	ConfidenceId    int                        `json:"confidence_id,omitempty"`
	ConfidenceScore int                        `json:"confidence_score,omitempty"`
	DataSecurity    *objects.DataSecurity      `json:"data_security,omitempty"`
	Database        *objects.Database          `json:"database,omitempty"`
	Databucket      *objects.Databucket        `json:"databucket,omitempty"`
	Device          *objects.Device            `json:"device,omitempty"`
	DstEndpoint     *objects.NetworkEndpoint   `json:"dst_endpoint,omitempty"`
	File            *objects.File              `json:"file,omitempty"`
	Impact          string                     `json:"impact,omitempty"`
	ImpactId        int                        `json:"impact_id,omitempty"`
	ImpactScore     int                        `json:"impact_score,omitempty"`
	IsAlert         bool                       `json:"is_alert,omitempty"`
	Resources       []*objects.ResourceDetails `json:"resources,omitempty"`
	RiskDetails     string                     `json:"risk_details,omitempty"`
	RiskLevel       string                     `json:"risk_level,omitempty"`
	RiskLevelId     int                        `json:"risk_level_id,omitempty"`
	RiskScore       int                        `json:"risk_score,omitempty"`
	SrcEndpoint     *objects.NetworkEndpoint   `json:"src_endpoint,omitempty"`
	Table           *objects.Table             `json:"table,omitempty"`
}

const (
	DataSecurityFindingActivityCreate     = 1
	DataSecurityFindingActivityUpdate     = 2
	DataSecurityFindingActivityClose      = 3
	DataSecurityFindingActivitySuppressed = 4
)

func NewDataSecurityFinding(activityID int) *DataSecurityFinding {
	return &DataSecurityFinding{
		Event: ocsf.Event{
			CategoryUID: 2,
			ClassUID:    2006,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(2, 2006, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "findings",
			Class:       "data_security_finding",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}
