// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package findings

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Data Security Finding - A Data Security Finding describes detections or alerts generated by various data security products such as Data Loss Prevention (DLP), Data Classification, Secrets Management, Digital Rights Management (DRM), Data Security Posture Management (DSPM), and similar tools. These detections or alerts can be created using fingerprinting, statistical analysis, machine learning or other methodologies. The finding describes the actors and endpoints who accessed or own the sensitive data, as well as the resources which store the sensitive data. Note: if the event producer is a security control, the <code>security_control</code> profile should be applied and its <code>attacks</code> information, if present, should be duplicated into the <code>finding_info</code> object. <br><strong>Note: </strong>If the Finding is an incident, i.e. requires incident workflow, also apply the <code>incident</code> profile  or aggregate this finding into an <code>Incident Finding</code>.
// OCSF Class UID: 2006
//
// This is a generated struct representing the OCSF event class.
type DataSecurityFinding struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	// The Data Security finding activity name, as defined by the `activity_id`.
	ActivityName string `json:"activity_name,omitempty"`
	// Describes details about the actor implicated in the data security finding. Either an actor that owns a particular digital file or information store, or an actor which accessed classified or sensitive data.
	Actor *objects.Actor `json:"actor,omitempty"`
	Confidence string `json:"confidence,omitempty"`
	ConfidenceId int `json:"confidence_id,omitempty"`
	ConfidenceScore int `json:"confidence_score,omitempty"`
	DataSecurity *objects.DataSecurity `json:"data_security,omitempty"`
	// Describes the database where classified or sensitive data is stored in, or was accessed from. Databases are typically datastore services that contain an organized collection of structured and/or semi-structured data.
	Database *objects.Database `json:"database,omitempty"`
	// Describes the databucket where classified or sensitive data is stored in, or was accessed from. The data bucket object is a basic container that holds data, typically organized through the use of data partitions.
	Databucket *objects.Databucket `json:"databucket,omitempty"`
	// Describes the device where classified or sensitive data is stored in, or was accessed from.
	Device *objects.Device `json:"device,omitempty"`
	// Describes the endpoint where classified or sensitive data is stored in, or was accessed from.
	DstEndpoint *objects.NetworkEndpoint `json:"dst_endpoint,omitempty"`
	// Describes a file that contains classified or sensitive data.
	File *objects.File `json:"file,omitempty"`
	Impact string `json:"impact,omitempty"`
	ImpactId int `json:"impact_id,omitempty"`
	ImpactScore int `json:"impact_score,omitempty"`
	// Indicates that the event is considered to be an alertable signal. For example, an `activity_id` of 'Create' could constitute an alertable signal and the value would be `true`, while 'Close' likely would not and either omit the attribute or set its value to `false`.  Note that other events with the `security_control` profile may also be deemed alertable signals and may also carry `is_alert = true` attributes.
	IsAlert bool `json:"is_alert,omitempty"`
	// Describes details about additional resources, where classified or sensitive data is stored in, or was accessed from. <p> You can populate this object, if the specific resource type objects available in the class (`database, databucket, table, file`) aren't sufficient; OR <br> You can also choose to duplicate `uid, name` of the specific resources objects, for a consistent access to resource uids across all findings.
	Resources []*objects.ResourceDetails `json:"resources,omitempty"`
	RiskDetails string `json:"risk_details,omitempty"`
	RiskLevel string `json:"risk_level,omitempty"`
	RiskLevelId int `json:"risk_level_id,omitempty"`
	RiskScore int `json:"risk_score,omitempty"`
	// Details about the source endpoint where classified or sensitive data was accessed from.
	SrcEndpoint *objects.NetworkEndpoint `json:"src_endpoint,omitempty"`
	// Describes the table where classified or sensitive data is stored in, or was accessed from. The table object represents a table within a structured relational database, warehouse, lake, or similar.
	Table *objects.Table `json:"table,omitempty"`
}

// Activity IDs for Data Security Finding
const (
	DataSecurityFindingActivityCreate = 1 // A new Data Security finding is created.
	DataSecurityFindingActivityUpdate = 2 // An existing Data Security finding is updated with more information.
	DataSecurityFindingActivityClose = 3 // An existing Data Security finding is closed, this can be due to any resolution (e.g., True Positive, False Positive, etc.).
	DataSecurityFindingActivitySuppressed = 4 // An existing Data Security finding is suppressed due to inaccurate detection techniques or a known true negative.
)

// NewDataSecurityFinding creates a new Data Security Finding event
func NewDataSecurityFinding(activityID int) *DataSecurityFinding {
	return &DataSecurityFinding{
		Event: ocsf.Event{
			CategoryUID: 2,
			ClassUID:    2006,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(2, 2006, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "findings",
			Class:       "data_security_finding",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

