// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package findings

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Detection Finding - A Detection Finding describes detections or alerts generated by security products using correlation engines, detection engines or other methodologies. Note: if the event producer is a security control, the <code>security_control</code> profile should be applied and its <code>attacks</code> information, if present, should be duplicated into the <code>finding_info</code> object. <br><strong>Note: </strong>If the Finding is an incident, i.e. requires incident workflow, also apply the <code>incident</code> profile  or aggregate this finding into an <code>Incident Finding</code>.
// OCSF Class UID: 2004
//
// This is a generated struct representing the OCSF event class.
type DetectionFinding struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	// Describes baseline information about normal activity patterns, along with any detected deviations or anomalies that triggered this finding.
	AnomalyAnalyses []*objects.AnomalyAnalysis `json:"anomaly_analyses,omitempty"`
	Confidence string `json:"confidence,omitempty"`
	ConfidenceId int `json:"confidence_id,omitempty"`
	ConfidenceScore int `json:"confidence_score,omitempty"`
	// Describes various evidence artifacts associated to the activity/activities that triggered a security detection.
	Evidences []*objects.Evidences `json:"evidences,omitempty"`
	Impact string `json:"impact,omitempty"`
	ImpactId int `json:"impact_id,omitempty"`
	ImpactScore int `json:"impact_score,omitempty"`
	// Indicates that the event is considered to be an alertable signal. For example, an `activity_id` of 'Create' could constitute an alertable signal and the value would be `true`, while 'Close' likely would not and either omit the attribute or set its value to `false`.  Note that other events with the `security_control` profile may also be deemed alertable signals and may also carry `is_alert = true` attributes.
	IsAlert bool `json:"is_alert,omitempty"`
	// Describes malware reported in a Detection Finding.
	Malware []*objects.Malware `json:"malware,omitempty"`
	// Describes details about malware scan job that triggered this Detection Finding.
	MalwareScanInfo *objects.MalwareScanInfo `json:"malware_scan_info,omitempty"`
	Remediation *objects.Remediation `json:"remediation,omitempty"`
	// Describes details about resources that were the target of the activity that triggered the finding.
	Resources []*objects.ResourceDetails `json:"resources,omitempty"`
	RiskDetails string `json:"risk_details,omitempty"`
	RiskLevel string `json:"risk_level,omitempty"`
	RiskLevelId int `json:"risk_level_id,omitempty"`
	RiskScore int `json:"risk_score,omitempty"`
	// Describes vulnerabilities reported in a Detection Finding.
	Vulnerabilities []*objects.Vulnerability `json:"vulnerabilities,omitempty"`
}

// NewDetectionFinding creates a new Detection Finding event
func NewDetectionFinding(activityID int) *DetectionFinding {
	return &DetectionFinding{
		Event: ocsf.Event{
			CategoryUID: 2,
			ClassUID:    2004,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(2, 2004, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "findings",
			Class:       "detection_finding",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

