// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package findings

import (
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
	"time"
)

type DetectionFinding struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	AnomalyAnalyses []*objects.AnomalyAnalysis `json:"anomaly_analyses,omitempty"`
	Confidence      string                     `json:"confidence,omitempty"`
	ConfidenceId    int                        `json:"confidence_id,omitempty"`
	ConfidenceScore int                        `json:"confidence_score,omitempty"`
	Evidences       []*objects.Evidences       `json:"evidences,omitempty"`
	Impact          string                     `json:"impact,omitempty"`
	ImpactId        int                        `json:"impact_id,omitempty"`
	ImpactScore     int                        `json:"impact_score,omitempty"`
	IsAlert         bool                       `json:"is_alert,omitempty"`
	Malware         []*objects.Malware         `json:"malware,omitempty"`
	MalwareScanInfo *objects.MalwareScanInfo   `json:"malware_scan_info,omitempty"`
	Remediation     *objects.Remediation       `json:"remediation,omitempty"`
	Resources       []*objects.ResourceDetails `json:"resources,omitempty"`
	RiskDetails     string                     `json:"risk_details,omitempty"`
	RiskLevel       string                     `json:"risk_level,omitempty"`
	RiskLevelId     int                        `json:"risk_level_id,omitempty"`
	RiskScore       int                        `json:"risk_score,omitempty"`
	Vulnerabilities []*objects.Vulnerability   `json:"vulnerabilities,omitempty"`
}

func NewDetectionFinding(activityID int) *DetectionFinding {
	return &DetectionFinding{
		Event: ocsf.Event{
			CategoryUID: 2,
			ClassUID:    2004,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(2, 2004, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "findings",
			Class:       "detection_finding",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

// Validate checks that all required fields are properly set
func (e *DetectionFinding) Validate() error {
	// No required string fields to validate
	return nil
}
