// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package findings

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// IAM Analysis Finding - This finding represents an IAM analysis result, which evaluates IAM policies, access patterns, and IAM configurations for potential security risks. The analysis can focus on either an identity (user, role, service account) or a resource to assess permissions, access patterns, and security posture within the IAM domain. <br><strong>Note:</strong> Use <code>permission_analysis_results</code> for identity-centric analysis (evaluating what an identity can do) and <code>access_analysis_result</code> for resource-centric analysis (evaluating who can access a resource). These complement each other for comprehensive IAM security assessment.<br><strong>Note:</strong> If the Finding is an incident, i.e. requires incident workflow, also apply the <code>incident</code> profile or aggregate this finding into an <code>Incident Finding</code>.
// OCSF Class UID: 2008
//
// This is a generated struct representing the OCSF event class.
type IamAnalysisFinding struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	AccessAnalysisResult *objects.AccessAnalysisResult `json:"access_analysis_result,omitempty"`
	// Details about applications, services, or systems that are accessible based on the IAM analysis. For identity-centric analysis, this represents applications the identity can access. For resource-centric analysis, this represents applications that can access the resource.
	Applications []*objects.Application `json:"applications,omitempty"`
	IdentityActivityMetrics *objects.IdentityActivityMetrics `json:"identity_activity_metrics,omitempty"`
	PermissionAnalysisResults []*objects.PermissionAnalysisResult `json:"permission_analysis_results,omitempty"`
	Remediation *objects.Remediation `json:"remediation,omitempty"`
	// Details about resources involved in the IAM analysis. For identity-centric analysis, this represents resources the identity can access. For resource-centric analysis, this represents the resource being analyzed and related resources in the access chain.
	Resources []*objects.ResourceDetails `json:"resources,omitempty"`
	// Details about the identity (user, role, service account, or other principal) that is the subject of the IAM analysis. This provides context about the identity being evaluated for security risks and access patterns.
	User *objects.User `json:"user,omitempty"`
}

// NewIamAnalysisFinding creates a new IAM Analysis Finding event
func NewIamAnalysisFinding(activityID int) *IamAnalysisFinding {
	return &IamAnalysisFinding{
		Event: ocsf.Event{
			CategoryUID: 2,
			ClassUID:    2008,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(2, 2008, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "findings",
			Class:       "iam_analysis_finding",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

