// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package findings

import (
	"fmt"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
	"time"
)

type IncidentFinding struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	ActivityName      string                    `json:"activity_name,omitempty"`
	Assignee          *objects.User             `json:"assignee,omitempty"`
	AssigneeGroup     *objects.Group            `json:"assignee_group,omitempty"`
	Attacks           []*objects.Attack         `json:"attacks,omitempty"`
	Comment           string                    `json:"comment,omitempty"`
	Confidence        string                    `json:"confidence,omitempty"`
	ConfidenceId      int                       `json:"confidence_id,omitempty"`
	ConfidenceScore   int                       `json:"confidence_score,omitempty"`
	Desc              string                    `json:"desc,omitempty"`
	EndTime           int64                     `json:"end_time,omitempty"`
	FindingInfoList   []*objects.FindingInfo    `json:"finding_info_list"`
	Impact            string                    `json:"impact,omitempty"`
	ImpactId          int                       `json:"impact_id,omitempty"`
	ImpactScore       int                       `json:"impact_score,omitempty"`
	IsSuspectedBreach bool                      `json:"is_suspected_breach,omitempty"`
	Priority          string                    `json:"priority,omitempty"`
	PriorityId        int                       `json:"priority_id,omitempty"`
	SrcUrl            string                    `json:"src_url,omitempty"`
	StartTime         int64                     `json:"start_time,omitempty"`
	Ticket            *objects.Ticket           `json:"ticket,omitempty"`
	Tickets           []*objects.Ticket         `json:"tickets,omitempty"`
	VendorAttributes  *objects.VendorAttributes `json:"vendor_attributes,omitempty"`
	Verdict           string                    `json:"verdict,omitempty"`
	VerdictId         int                       `json:"verdict_id,omitempty"`
}

const (
	IncidentFindingActivityCreate = 1
	IncidentFindingActivityUpdate = 2
	IncidentFindingActivityClose  = 3
)

func NewIncidentFinding(activityID int) *IncidentFinding {
	return &IncidentFinding{
		Event: ocsf.Event{
			CategoryUID: 2,
			ClassUID:    2005,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(2, 2005, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "findings",
			Class:       "incident_finding",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

// Validate checks that all required fields are properly set
func (e *IncidentFinding) Validate() error {
	// No required string fields to validate
	return nil
}
