// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package findings

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Security Finding - Security Finding events describe findings, detections, anomalies, alerts and/or actions performed by security products
// OCSF Class UID: 2001
//
// This is a generated struct representing the OCSF event class.
type SecurityFinding struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Analytic *objects.Analytic `json:"analytic,omitempty"`
	// An array of <a target='_blank' href='https://attack.mitre.org'>MITRE ATT&CK®</a> objects describing the tactics, techniques & sub-techniques associated to the Finding.
	Attacks []*objects.Attack `json:"attacks,omitempty"`
	CisCsc []*objects.CisCsc `json:"cis_csc,omitempty"`
	Compliance *objects.Compliance `json:"compliance,omitempty"`
	Confidence string `json:"confidence,omitempty"`
	ConfidenceId int `json:"confidence_id,omitempty"`
	ConfidenceScore int `json:"confidence_score,omitempty"`
	DataSources []string `json:"data_sources,omitempty"`
	Evidence string `json:"evidence,omitempty"`
	Finding *objects.Finding `json:"finding"`
	Impact string `json:"impact,omitempty"`
	ImpactId int `json:"impact_id,omitempty"`
	ImpactScore int `json:"impact_score,omitempty"`
	KillChain []*objects.KillChainPhase `json:"kill_chain,omitempty"`
	Malware []*objects.Malware `json:"malware,omitempty"`
	Nist []string `json:"nist,omitempty"`
	Process *objects.Process `json:"process,omitempty"`
	Resources []*objects.ResourceDetails `json:"resources,omitempty"`
	RiskLevel string `json:"risk_level,omitempty"`
	RiskLevelId int `json:"risk_level_id,omitempty"`
	RiskScore int `json:"risk_score,omitempty"`
	// The normalized state of a security finding.
	State string `json:"state,omitempty"`
	// The normalized state identifier of a security finding.
	StateId int `json:"state_id"`
	Vulnerabilities []*objects.Vulnerability `json:"vulnerabilities,omitempty"`
}

// Activity IDs for Security Finding
const (
	SecurityFindingActivityCreate = 1 // A security finding was created.
	SecurityFindingActivityUpdate = 2 // A security finding was updated.
	SecurityFindingActivityClose = 3 // A security finding was closed.
)

// NewSecurityFinding creates a new Security Finding event
func NewSecurityFinding(activityID int) *SecurityFinding {
	return &SecurityFinding{
		Event: ocsf.Event{
			CategoryUID: 2,
			ClassUID:    2001,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(2, 2001, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "findings",
			Class:       "security_finding",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

