// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package findings

import (
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
	"time"
)

type SecurityFinding struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Analytic        *objects.Analytic          `json:"analytic,omitempty"`
	Attacks         []*objects.Attack          `json:"attacks,omitempty"`
	CisCsc          []*objects.CisCsc          `json:"cis_csc,omitempty"`
	Compliance      *objects.Compliance        `json:"compliance,omitempty"`
	Confidence      string                     `json:"confidence,omitempty"`
	ConfidenceId    int                        `json:"confidence_id,omitempty"`
	ConfidenceScore int                        `json:"confidence_score,omitempty"`
	DataSources     []string                   `json:"data_sources,omitempty"`
	Evidence        string                     `json:"evidence,omitempty"`
	Finding         *objects.Finding           `json:"finding"`
	Impact          string                     `json:"impact,omitempty"`
	ImpactId        int                        `json:"impact_id,omitempty"`
	ImpactScore     int                        `json:"impact_score,omitempty"`
	KillChain       []*objects.KillChainPhase  `json:"kill_chain,omitempty"`
	Malware         []*objects.Malware         `json:"malware,omitempty"`
	Nist            []string                   `json:"nist,omitempty"`
	Process         *objects.Process           `json:"process,omitempty"`
	Resources       []*objects.ResourceDetails `json:"resources,omitempty"`
	RiskLevel       string                     `json:"risk_level,omitempty"`
	RiskLevelId     int                        `json:"risk_level_id,omitempty"`
	RiskScore       int                        `json:"risk_score,omitempty"`
	State           string                     `json:"state,omitempty"`
	StateId         int                        `json:"state_id"`
	Vulnerabilities []*objects.Vulnerability   `json:"vulnerabilities,omitempty"`
}

const (
	SecurityFindingActivityCreate = 1
	SecurityFindingActivityUpdate = 2
	SecurityFindingActivityClose  = 3
)

func NewSecurityFinding(activityID int) *SecurityFinding {
	return &SecurityFinding{
		Event: ocsf.Event{
			CategoryUID: 2,
			ClassUID:    2001,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(2, 2001, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "findings",
			Class:       "security_finding",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

// Validate checks that all required fields are properly set
func (e *SecurityFinding) Validate() error {
	// No required string fields to validate
	return nil
}
