// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package unmanned_systems

import (
	"fmt"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
	"time"
)

type AirborneBroadcastActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Aircraft                    *objects.Aircraft                    `json:"aircraft,omitempty"`
	DstEndpoint                 *objects.NetworkEndpoint             `json:"dst_endpoint,omitempty"`
	ProtocolName                string                               `json:"protocol_name,omitempty"`
	Rssi                        int                                  `json:"rssi,omitempty"`
	SrcEndpoint                 *objects.NetworkEndpoint             `json:"src_endpoint,omitempty"`
	Traffic                     *objects.NetworkTraffic              `json:"traffic,omitempty"`
	UnmannedAerialSystem        *objects.UnmannedAerialSystem        `json:"unmanned_aerial_system"`
	UnmannedSystemOperatingArea *objects.UnmannedSystemOperatingArea `json:"unmanned_system_operating_area,omitempty"`
	UnmannedSystemOperator      *objects.User                        `json:"unmanned_system_operator"`
}

const (
	AirborneBroadcastActivityActivityUnknown = 0
	AirborneBroadcastActivityActivityCapture = 1
	AirborneBroadcastActivityActivityRecord  = 2
	AirborneBroadcastActivityActivityOther   = 99
)

func NewAirborneBroadcastActivity(activityID int) *AirborneBroadcastActivity {
	return &AirborneBroadcastActivity{
		Event: ocsf.Event{
			CategoryUID: 8,
			ClassUID:    8002,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(8, 8002, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "unmanned_systems",
			Class:       "airborne_broadcast_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

// Validate checks that all required fields are properly set
func (e *AirborneBroadcastActivity) Validate() error {
	// No required string fields to validate
	return nil
}
