// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package unmanned_systems

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Drone Flights Activity - Drone Flights Activity events report the activity of Unmanned Aerial Systems (UAS), their Operators, and mission-planning and authorization metadata as reported by the UAS platforms themselves, by Counter-UAS (CUAS) systems, or other remote monitoring or sensing infrastructure. Based on the Remote ID defined in Standard Specification for Remote ID and Tracking (ASTM Designation: F3411-22a) <a target='_blank' href='https://cdn.standards.iteh.ai/samples/112830/71297057ac42432880a203654f213709/ASTM-F3411-22a.pdf'>ASTM F3411-22a</a>
// OCSF Class UID: 8001
//
// This is a generated struct representing the OCSF event class.
type DroneFlightsActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	// The authentication type as defined by the caption of `auth_protocol_id`. In the case of 'Other', it is defined by the event source.
	AuthProtocol string `json:"auth_protocol,omitempty"`
	// The normalized identifier of the authentication type used to authorize a flight plan or mission.
	AuthProtocolId int `json:"auth_protocol_id,omitempty"`
	// UA Classification - Allows a region to classify UAS in a regional specific manner. The format may differ from region to region.
	Classification string `json:"classification,omitempty"`
	// This optional, free-text field enables the operator to describe the purpose of a flight, if so desired.
	Comment string `json:"comment,omitempty"`
	// The networking protocol associated with the Remote ID device or beacon. E.g. `BLE`, `LTE`, `802.11`.
	ProtocolName string `json:"protocol_name,omitempty"`
	SrcEndpoint *objects.NetworkEndpoint `json:"src_endpoint,omitempty"`
	// Traffic refers to the amount of data transmitted from a Unmanned Aerial System (UAS) or Counter Unmanned Aerial System (UAS) (CUAS) system at a given point of time. Ex: `bytes_in` and `bytes_out`.
	Traffic *objects.NetworkTraffic `json:"traffic,omitempty"`
	UnmannedAerialSystem *objects.UnmannedAerialSystem `json:"unmanned_aerial_system"`
	UnmannedSystemOperatingArea *objects.UnmannedSystemOperatingArea `json:"unmanned_system_operating_area,omitempty"`
	UnmannedSystemOperator *objects.User `json:"unmanned_system_operator"`
}

// Activity IDs for Drone Flights Activity
const (
	DroneFlightsActivityActivityUnknown = 0 // The event activity is unknown.
	DroneFlightsActivityActivityCapture = 1 // Remote ID information from an Unmanned System is being captured (collected).
	DroneFlightsActivityActivityRecord = 2 // Unmanned System activity is being recorded.
	DroneFlightsActivityActivityOther = 99 // The event activity is not mapped. See the <code>activity_name</code> attribute, which contains a data source specific value.
)

// NewDroneFlightsActivity creates a new Drone Flights Activity event
func NewDroneFlightsActivity(activityID int) *DroneFlightsActivity {
	return &DroneFlightsActivity{
		Event: ocsf.Event{
			CategoryUID: 8,
			ClassUID:    8001,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(8, 8001, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "unmanned_systems",
			Class:       "drone_flights_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

