// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package system

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/common/ocsf"
	"github.com/telhawk-systems/telhawk-stack/common/ocsf/objects"
)

type ModuleActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Actor *objects.Actor `json:"actor"`
	Module *objects.Module `json:"module"`
}

const (
	ModuleActivityActivityLoad = 1
	ModuleActivityActivityUnload = 2
	ModuleActivityActivityInvoke = 3
)

func NewModuleActivity(activityID int) *ModuleActivity {
	return &ModuleActivity{
		Event: ocsf.Event{
			CategoryUID: 1,
			ClassUID:    1005,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(1, 1005, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "system",
			Class:       "module_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

// Validate checks that all required fields are properly set
func (e *ModuleActivity) Validate() error {
	// No required string fields to validate
	return nil
}

