// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type AuthFactor struct {
	Device *Device `json:"device,omitempty"`
	EmailAddr string `json:"email_addr,omitempty"`
	FactorType string `json:"factor_type,omitempty"`
	FactorTypeId int `json:"factor_type_id"`
	IsHotp bool `json:"is_hotp,omitempty"`
	IsTotp bool `json:"is_totp,omitempty"`
	PhoneNumber string `json:"phone_number,omitempty"`
	Provider string `json:"provider,omitempty"`
	SecurityQuestions []string `json:"security_questions,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *AuthFactor) Validate() error {
	// No required string fields to validate
	return nil
}

