// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type Check struct {
	Desc string `json:"desc,omitempty"`
	Name string `json:"name,omitempty"`
	Severity string `json:"severity,omitempty"`
	SeverityId int `json:"severity_id,omitempty"`
	Standards []string `json:"standards,omitempty"`
	Status string `json:"status,omitempty"`
	StatusId int `json:"status_id,omitempty"`
	Uid string `json:"uid,omitempty"`
	Version string `json:"version,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *Check) Validate() error {
	// No required string fields to validate
	return nil
}

