// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

import "fmt"

type ClassifierDetails struct {
	Name string `json:"name,omitempty"`
	Type string `json:"type"`
	Uid string `json:"uid,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *ClassifierDetails) Validate() error {
	if o.Type == "" {
		return fmt.Errorf("required field type is empty")
	}
	return nil
}

