// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

import "fmt"

type Cloud struct {
	Account *Account `json:"account,omitempty"`
	CloudPartition string `json:"cloud_partition,omitempty"`
	Org *Organization `json:"org,omitempty"`
	ProjectUid string `json:"project_uid,omitempty"`
	Provider string `json:"provider"`
	Region string `json:"region,omitempty"`
	Zone string `json:"zone,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *Cloud) Validate() error {
	if o.Provider == "" {
		return fmt.Errorf("required field provider is empty")
	}
	return nil
}

