// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type FirewallRule struct {
	Category      string   `json:"category,omitempty"`
	Condition     string   `json:"condition,omitempty"`
	Desc          string   `json:"desc,omitempty"`
	Duration      int64    `json:"duration,omitempty"`
	MatchDetails  []string `json:"match_details,omitempty"`
	MatchLocation string   `json:"match_location,omitempty"`
	Name          string   `json:"name"`
	RateLimit     int      `json:"rate_limit,omitempty"`
	Sensitivity   string   `json:"sensitivity,omitempty"`
	Type          string   `json:"type,omitempty"`
	Uid           string   `json:"uid"`
	Version       string   `json:"version,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *FirewallRule) Validate() error {
	// No required string fields to validate
	return nil
}
