// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type HttpResponse struct {
	BodyLength int `json:"body_length,omitempty"`
	Code int `json:"code"`
	ContentType string `json:"content_type,omitempty"`
	HttpHeaders []*HttpHeader `json:"http_headers,omitempty"`
	Latency int `json:"latency,omitempty"`
	Length int `json:"length,omitempty"`
	Message string `json:"message,omitempty"`
	Status string `json:"status,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *HttpResponse) Validate() error {
	// No required string fields to validate
	return nil
}

