// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type IdentityActivityMetrics struct {
	FirstSeenTime int64 `json:"first_seen_time,omitempty"`
	LastAuthenticationTime int64 `json:"last_authentication_time,omitempty"`
	LastSeenTime int64 `json:"last_seen_time,omitempty"`
	PasswordLastUsedTime int64 `json:"password_last_used_time,omitempty"`
	ProgrammaticCredentials []*ProgrammaticCredential `json:"programmatic_credentials,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *IdentityActivityMetrics) Validate() error {
	// No required string fields to validate
	return nil
}

