// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

import "fmt"

type Kernel struct {
	IsSystem bool `json:"is_system,omitempty"`
	Name string `json:"name"`
	Path string `json:"path,omitempty"`
	SystemCall string `json:"system_call,omitempty"`
	Type string `json:"type,omitempty"`
	TypeId int `json:"type_id"`
}

// Validate checks that all required fields are properly set
func (o *Kernel) Validate() error {
	if o.Name == "" {
		return fmt.Errorf("required field name is empty")
	}
	return nil
}

