// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type LdapPerson struct {
	CostCenter     string            `json:"cost_center,omitempty"`
	CreatedTime    int64             `json:"created_time,omitempty"`
	DeletedTime    int64             `json:"deleted_time,omitempty"`
	DisplayName    string            `json:"display_name,omitempty"`
	EmailAddrs     []string          `json:"email_addrs,omitempty"`
	EmployeeUid    string            `json:"employee_uid,omitempty"`
	GivenName      string            `json:"given_name,omitempty"`
	HireTime       int64             `json:"hire_time,omitempty"`
	JobTitle       string            `json:"job_title,omitempty"`
	Labels         []string          `json:"labels,omitempty"`
	LastLoginTime  int64             `json:"last_login_time,omitempty"`
	LdapCn         string            `json:"ldap_cn,omitempty"`
	LdapDn         string            `json:"ldap_dn,omitempty"`
	LeaveTime      int64             `json:"leave_time,omitempty"`
	Location       *Location         `json:"location,omitempty"`
	Manager        *User             `json:"manager,omitempty"`
	ModifiedTime   int64             `json:"modified_time,omitempty"`
	OfficeLocation string            `json:"office_location,omitempty"`
	PhoneNumber    string            `json:"phone_number,omitempty"`
	Surname        string            `json:"surname,omitempty"`
	Tags           []*KeyValueObject `json:"tags,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *LdapPerson) Validate() error {
	// No required string fields to validate
	return nil
}
