// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type OccurrenceDetails struct {
	CellName string `json:"cell_name,omitempty"`
	ColumnName string `json:"column_name,omitempty"`
	ColumnNumber int `json:"column_number,omitempty"`
	EndLine int `json:"end_line,omitempty"`
	JsonPath string `json:"json_path,omitempty"`
	PageNumber int `json:"page_number,omitempty"`
	RecordIndexInArray int `json:"record_index_in_array,omitempty"`
	RowNumber int `json:"row_number,omitempty"`
	StartLine int `json:"start_line,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *OccurrenceDetails) Validate() error {
	// No required string fields to validate
	return nil
}

