// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

import "fmt"

type Os struct {
	Build string `json:"build,omitempty"`
	Country string `json:"country,omitempty"`
	CpeName string `json:"cpe_name,omitempty"`
	CpuBits int `json:"cpu_bits,omitempty"`
	Edition string `json:"edition,omitempty"`
	KernelRelease string `json:"kernel_release,omitempty"`
	Lang string `json:"lang,omitempty"`
	Name string `json:"name"`
	SpName string `json:"sp_name,omitempty"`
	SpVer int `json:"sp_ver,omitempty"`
	Type string `json:"type,omitempty"`
	TypeId int `json:"type_id"`
	Version string `json:"version,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *Os) Validate() error {
	if o.Name == "" {
		return fmt.Errorf("required field name is empty")
	}
	return nil
}

