// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

import "fmt"

type Remediation struct {
	CisControls []*CisControl `json:"cis_controls,omitempty"`
	Desc string `json:"desc"`
	KbArticleList []*KbArticle `json:"kb_article_list,omitempty"`
	KbArticles []string `json:"kb_articles,omitempty"`
	References []string `json:"references,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *Remediation) Validate() error {
	if o.Desc == "" {
		return fmt.Errorf("required field desc is empty")
	}
	return nil
}

