// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type Reputation struct {
	BaseScore float64 `json:"base_score"`
	Provider string `json:"provider,omitempty"`
	Score string `json:"score,omitempty"`
	ScoreId int `json:"score_id"`
}

// Validate checks that all required fields are properly set
func (o *Reputation) Validate() error {
	// No required string fields to validate
	return nil
}

