// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

type Scan struct {
	Name string `json:"name"`
	Type string `json:"type,omitempty"`
	TypeId int `json:"type_id"`
	Uid string `json:"uid"`
}

// Validate checks that all required fields are properly set
func (o *Scan) Validate() error {
	// No required string fields to validate
	return nil
}

