// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package objects

import "fmt"

type StartupItem struct {
	Driver      *KernelDriver `json:"driver,omitempty"`
	Job         *Job          `json:"job,omitempty"`
	Name        string        `json:"name"`
	Process     *Process      `json:"process,omitempty"`
	RunModeIds  []int         `json:"run_mode_ids,omitempty"`
	RunModes    []string      `json:"run_modes,omitempty"`
	RunState    string        `json:"run_state,omitempty"`
	RunStateId  int           `json:"run_state_id,omitempty"`
	StartType   string        `json:"start_type,omitempty"`
	StartTypeId int           `json:"start_type_id"`
	Type        string        `json:"type,omitempty"`
	TypeId      int           `json:"type_id,omitempty"`
}

// Validate checks that all required fields are properly set
func (o *StartupItem) Validate() error {
	if o.Name == "" {
		return fmt.Errorf("required field name is empty")
	}
	return nil
}
