// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package application

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
)

// Application Error - Application Error events describe issues with an applications. The error message should be put in the event's <code>message</code> attribute. The <code>metadata.product</code> attribute can be used to capture the originating application information. The <code>host</code> profile can used to include the generating device information. This class is helpful for applications that generate or handle OCSF events and can also be used for errors in upstream products and services.
// OCSF Class UID: 6008
//
// This is a generated struct representing the OCSF event class.
type ApplicationError struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	// The error message as reported by the application.
	Message string `json:"message"`
}

// Activity IDs for Application Error
const (
	ApplicationErrorActivityGeneralError = 1 // The application has experienced an error.
	ApplicationErrorActivityTranslationError = 2 // The application has experienced an error translating (mapping) a raw event to OCSF. Including the original raw event in the raw_data field is highly recommended.
)

// NewApplicationError creates a new Application Error event
func NewApplicationError(activityID int) *ApplicationError {
	return &ApplicationError{
		Event: ocsf.Event{
			CategoryUID: 6,
			ClassUID:    6008,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(6, 6008, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "application",
			Class:       "application_error",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

