// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package application

import (
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
	"time"
)

type DatastoreActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Actor        *objects.Actor           `json:"actor"`
	Database     *objects.Database        `json:"database,omitempty"`
	Databucket   *objects.Databucket      `json:"databucket,omitempty"`
	DstEndpoint  *objects.NetworkEndpoint `json:"dst_endpoint,omitempty"`
	HttpRequest  *objects.HttpRequest     `json:"http_request,omitempty"`
	HttpResponse *objects.HttpResponse    `json:"http_response,omitempty"`
	QueryInfo    *objects.QueryInfo       `json:"query_info,omitempty"`
	SrcEndpoint  *objects.NetworkEndpoint `json:"src_endpoint"`
	Table        *objects.Table           `json:"table,omitempty"`
	Type         string                   `json:"type,omitempty"`
	TypeId       int                      `json:"type_id,omitempty"`
}

const (
	DatastoreActivityActivityRead    = 1
	DatastoreActivityActivityDecrypt = 10
	DatastoreActivityActivityUpdate  = 2
	DatastoreActivityActivityConnect = 3
	DatastoreActivityActivityQuery   = 4
	DatastoreActivityActivityWrite   = 5
	DatastoreActivityActivityCreate  = 6
	DatastoreActivityActivityDelete  = 7
	DatastoreActivityActivityList    = 8
	DatastoreActivityActivityEncrypt = 9
)

func NewDatastoreActivity(activityID int) *DatastoreActivity {
	return &DatastoreActivity{
		Event: ocsf.Event{
			CategoryUID: 6,
			ClassUID:    6005,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(6, 6005, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "application",
			Class:       "datastore_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

// Validate checks that all required fields are properly set
func (e *DatastoreActivity) Validate() error {
	// No required string fields to validate
	return nil
}
