// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package application

import (
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
	"time"
)

type ScanActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	CommandUid       string          `json:"command_uid,omitempty"`
	Duration         int64           `json:"duration,omitempty"`
	EndTime          int64           `json:"end_time,omitempty"`
	NumDetections    int             `json:"num_detections,omitempty"`
	NumFiles         int             `json:"num_files,omitempty"`
	NumFolders       int             `json:"num_folders,omitempty"`
	NumNetworkItems  int             `json:"num_network_items,omitempty"`
	NumProcesses     int             `json:"num_processes,omitempty"`
	NumRegistryItems int             `json:"num_registry_items,omitempty"`
	NumResolutions   int             `json:"num_resolutions,omitempty"`
	NumSkippedItems  int             `json:"num_skipped_items,omitempty"`
	NumTrustedItems  int             `json:"num_trusted_items,omitempty"`
	Policy           *objects.Policy `json:"policy,omitempty"`
	Scan             *objects.Scan   `json:"scan"`
	ScheduleUid      string          `json:"schedule_uid,omitempty"`
	StartTime        int64           `json:"start_time,omitempty"`
	Total            int             `json:"total,omitempty"`
}

const (
	ScanActivityActivityStarted           = 1
	ScanActivityActivityDelayed           = 10
	ScanActivityActivityCompleted         = 2
	ScanActivityActivityCancelled         = 3
	ScanActivityActivityDurationViolation = 4
	ScanActivityActivityPauseViolation    = 5
	ScanActivityActivityError             = 6
	ScanActivityActivityPaused            = 7
	ScanActivityActivityResumed           = 8
	ScanActivityActivityRestarted         = 9
)

func NewScanActivity(activityID int) *ScanActivity {
	return &ScanActivity{
		Event: ocsf.Event{
			CategoryUID: 6,
			ClassUID:    6007,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(6, 6007, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "application",
			Class:       "scan_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

// Validate checks that all required fields are properly set
func (e *ScanActivity) Validate() error {
	// No required string fields to validate
	return nil
}
