// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package application

import (
	"fmt"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
	"time"
)

type WebResourcesActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	DstEndpoint        *objects.NetworkEndpoint `json:"dst_endpoint,omitempty"`
	HttpRequest        *objects.HttpRequest     `json:"http_request,omitempty"`
	HttpResponse       *objects.HttpResponse    `json:"http_response,omitempty"`
	SrcEndpoint        *objects.NetworkEndpoint `json:"src_endpoint,omitempty"`
	Tls                *objects.Tls             `json:"tls,omitempty"`
	WebResources       []*objects.WebResource   `json:"web_resources"`
	WebResourcesResult []*objects.WebResource   `json:"web_resources_result,omitempty"`
}

const (
	WebResourcesActivityActivityCreate = 1
	WebResourcesActivityActivityRead   = 2
	WebResourcesActivityActivityUpdate = 3
	WebResourcesActivityActivityDelete = 4
	WebResourcesActivityActivitySearch = 5
	WebResourcesActivityActivityImport = 6
	WebResourcesActivityActivityExport = 7
	WebResourcesActivityActivityShare  = 8
)

func NewWebResourcesActivity(activityID int) *WebResourcesActivity {
	return &WebResourcesActivity{
		Event: ocsf.Event{
			CategoryUID: 6,
			ClassUID:    6001,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(6, 6001, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "application",
			Class:       "web_resources_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

// Validate checks that all required fields are properly set
func (e *WebResourcesActivity) Validate() error {
	// No required string fields to validate
	return nil
}
