// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package application

import (
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
	"time"
)

type WebResourceAccessActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	HttpRequest  *objects.HttpRequest     `json:"http_request"`
	HttpResponse *objects.HttpResponse    `json:"http_response,omitempty"`
	Proxy        *objects.NetworkProxy    `json:"proxy,omitempty"`
	SrcEndpoint  *objects.NetworkEndpoint `json:"src_endpoint,omitempty"`
	Tls          *objects.Tls             `json:"tls,omitempty"`
	WebResources []*objects.WebResource   `json:"web_resources"`
}

const (
	WebResourceAccessActivityActivityAccessGrant  = 1
	WebResourceAccessActivityActivityAccessDeny   = 2
	WebResourceAccessActivityActivityAccessRevoke = 3
	WebResourceAccessActivityActivityAccessError  = 4
)

func NewWebResourceAccessActivity(activityID int) *WebResourceAccessActivity {
	return &WebResourceAccessActivity{
		Event: ocsf.Event{
			CategoryUID: 6,
			ClassUID:    6004,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(6, 6004, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "application",
			Class:       "web_resource_access_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}
