// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package unmanned_systems

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/common/ocsf"
	"github.com/telhawk-systems/telhawk-stack/common/ocsf/objects"
)

type DroneFlightsActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	AuthProtocol string `json:"auth_protocol,omitempty"`
	AuthProtocolId int `json:"auth_protocol_id,omitempty"`
	Classification string `json:"classification,omitempty"`
	Comment string `json:"comment,omitempty"`
	ProtocolName string `json:"protocol_name,omitempty"`
	SrcEndpoint *objects.NetworkEndpoint `json:"src_endpoint,omitempty"`
	Traffic *objects.NetworkTraffic `json:"traffic,omitempty"`
	UnmannedAerialSystem *objects.UnmannedAerialSystem `json:"unmanned_aerial_system"`
	UnmannedSystemOperatingArea *objects.UnmannedSystemOperatingArea `json:"unmanned_system_operating_area,omitempty"`
	UnmannedSystemOperator *objects.User `json:"unmanned_system_operator"`
}

const (
	DroneFlightsActivityActivityUnknown = 0
	DroneFlightsActivityActivityCapture = 1
	DroneFlightsActivityActivityRecord = 2
	DroneFlightsActivityActivityOther = 99
)

func NewDroneFlightsActivity(activityID int) *DroneFlightsActivity {
	return &DroneFlightsActivity{
		Event: ocsf.Event{
			CategoryUID: 8,
			ClassUID:    8001,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(8, 8001, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "unmanned_systems",
			Class:       "drone_flights_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

// Validate checks that all required fields are properly set
func (e *DroneFlightsActivity) Validate() error {
	// No required string fields to validate
	return nil
}

