// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package discovery

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Cloud Resources Inventory Info - Cloud Resources Inventory Info events report cloud asset inventory data. This data can be either logged or proactively collected. For example, use this event class when creating an inventory of cloud resource information from a Configuration Management Database (CMDB), Cyber Asset Attack Surface Management (CAASM), direct public cloud service provider APIs, Software-as-a-Service (SaaS) APIs, or otherwise.
// OCSF Class UID: 5023
//
// This is a generated struct representing the OCSF event class.
type CloudResourcesInventoryInfo struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	// Cloud service provider or SaaS platform metadata about the cloud resource(s) that are being discovered by an inventory process.
	Cloud *objects.Cloud `json:"cloud,omitempty"`
	// A cloud-based container image or running container discovered by an inventory process.
	Container *objects.Container `json:"container,omitempty"`
	// A cloud-based database discovered by an inventory process.
	Database *objects.Database `json:"database,omitempty"`
	// A cloud-based data bucket or other object storage discovered by an inventory process.
	Databucket *objects.Databucket `json:"databucket,omitempty"`
	// The Identity Provider that is being discovered by an inventory process, or that is related to the cloud resource(s) being discovered by an inventory process.
	Idp *objects.Idp `json:"idp,omitempty"`
	// The cloud region where the resource is located, e.g., `us-isof-south-1`, `eastus2`, `us-central1`, etc.
	Region string `json:"region,omitempty"`
	// The cloud resource(s) that are being discovered by an inventory process. Use this object if there is not a direct object match in the class.
	Resources []*objects.ResourceDetails `json:"resources,omitempty"`
	// A cloud-based database table discovered by an inventory process.
	Table *objects.Table `json:"table,omitempty"`
}

// NewCloudResourcesInventoryInfo creates a new Cloud Resources Inventory Info event
func NewCloudResourcesInventoryInfo(activityID int) *CloudResourcesInventoryInfo {
	return &CloudResourcesInventoryInfo{
		Event: ocsf.Event{
			CategoryUID: 5,
			ClassUID:    5023,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(5, 5023, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "discovery",
			Class:       "cloud_resources_inventory_info",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

