// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package discovery

import (
	"fmt"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
	"time"
)

type CloudResourcesInventoryInfo struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Cloud      *objects.Cloud             `json:"cloud,omitempty"`
	Container  *objects.Container         `json:"container,omitempty"`
	Database   *objects.Database          `json:"database,omitempty"`
	Databucket *objects.Databucket        `json:"databucket,omitempty"`
	Idp        *objects.Idp               `json:"idp,omitempty"`
	Region     string                     `json:"region,omitempty"`
	Resources  []*objects.ResourceDetails `json:"resources,omitempty"`
	Table      *objects.Table             `json:"table,omitempty"`
}

func NewCloudResourcesInventoryInfo(activityID int) *CloudResourcesInventoryInfo {
	return &CloudResourcesInventoryInfo{
		Event: ocsf.Event{
			CategoryUID: 5,
			ClassUID:    5023,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(5, 5023, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "discovery",
			Class:       "cloud_resources_inventory_info",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

// Validate checks that all required fields are properly set
func (e *CloudResourcesInventoryInfo) Validate() error {
	// No required string fields to validate
	return nil
}
