// Code generated by ocsf-generator. DO NOT EDIT.

package discovery

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Device Config State - Device Config State events report device configuration data, device assessments, and/or CIS Benchmark results.
// OCSF Class UID: 5002
//
// This is a generated struct representing the OCSF event class.
type ConfigState struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Actor *objects.Actor `json:"actor,omitempty"`
	// A list of assessments associated with the device.
	Assessments []*objects.Assessment `json:"assessments,omitempty"`
	CisBenchmarkResult *objects.CisBenchmarkResult `json:"cis_benchmark_result,omitempty"`
	// The device that is being discovered by an inventory process.
	Device *objects.Device `json:"device"`
}

// NewConfigState creates a new Device Config State event
func NewConfigState(activityID int) *ConfigState {
	return &ConfigState{
		Event: ocsf.Event{
			CategoryUID: 5,
			ClassUID:    5002,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(5, 5002, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "discovery",
			Class:       "config_state",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

