// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package discovery

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Device Config State Change - Device Config State Change events report state changes that impact the security of the device.
// OCSF Class UID: 5019
//
// This is a generated struct representing the OCSF event class.
type DeviceConfigStateChange struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Actor *objects.Actor `json:"actor,omitempty"`
	// The device that is impacted by the state change.
	Device *objects.Device `json:"device"`
	PrevSecurityLevel string `json:"prev_security_level,omitempty"`
	PrevSecurityLevelId int `json:"prev_security_level_id,omitempty"`
	// The previous security states of the device.
	PrevSecurityStates []*objects.SecurityState `json:"prev_security_states,omitempty"`
	SecurityLevel string `json:"security_level,omitempty"`
	SecurityLevelId int `json:"security_level_id,omitempty"`
	// The current security states of the device.
	SecurityStates []*objects.SecurityState `json:"security_states,omitempty"`
	// The Config Change Stat, normalized to the caption of the state_id value. In the case of 'Other', it is defined by the source.
	State string `json:"state,omitempty"`
	// The Config Change State of the managed entity.
	StateId int `json:"state_id,omitempty"`
}

// NewDeviceConfigStateChange creates a new Device Config State Change event
func NewDeviceConfigStateChange(activityID int) *DeviceConfigStateChange {
	return &DeviceConfigStateChange{
		Event: ocsf.Event{
			CategoryUID: 5,
			ClassUID:    5019,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(5, 5019, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "discovery",
			Class:       "device_config_state_change",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

