// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package discovery

import (
	"fmt"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
	"time"
)

type EvidenceInfo struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Device        *objects.Device        `json:"device"`
	QueryEvidence *objects.QueryEvidence `json:"query_evidence"`
}

func NewEvidenceInfo(activityID int) *EvidenceInfo {
	return &EvidenceInfo{
		Event: ocsf.Event{
			CategoryUID: 5,
			ClassUID:    5040,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(5, 5040, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "discovery",
			Class:       "evidence_info",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

// Validate checks that all required fields are properly set
func (e *EvidenceInfo) Validate() error {
	// No required string fields to validate
	return nil
}
