// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package discovery

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Device Inventory Info - Device Inventory Info events report device inventory data that is either logged or proactively collected. For example, when collecting device information from a CMDB or running a network sweep of connected devices.
// OCSF Class UID: 5001
//
// This is a generated struct representing the OCSF event class.
type InventoryInfo struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Actor *objects.Actor `json:"actor,omitempty"`
	// The device that is being discovered by an inventory process.
	Device *objects.Device `json:"device"`
}

// NewInventoryInfo creates a new Device Inventory Info event
func NewInventoryInfo(activityID int) *InventoryInfo {
	return &InventoryInfo{
		Event: ocsf.Event{
			CategoryUID: 5,
			ClassUID:    5001,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(5, 5001, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "discovery",
			Class:       "inventory_info",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

