// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package discovery

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Kernel Object Query - Kernel Object Query events report information about discovered kernel resources.
// OCSF Class UID: 5006
//
// This is a generated struct representing the OCSF event class.
type KernelObjectQuery struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	// The kernel object that pertains to the event.
	Kernel *objects.Kernel `json:"kernel"`
}

// NewKernelObjectQuery creates a new Kernel Object Query event
func NewKernelObjectQuery(activityID int) *KernelObjectQuery {
	return &KernelObjectQuery{
		Event: ocsf.Event{
			CategoryUID: 5,
			ClassUID:    5006,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(5, 5006, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "discovery",
			Class:       "kernel_object_query",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

