// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package discovery

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Module Query - Module Query events report information about loaded modules.
// OCSF Class UID: 5011
//
// This is a generated struct representing the OCSF event class.
type ModuleQuery struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Module *objects.Module `json:"module"`
	// The process that loaded the module.
	Process *objects.Process `json:"process"`
}

// NewModuleQuery creates a new Module Query event
func NewModuleQuery(activityID int) *ModuleQuery {
	return &ModuleQuery{
		Event: ocsf.Event{
			CategoryUID: 5,
			ClassUID:    5011,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(5, 5011, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "discovery",
			Class:       "module_query",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

