// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package discovery

import (
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
	"time"
)

type ModuleQuery struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Module  *objects.Module  `json:"module"`
	Process *objects.Process `json:"process"`
}

func NewModuleQuery(activityID int) *ModuleQuery {
	return &ModuleQuery{
		Event: ocsf.Event{
			CategoryUID: 5,
			ClassUID:    5011,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(5, 5011, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "discovery",
			Class:       "module_query",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

// Validate checks that all required fields are properly set
func (e *ModuleQuery) Validate() error {
	// No required string fields to validate
	return nil
}
