// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package discovery

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Network Connection Query - Network Connection Query events report information about active network connections.
// OCSF Class UID: 5012
//
// This is a generated struct representing the OCSF event class.
type NetworkConnectionQuery struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	ConnectionInfo *objects.NetworkConnectionInfo `json:"connection_info"`
	// The process that owns the socket.
	Process *objects.Process `json:"process"`
	// The state of the socket, normalized to the caption of the state_id value. In the case of 'Other', it is defined by the event source.
	State string `json:"state,omitempty"`
	// The state of the socket.
	StateId int `json:"state_id"`
}

// NewNetworkConnectionQuery creates a new Network Connection Query event
func NewNetworkConnectionQuery(activityID int) *NetworkConnectionQuery {
	return &NetworkConnectionQuery{
		Event: ocsf.Event{
			CategoryUID: 5,
			ClassUID:    5012,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(5, 5012, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "discovery",
			Class:       "network_connection_query",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

