// Code generated by ocsf-generator. DO NOT EDIT.

package discovery

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Service Query - Service Query events report information about running services.
// OCSF Class UID: 5016
//
// This is a generated struct representing the OCSF event class.
type ServiceQuery struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Service *objects.Service `json:"service"`
}

// NewServiceQuery creates a new Service Query event
func NewServiceQuery(activityID int) *ServiceQuery {
	return &ServiceQuery{
		Event: ocsf.Event{
			CategoryUID: 5,
			ClassUID:    5016,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(5, 5016, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "discovery",
			Class:       "service_query",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

