// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package discovery

import (
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
	"time"
)

type SessionQuery struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Session *objects.Session `json:"session"`
}

func NewSessionQuery(activityID int) *SessionQuery {
	return &SessionQuery{
		Event: ocsf.Event{
			CategoryUID: 5,
			ClassUID:    5017,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(5, 5017, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "discovery",
			Class:       "session_query",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}
