// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package discovery

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Software Inventory Info - Software Inventory Info events report device software inventory data that is either logged or proactively collected. For example, when collecting device information from a CMDB or running a network sweep of connected devices.
// OCSF Class UID: 5020
//
// This is a generated struct representing the OCSF event class.
type SoftwareInfo struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Actor *objects.Actor `json:"actor,omitempty"`
	// The device that is being discovered by an inventory process.
	Device *objects.Device `json:"device"`
	// The device software that is being discovered by an inventory process.
	Package *objects.Package `json:"package,omitempty"`
	// Additional product attributes that have been discovered or enriched from a catalog or other external source.
	Product *objects.Product `json:"product,omitempty"`
	// The Software Bill of Materials (SBOM) of the device software that is being discovered by an inventory process.
	Sbom *objects.Sbom `json:"sbom,omitempty"`
}

// NewSoftwareInfo creates a new Software Inventory Info event
func NewSoftwareInfo(activityID int) *SoftwareInfo {
	return &SoftwareInfo{
		Event: ocsf.Event{
			CategoryUID: 5,
			ClassUID:    5020,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(5, 5020, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "discovery",
			Class:       "software_info",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

