// Code generated by ocsf-generator. DO NOT EDIT.

package discovery

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// User Inventory Info - User Inventory Info events report user inventory data that is either logged or proactively collected. For example, when collecting user information from Active Directory entries.
// OCSF Class UID: 5003
//
// This is a generated struct representing the OCSF event class.
type UserInventory struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	// The actor describes the process that was the source of the inventory activity. In the case of user inventory data, that could be a particular process or script that is run to scrape the user data. For example, it could be a powershell process that runs to pull data from the Azure AD graph API.
	Actor *objects.Actor `json:"actor,omitempty"`
	// The user that is being discovered by an inventory process.
	User *objects.User `json:"user"`
}

// NewUserInventory creates a new User Inventory Info event
func NewUserInventory(activityID int) *UserInventory {
	return &UserInventory{
		Event: ocsf.Event{
			CategoryUID: 5,
			ClassUID:    5003,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(5, 5003, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "discovery",
			Class:       "user_inventory",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

