// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package discovery

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// User Query - User Query events report user data that have been discovered, queried, polled or searched. This event differs from User Inventory as it describes the result of a targeted search by filtering a subset of user attributes.
// OCSF Class UID: 5018
//
// This is a generated struct representing the OCSF event class.
type UserQuery struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	User *objects.User `json:"user"`
}

// NewUserQuery creates a new User Query event
func NewUserQuery(activityID int) *UserQuery {
	return &UserQuery{
		Event: ocsf.Event{
			CategoryUID: 5,
			ClassUID:    5018,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(5, 5018, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "discovery",
			Class:       "user_query",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

