// Code generated by ocsf-generator. DO NOT EDIT.

package ocsf

// CategoryName returns the human-readable category name from category_uid.
func CategoryName(categoryUID int) string {
	switch categoryUID {
	case 6:
		return "Application Activity"
	case 5:
		return "Discovery"
	case 2:
		return "Findings"
	case 3:
		return "Identity & Access Management"
	case 4:
		return "Network Activity"
	case 7:
		return "Remediation"
	case 1:
		return "System Activity"
	case 8:
		return "Unmanned Systems"
	default:
		return "Unknown"
	}
}

// ClassName returns the human-readable class name from class_uid.
func ClassName(classUID int) string {
	switch classUID {
	case 1001:
		return "File System Activity"
	case 1002:
		return "Kernel Extension Activity"
	case 1003:
		return "Kernel Activity"
	case 1004:
		return "Memory Activity"
	case 1005:
		return "Module Activity"
	case 1006:
		return "Scheduled Job Activity"
	case 1007:
		return "Process Activity"
	case 1008:
		return "Event Log Activity"
	case 1009:
		return "Script Activity"
	case 1010:
		return "Peripheral Activity"
	case 2000:
		return "Finding"
	case 2001:
		return "Security Finding"
	case 2002:
		return "Vulnerability Finding"
	case 2003:
		return "Compliance Finding"
	case 2004:
		return "Detection Finding"
	case 2005:
		return "Incident Finding"
	case 2006:
		return "Data Security Finding"
	case 2007:
		return "Application Security Posture Finding"
	case 2008:
		return "IAM Analysis Finding"
	case 3001:
		return "Account Change"
	case 3002:
		return "Authentication"
	case 3003:
		return "Authorize Session"
	case 3004:
		return "Entity Management"
	case 3005:
		return "User Access Management"
	case 3006:
		return "Group Management"
	case 4001:
		return "Network Activity"
	case 4002:
		return "HTTP Activity"
	case 4003:
		return "DNS Activity"
	case 4004:
		return "DHCP Activity"
	case 4005:
		return "RDP Activity"
	case 4006:
		return "SMB Activity"
	case 4007:
		return "SSH Activity"
	case 4008:
		return "FTP Activity"
	case 4009:
		return "Email Activity"
	case 4010:
		return "Network File Activity"
	case 4011:
		return "Email File Activity"
	case 4012:
		return "Email URL Activity"
	case 4013:
		return "NTP Activity"
	case 4014:
		return "Tunnel Activity"
	case 5000:
		return "Discovery Result"
	case 5001:
		return "Device Inventory Info"
	case 5002:
		return "Device Config State"
	case 5003:
		return "User Inventory Info"
	case 5004:
		return "Operating System Patch State"
	case 5006:
		return "Kernel Object Query"
	case 5007:
		return "File Query"
	case 5008:
		return "Folder Query"
	case 5009:
		return "Admin Group Query"
	case 5010:
		return "Job Query"
	case 5011:
		return "Module Query"
	case 5012:
		return "Network Connection Query"
	case 5013:
		return "Networks Query"
	case 5014:
		return "Peripheral Device Query"
	case 5015:
		return "Process Query"
	case 5016:
		return "Service Query"
	case 5017:
		return "User Session Query"
	case 5018:
		return "User Query"
	case 5019:
		return "Device Config State Change"
	case 5020:
		return "Software Inventory Info"
	case 5021:
		return "OSINT Inventory Info"
	case 5022:
		return "Startup Item Query"
	case 5023:
		return "Cloud Resources Inventory Info"
	case 5040:
		return "Live Evidence Info"
	case 6001:
		return "Web Resources Activity"
	case 6002:
		return "Application Lifecycle"
	case 6003:
		return "API Activity"
	case 6004:
		return "Web Resource Access Activity"
	case 6005:
		return "Datastore Activity"
	case 6006:
		return "File Hosting Activity"
	case 6007:
		return "Scan Activity"
	case 6008:
		return "Application Error"
	case 7001:
		return "Remediation Activity"
	case 7002:
		return "File Remediation Activity"
	case 7003:
		return "Process Remediation Activity"
	case 7004:
		return "Network Remediation Activity"
	case 8001:
		return "Drone Flights Activity"
	case 8002:
		return "Airborne Broadcast Activity"
	default:
		return "Unknown"
	}
}

// ActivityName returns the human-readable activity name from class_uid and activity_id.
func ActivityName(classUID int, activityID int) string {
	// Format: class_uid * 100 + activity_id for lookup key
	key := classUID*100 + activityID
	switch key {
	case 100101:
		return "Create"
	case 100102:
		return "Read"
	case 100103:
		return "Update"
	case 100104:
		return "Delete"
	case 100105:
		return "Rename"
	case 100106:
		return "Set Attributes"
	case 100107:
		return "Set Security"
	case 100108:
		return "Get Attributes"
	case 100109:
		return "Get Security"
	case 100110:
		return "Encrypt"
	case 100111:
		return "Decrypt"
	case 100112:
		return "Mount"
	case 100113:
		return "Unmount"
	case 100114:
		return "Open"
	case 100201:
		return "Load"
	case 100202:
		return "Unload"
	case 100301:
		return "Create"
	case 100302:
		return "Read"
	case 100303:
		return "Delete"
	case 100304:
		return "Invoke"
	case 100401:
		return "Allocate Page"
	case 100402:
		return "Modify Page"
	case 100403:
		return "Delete Page"
	case 100404:
		return "Buffer Overflow"
	case 100405:
		return "Disable DEP"
	case 100406:
		return "Enable DEP"
	case 100407:
		return "Read"
	case 100408:
		return "Write"
	case 100409:
		return "Map View"
	case 100501:
		return "Load"
	case 100502:
		return "Unload"
	case 100503:
		return "Invoke"
	case 100601:
		return "Create"
	case 100602:
		return "Update"
	case 100603:
		return "Delete"
	case 100604:
		return "Enable"
	case 100605:
		return "Disable"
	case 100606:
		return "Start"
	case 100701:
		return "Launch"
	case 100702:
		return "Terminate"
	case 100703:
		return "Open"
	case 100704:
		return "Inject"
	case 100705:
		return "Set User ID"
	case 100801:
		return "Clear"
	case 100802:
		return "Delete"
	case 100803:
		return "Export"
	case 100804:
		return "Archive"
	case 100805:
		return "Rotate"
	case 100806:
		return "Start"
	case 100807:
		return "Stop"
	case 100808:
		return "Restart"
	case 100809:
		return "Enable"
	case 100810:
		return "Disable"
	case 100901:
		return "Execute"
	case 101001:
		return "Connect"
	case 101002:
		return "Disconnect"
	case 101003:
		return "Enable"
	case 101004:
		return "Disable"
	case 101005:
		return "Eject"
	case 200001:
		return "Create"
	case 200002:
		return "Update"
	case 200003:
		return "Close"
	case 200101:
		return "Create"
	case 200102:
		return "Update"
	case 200103:
		return "Close"
	case 200501:
		return "Create"
	case 200502:
		return "Update"
	case 200503:
		return "Close"
	case 200601:
		return "Create"
	case 200602:
		return "Update"
	case 200603:
		return "Close"
	case 200604:
		return "Suppressed"
	case 300101:
		return "Create"
	case 300102:
		return "Enable"
	case 300103:
		return "Password Change"
	case 300104:
		return "Password Reset"
	case 300105:
		return "Disable"
	case 300106:
		return "Delete"
	case 300107:
		return "Attach Policy"
	case 300108:
		return "Detach Policy"
	case 300109:
		return "Lock"
	case 300110:
		return "MFA Factor Enable"
	case 300111:
		return "MFA Factor Disable"
	case 300112:
		return "Unlock"
	case 300201:
		return "Logon"
	case 300202:
		return "Logoff"
	case 300203:
		return "Authentication Ticket"
	case 300204:
		return "Service Ticket Request"
	case 300205:
		return "Service Ticket Renew"
	case 300206:
		return "Preauth"
	case 300207:
		return "Account Switch"
	case 300301:
		return "Assign Privileges"
	case 300302:
		return "Assign Groups"
	case 300401:
		return "Create"
	case 300402:
		return "Read"
	case 300403:
		return "Update"
	case 300404:
		return "Delete"
	case 300405:
		return "Move"
	case 300406:
		return "Enroll"
	case 300407:
		return "Unenroll"
	case 300408:
		return "Enable"
	case 300409:
		return "Disable"
	case 300410:
		return "Activate"
	case 300411:
		return "Deactivate"
	case 300412:
		return "Suspend"
	case 300413:
		return "Resume"
	case 300501:
		return "Assign Privileges"
	case 300502:
		return "Revoke Privileges"
	case 300601:
		return "Assign Privileges"
	case 300602:
		return "Revoke Privileges"
	case 300603:
		return "Add User"
	case 300604:
		return "Remove User"
	case 300605:
		return "Delete"
	case 300606:
		return "Create"
	case 300607:
		return "Add Subgroup"
	case 300608:
		return "Remove Subgroup"
	case 400101:
		return "Open"
	case 400102:
		return "Close"
	case 400103:
		return "Reset"
	case 400104:
		return "Fail"
	case 400105:
		return "Refuse"
	case 400106:
		return "Traffic"
	case 400107:
		return "Listen"
	case 400201:
		return "Connect"
	case 400202:
		return "Delete"
	case 400203:
		return "Get"
	case 400204:
		return "Head"
	case 400205:
		return "Options"
	case 400206:
		return "Post"
	case 400207:
		return "Put"
	case 400208:
		return "Trace"
	case 400209:
		return "Patch"
	case 400301:
		return "Query"
	case 400302:
		return "Response"
	case 400306:
		return "Traffic"
	case 400401:
		return "Discover"
	case 400402:
		return "Offer"
	case 400403:
		return "Request"
	case 400404:
		return "Decline"
	case 400405:
		return "Ack"
	case 400406:
		return "Nak"
	case 400407:
		return "Release"
	case 400408:
		return "Inform"
	case 400409:
		return "Expire"
	case 400501:
		return "Initial Request"
	case 400502:
		return "Initial Response"
	case 400503:
		return "Connect Request"
	case 400504:
		return "Connect Response"
	case 400505:
		return "TLS Handshake"
	case 400506:
		return "Traffic"
	case 400507:
		return "Disconnect"
	case 400508:
		return "Reconnect"
	case 400601:
		return "File Supersede"
	case 400602:
		return "File Open"
	case 400603:
		return "File Create"
	case 400604:
		return "File Open If"
	case 400605:
		return "File Overwrite"
	case 400606:
		return "File Overwrite If"
	case 400701:
		return "Open"
	case 400702:
		return "Close"
	case 400703:
		return "Reset"
	case 400704:
		return "Fail"
	case 400705:
		return "Refuse"
	case 400706:
		return "Traffic"
	case 400707:
		return "Listen"
	case 400801:
		return "Put"
	case 400802:
		return "Get"
	case 400803:
		return "Poll"
	case 400804:
		return "Delete"
	case 400805:
		return "Rename"
	case 400806:
		return "List"
	case 400901:
		return "Send"
	case 400902:
		return "Receive"
	case 400903:
		return "Scan"
	case 400904:
		return "Trace"
	case 400905:
		return "MTA Relay"
	case 401001:
		return "Upload"
	case 401002:
		return "Download"
	case 401003:
		return "Update"
	case 401004:
		return "Delete"
	case 401005:
		return "Rename"
	case 401006:
		return "Copy"
	case 401007:
		return "Move"
	case 401008:
		return "Restore"
	case 401009:
		return "Preview"
	case 401010:
		return "Lock"
	case 401011:
		return "Unlock"
	case 401012:
		return "Share"
	case 401013:
		return "Unshare"
	case 401014:
		return "Open"
	case 401015:
		return "Sync"
	case 401016:
		return "Unsync"
	case 401101:
		return "Send"
	case 401102:
		return "Receive"
	case 401103:
		return "Scan"
	case 401201:
		return "Send"
	case 401202:
		return "Receive"
	case 401203:
		return "Scan"
	case 401300:
		return "Unknown"
	case 401301:
		return "Symmetric Active Exchange"
	case 401302:
		return "Symmetric Passive Response"
	case 401303:
		return "Client Synchronization"
	case 401304:
		return "Server Response"
	case 401305:
		return "Broadcast"
	case 401306:
		return "Control"
	case 401307:
		return "Private Use Case"
	case 401399:
		return "Other"
	case 401400:
		return "Unknown"
	case 401401:
		return "Open"
	case 401402:
		return "Close"
	case 401403:
		return "Renew"
	case 401499:
		return "Other"
	case 500001:
		return "Query"
	case 600101:
		return "Create"
	case 600102:
		return "Read"
	case 600103:
		return "Update"
	case 600104:
		return "Delete"
	case 600105:
		return "Search"
	case 600106:
		return "Import"
	case 600107:
		return "Export"
	case 600108:
		return "Share"
	case 600201:
		return "Install"
	case 600202:
		return "Remove"
	case 600203:
		return "Start"
	case 600204:
		return "Stop"
	case 600205:
		return "Restart"
	case 600206:
		return "Enable"
	case 600207:
		return "Disable"
	case 600208:
		return "Update"
	case 600301:
		return "Create"
	case 600302:
		return "Read"
	case 600303:
		return "Update"
	case 600304:
		return "Delete"
	case 600401:
		return "Access Grant"
	case 600402:
		return "Access Deny"
	case 600403:
		return "Access Revoke"
	case 600404:
		return "Access Error"
	case 600501:
		return "Read"
	case 600502:
		return "Update"
	case 600503:
		return "Connect"
	case 600504:
		return "Query"
	case 600505:
		return "Write"
	case 600506:
		return "Create"
	case 600507:
		return "Delete"
	case 600508:
		return "List"
	case 600509:
		return "Encrypt"
	case 600510:
		return "Decrypt"
	case 600601:
		return "Upload"
	case 600602:
		return "Download"
	case 600603:
		return "Update"
	case 600604:
		return "Delete"
	case 600605:
		return "Rename"
	case 600606:
		return "Copy"
	case 600607:
		return "Move"
	case 600608:
		return "Restore"
	case 600609:
		return "Preview"
	case 600610:
		return "Lock"
	case 600611:
		return "Unlock"
	case 600612:
		return "Share"
	case 600613:
		return "Unshare"
	case 600614:
		return "Open"
	case 600615:
		return "Sync"
	case 600616:
		return "Unsync"
	case 600617:
		return "Access Check"
	case 600701:
		return "Started"
	case 600702:
		return "Completed"
	case 600703:
		return "Cancelled"
	case 600704:
		return "Duration Violation"
	case 600705:
		return "Pause Violation"
	case 600706:
		return "Error"
	case 600707:
		return "Paused"
	case 600708:
		return "Resumed"
	case 600709:
		return "Restarted"
	case 600710:
		return "Delayed"
	case 600801:
		return "General Error"
	case 600802:
		return "Translation Error"
	case 700101:
		return "Isolate"
	case 700102:
		return "Evict"
	case 700103:
		return "Restore"
	case 700104:
		return "Harden"
	case 700105:
		return "Detect"
	case 800100:
		return "Unknown"
	case 800101:
		return "Capture"
	case 800102:
		return "Record"
	case 800199:
		return "Other"
	case 800200:
		return "Unknown"
	case 800201:
		return "Capture"
	case 800202:
		return "Record"
	case 800299:
		return "Other"
	default:
		return ""
	}
}
