// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package network

import (
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
	"time"
)

type DhcpActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	DstEndpoint    *objects.NetworkEndpoint  `json:"dst_endpoint,omitempty"`
	IsRenewal      bool                      `json:"is_renewal,omitempty"`
	LeaseDur       int                       `json:"lease_dur,omitempty"`
	Relay          *objects.NetworkInterface `json:"relay,omitempty"`
	SrcEndpoint    *objects.NetworkEndpoint  `json:"src_endpoint,omitempty"`
	TransactionUid string                    `json:"transaction_uid,omitempty"`
}

const (
	DhcpActivityActivityDiscover = 1
	DhcpActivityActivityOffer    = 2
	DhcpActivityActivityRequest  = 3
	DhcpActivityActivityDecline  = 4
	DhcpActivityActivityAck      = 5
	DhcpActivityActivityNak      = 6
	DhcpActivityActivityRelease  = 7
	DhcpActivityActivityInform   = 8
	DhcpActivityActivityExpire   = 9
)

func NewDhcpActivity(activityID int) *DhcpActivity {
	return &DhcpActivity{
		Event: ocsf.Event{
			CategoryUID: 4,
			ClassUID:    4004,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(4, 4004, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "network",
			Class:       "dhcp_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}
