// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package network

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// DNS Activity - DNS Activity events report DNS queries and answers as seen on the network.
// OCSF Class UID: 4003
//
// This is a generated struct representing the OCSF event class.
type DnsActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Answers []*objects.DnsAnswer `json:"answers,omitempty"`
	ConnectionInfo *objects.NetworkConnectionInfo `json:"connection_info,omitempty"`
	DstEndpoint *objects.NetworkEndpoint `json:"dst_endpoint,omitempty"`
	Query *objects.DnsQuery `json:"query,omitempty"`
	QueryTime int64 `json:"query_time,omitempty"`
	// The DNS server response code, normalized to the caption of the rcode_id value. In the case of 'Other', it is defined by the event source.
	Rcode string `json:"rcode,omitempty"`
	// The normalized identifier of the DNS server response code. See <a target='_blank' href='https://datatracker.ietf.org/doc/html/rfc6895'>RFC-6895</a>.
	RcodeId int `json:"rcode_id,omitempty"`
	ResponseTime int64 `json:"response_time,omitempty"`
	Traffic *objects.NetworkTraffic `json:"traffic,omitempty"`
}

// Activity IDs for DNS Activity
const (
	DnsActivityActivityQuery = 1 // The DNS query request.
	DnsActivityActivityResponse = 2 // The DNS query response.
	DnsActivityActivityTraffic = 6 // Bidirectional DNS request and response traffic.
)

// NewDnsActivity creates a new DNS Activity event
func NewDnsActivity(activityID int) *DnsActivity {
	return &DnsActivity{
		Event: ocsf.Event{
			CategoryUID: 4,
			ClassUID:    4003,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(4, 4003, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "network",
			Class:       "dns_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

