// Code generated by ocsf-generator. DO NOT EDIT.

package network

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Email File Activity - Email File Activity events report files within emails.
// OCSF Class UID: 4011
//
// This is a generated struct representing the OCSF event class.
type EmailFileActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	EmailUid string `json:"email_uid"`
	// The email file attachment.
	File *objects.File `json:"file"`
}

// Activity IDs for Email File Activity
const (
	EmailFileActivityActivitySend = 1 // 
	EmailFileActivityActivityReceive = 2 // 
	EmailFileActivityActivityScan = 3 // Email file being scanned (example: security scanning).
)

// NewEmailFileActivity creates a new Email File Activity event
func NewEmailFileActivity(activityID int) *EmailFileActivity {
	return &EmailFileActivity{
		Event: ocsf.Event{
			CategoryUID: 4,
			ClassUID:    4011,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(4, 4011, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "network",
			Class:       "email_file_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

