// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package network

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Email URL Activity - Email URL Activity events report URLs within an email.
// OCSF Class UID: 4012
//
// This is a generated struct representing the OCSF event class.
type EmailUrlActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	EmailUid string `json:"email_uid"`
	// The URL included in the email content.
	Url *objects.Url `json:"url"`
}

// Activity IDs for Email URL Activity
const (
	EmailUrlActivityActivitySend = 1 // 
	EmailUrlActivityActivityReceive = 2 // 
	EmailUrlActivityActivityScan = 3 // Email URL being scanned (example: security scanning).
)

// NewEmailUrlActivity creates a new Email URL Activity event
func NewEmailUrlActivity(activityID int) *EmailUrlActivity {
	return &EmailUrlActivity{
		Event: ocsf.Event{
			CategoryUID: 4,
			ClassUID:    4012,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(4, 4012, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "network",
			Class:       "email_url_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

