// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package network

import (
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
	"time"
)

type EmailActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Attempt         int                      `json:"attempt,omitempty"`
	Banner          string                   `json:"banner,omitempty"`
	Command         string                   `json:"command,omitempty"`
	Direction       string                   `json:"direction,omitempty"`
	DirectionId     int                      `json:"direction_id"`
	DstEndpoint     *objects.NetworkEndpoint `json:"dst_endpoint,omitempty"`
	Email           *objects.Email           `json:"email"`
	EmailAuth       *objects.EmailAuth       `json:"email_auth,omitempty"`
	From            string                   `json:"from,omitempty"`
	MessageTraceUid string                   `json:"message_trace_uid,omitempty"`
	ProtocolName    string                   `json:"protocol_name,omitempty"`
	SmtpHello       string                   `json:"smtp_hello,omitempty"`
	SrcEndpoint     *objects.NetworkEndpoint `json:"src_endpoint,omitempty"`
	To              []string                 `json:"to,omitempty"`
}

const (
	EmailActivityActivitySend     = 1
	EmailActivityActivityReceive  = 2
	EmailActivityActivityScan     = 3
	EmailActivityActivityTrace    = 4
	EmailActivityActivityMTARelay = 5
)

func NewEmailActivity(activityID int) *EmailActivity {
	return &EmailActivity{
		Event: ocsf.Event{
			CategoryUID: 4,
			ClassUID:    4009,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(4, 4009, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "network",
			Class:       "email_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}
