// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package network

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// FTP Activity - File Transfer Protocol (FTP) Activity events report file transfers between a server and a client as seen on the network.
// OCSF Class UID: 4008
//
// This is a generated struct representing the OCSF event class.
type FtpActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	// The list of return codes to the FTP command.
	Codes []int `json:"codes,omitempty"`
	// The FTP command.
	Command string `json:"command,omitempty"`
	// The list of responses to the FTP command.
	CommandResponses []string `json:"command_responses,omitempty"`
	// The file that is the target of the FTP activity.
	File *objects.File `json:"file,omitempty"`
	// The name of the data affiliated with the command.
	Name string `json:"name,omitempty"`
	// The dynamic port established for impending data transfers.
	Port string `json:"port,omitempty"`
	// The type of FTP network connection (e.g. active, passive).
	Type string `json:"type,omitempty"`
}

// Activity IDs for FTP Activity
const (
	FtpActivityActivityPut = 1 // File upload to the FTP or SFTP site.
	FtpActivityActivityGet = 2 // File download from the FTP or SFTP site.
	FtpActivityActivityPoll = 3 // Poll directory for specific file(s) or folder(s) at the FTP or SFTP site location.
	FtpActivityActivityDelete = 4 // Delete file(s) from the FTP or SFTP site.
	FtpActivityActivityRename = 5 // Rename the file(s) in the FTP or SFTP site.
	FtpActivityActivityList = 6 // List files in a specified directory.
)

// NewFtpActivity creates a new FTP Activity event
func NewFtpActivity(activityID int) *FtpActivity {
	return &FtpActivity{
		Event: ocsf.Event{
			CategoryUID: 4,
			ClassUID:    4008,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(4, 4008, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "network",
			Class:       "ftp_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

