// Code generated by ocsf-generator. DO NOT EDIT.

package network

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// HTTP Activity - HTTP Activity events report HTTP connection and traffic information.
// OCSF Class UID: 4002
//
// This is a generated struct representing the OCSF event class.
type HttpActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	// The file that is the target of the HTTP activity.
	File *objects.File `json:"file,omitempty"`
	HttpCookies []*objects.HttpCookie `json:"http_cookies,omitempty"`
	HttpRequest *objects.HttpRequest `json:"http_request,omitempty"`
	HttpResponse *objects.HttpResponse `json:"http_response,omitempty"`
	HttpStatus int `json:"http_status,omitempty"`
}

// Activity IDs for HTTP Activity
const (
	HttpActivityActivityConnect = 1 // The CONNECT method establishes a tunnel to the server identified by the target resource.
	HttpActivityActivityDelete = 2 // The DELETE method deletes the specified resource.
	HttpActivityActivityGet = 3 // The GET method requests a representation of the specified resource. Requests using GET should only retrieve data.
	HttpActivityActivityHead = 4 // The HEAD method asks for a response identical to a GET request, but without the response body.
	HttpActivityActivityOptions = 5 // The OPTIONS method describes the communication options for the target resource.
	HttpActivityActivityPost = 6 // The POST method submits an entity to the specified resource, often causing a change in state or side effects on the server.
	HttpActivityActivityPut = 7 // The PUT method replaces all current representations of the target resource with the request payload.
	HttpActivityActivityTrace = 8 // The TRACE method performs a message loop-back test along the path to the target resource.
	HttpActivityActivityPatch = 9 // The PATCH method applies partial modifications to a resource.
)

// NewHttpActivity creates a new HTTP Activity event
func NewHttpActivity(activityID int) *HttpActivity {
	return &HttpActivity{
		Event: ocsf.Event{
			CategoryUID: 4,
			ClassUID:    4002,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(4, 4002, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "network",
			Class:       "http_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

