// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package network

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Network File Activity - Network File Activity events report file activities traversing the network, including file storage services such as Box, MS OneDrive, or Google Drive.
// OCSF Class UID: 4010
//
// This is a generated struct representing the OCSF event class.
type NetworkFileActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	// The actor that performed the activity on the target file.
	Actor *objects.Actor `json:"actor"`
	ConnectionInfo *objects.NetworkConnectionInfo `json:"connection_info,omitempty"`
	// The endpoint that received the activity on the target file.
	DstEndpoint *objects.NetworkEndpoint `json:"dst_endpoint,omitempty"`
	// The share expiration time.
	ExpirationTime int64 `json:"expiration_time,omitempty"`
	// The file that is the target of the activity.
	File *objects.File `json:"file"`
	// The endpoint that performed the activity on the target file.
	SrcEndpoint *objects.NetworkEndpoint `json:"src_endpoint"`
}

// Activity IDs for Network File Activity
const (
	NetworkFileActivityActivityUpload = 1 // Upload a file.
	NetworkFileActivityActivityLock = 10 // Lock a file.
	NetworkFileActivityActivityUnlock = 11 // Unlock a file.
	NetworkFileActivityActivityShare = 12 // Share a file.
	NetworkFileActivityActivityUnshare = 13 // Unshare a file.
	NetworkFileActivityActivityOpen = 14 // Open a file.
	NetworkFileActivityActivitySync = 15 // Mark a file or folder to sync with a computer.
	NetworkFileActivityActivityUnsync = 16 // Mark a file or folder to not sync with a computer.
	NetworkFileActivityActivityDownload = 2 // Download a file.
	NetworkFileActivityActivityUpdate = 3 // Update a file.
	NetworkFileActivityActivityDelete = 4 // Delete a file.
	NetworkFileActivityActivityRename = 5 // Rename a file.
	NetworkFileActivityActivityCopy = 6 // Copy a file.
	NetworkFileActivityActivityMove = 7 // Move a file.
	NetworkFileActivityActivityRestore = 8 // Restore a file.
	NetworkFileActivityActivityPreview = 9 // Preview a file.
)

// NewNetworkFileActivity creates a new Network File Activity event
func NewNetworkFileActivity(activityID int) *NetworkFileActivity {
	return &NetworkFileActivity{
		Event: ocsf.Event{
			CategoryUID: 4,
			ClassUID:    4010,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(4, 4010, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "network",
			Class:       "network_file_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

