// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package network

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Network Activity - Network Activity events report network connection and traffic activity.
// OCSF Class UID: 4001
//
// This is a generated struct representing the OCSF event class.
type NetworkActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	// The responder of the network connection. In some contexts an event source cannot correctly identify the responder. Refer to `is_src_dst_assignment_known` for certainty.
	DstEndpoint *objects.NetworkEndpoint `json:"dst_endpoint"`
	IsSrcDstAssignmentKnown bool `json:"is_src_dst_assignment_known,omitempty"`
	// The initiator of the network connection. In some contexts an event source cannot correctly identify the initiator. Refer to `is_src_dst_assignment_known` for certainty.
	SrcEndpoint *objects.NetworkEndpoint `json:"src_endpoint"`
	// The URL details relevant to the network traffic.
	Url *objects.Url `json:"url,omitempty"`
}

// Activity IDs for Network Activity
const (
	NetworkActivityActivityOpen = 1 // A new network connection was opened.
	NetworkActivityActivityClose = 2 // The network connection was closed.
	NetworkActivityActivityReset = 3 // The network connection was abnormally terminated or closed by a middle device like firewalls.
	NetworkActivityActivityFail = 4 // The network connection failed. For example a connection timeout or no route to host.
	NetworkActivityActivityRefuse = 5 // The network connection was refused. For example an attempt to connect to a server port which is not open.
	NetworkActivityActivityTraffic = 6 // Network traffic report.
	NetworkActivityActivityListen = 7 // A network endpoint began listening for new network connections.
)

// NewNetworkActivity creates a new Network Activity event
func NewNetworkActivity(activityID int) *NetworkActivity {
	return &NetworkActivity{
		Event: ocsf.Event{
			CategoryUID: 4,
			ClassUID:    4001,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(4, 4001, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "network",
			Class:       "network_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

