// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package network

import (
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"time"
)

type NtpActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Delay      int    `json:"delay,omitempty"`
	Dispersion int    `json:"dispersion,omitempty"`
	Precision  int    `json:"precision,omitempty"`
	Stratum    string `json:"stratum,omitempty"`
	StratumId  int    `json:"stratum_id,omitempty"`
	Version    string `json:"version"`
}

const (
	NtpActivityActivityUnknown                  = 0
	NtpActivityActivitySymmetricActiveExchange  = 1
	NtpActivityActivitySymmetricPassiveResponse = 2
	NtpActivityActivityClientSynchronization    = 3
	NtpActivityActivityServerResponse           = 4
	NtpActivityActivityBroadcast                = 5
	NtpActivityActivityControl                  = 6
	NtpActivityActivityPrivateUseCase           = 7
	NtpActivityActivityOther                    = 99
)

func NewNtpActivity(activityID int) *NtpActivity {
	return &NtpActivity{
		Event: ocsf.Event{
			CategoryUID: 4,
			ClassUID:    4013,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(4, 4013, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "network",
			Class:       "ntp_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}
