// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package network

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
)

// NTP Activity - The Network Time Protocol (NTP) Activity events report instances of remote clients synchronizing their clocks with an NTP server, as observed on the network.
// OCSF Class UID: 4013
//
// This is a generated struct representing the OCSF event class.
type NtpActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Delay int `json:"delay,omitempty"`
	Dispersion int `json:"dispersion,omitempty"`
	// The NTP precision quantifies a clock's accuracy and stability in log2 seconds, as defined in RFC-5905.
	Precision int `json:"precision,omitempty"`
	Stratum string `json:"stratum,omitempty"`
	StratumId int `json:"stratum_id,omitempty"`
	// The version number of the NTP protocol.
	Version string `json:"version"`
}

// Activity IDs for NTP Activity
const (
	NtpActivityActivityUnknown = 0 // Not used in standard NTP implementations.
	NtpActivityActivitySymmetricActiveExchange = 1 // Bidirectional time exchange between devices.
	NtpActivityActivitySymmetricPassiveResponse = 2 // Device responds as a server to peers in symmetric active mode.
	NtpActivityActivityClientSynchronization = 3 // NTP client, syncs with servers.
	NtpActivityActivityServerResponse = 4 // Dedicated NTP time server, responds to clients.
	NtpActivityActivityBroadcast = 5 // Broadcast time info to network devices.
	NtpActivityActivityControl = 6 // Monitoring and control messaging.
	NtpActivityActivityPrivateUseCase = 7 // Reserved - Not defined in standard NTP specifications.
	NtpActivityActivityOther = 99 // The event activity is not mapped.
)

// NewNtpActivity creates a new NTP Activity event
func NewNtpActivity(activityID int) *NtpActivity {
	return &NtpActivity{
		Event: ocsf.Event{
			CategoryUID: 4,
			ClassUID:    4013,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(4, 4013, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "network",
			Class:       "ntp_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

