// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package network

import (
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
	"time"
)

type RdpActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Capabilities     []string                       `json:"capabilities,omitempty"`
	CertificateChain []string                       `json:"certificate_chain,omitempty"`
	ConnectionInfo   *objects.NetworkConnectionInfo `json:"connection_info,omitempty"`
	Device           *objects.Device                `json:"device,omitempty"`
	File             *objects.File                  `json:"file,omitempty"`
	IdentifierCookie string                         `json:"identifier_cookie,omitempty"`
	KeyboardInfo     *objects.KeyboardInfo          `json:"keyboard_info,omitempty"`
	ProtocolVer      string                         `json:"protocol_ver,omitempty"`
	RemoteDisplay    *objects.Display               `json:"remote_display,omitempty"`
	Request          *objects.Request               `json:"request,omitempty"`
	Response         *objects.Response              `json:"response,omitempty"`
	User             *objects.User                  `json:"user,omitempty"`
}

const (
	RdpActivityActivityInitialRequest  = 1
	RdpActivityActivityInitialResponse = 2
	RdpActivityActivityConnectRequest  = 3
	RdpActivityActivityConnectResponse = 4
	RdpActivityActivityTLSHandshake    = 5
	RdpActivityActivityTraffic         = 6
	RdpActivityActivityDisconnect      = 7
	RdpActivityActivityReconnect       = 8
)

func NewRdpActivity(activityID int) *RdpActivity {
	return &RdpActivity{
		Event: ocsf.Event{
			CategoryUID: 4,
			ClassUID:    4005,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(4, 4005, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "network",
			Class:       "rdp_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}
