// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package network

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// RDP Activity - Remote Desktop Protocol (RDP) Activity events report post-authentication remote client connections between clients and servers over the network.
// OCSF Class UID: 4005
//
// This is a generated struct representing the OCSF event class.
type RdpActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Capabilities []string `json:"capabilities,omitempty"`
	// The list of observed certificates in an RDP TLS connection.
	CertificateChain []string `json:"certificate_chain,omitempty"`
	// The remote desktop connection details, either connection-based or connectionless.
	ConnectionInfo *objects.NetworkConnectionInfo `json:"connection_info,omitempty"`
	// The device instigating the RDP connection.
	Device *objects.Device `json:"device,omitempty"`
	// The file that is the target of the RDP activity.
	File *objects.File `json:"file,omitempty"`
	IdentifierCookie string `json:"identifier_cookie,omitempty"`
	KeyboardInfo *objects.KeyboardInfo `json:"keyboard_info,omitempty"`
	// The Remote Desktop Protocol version.
	ProtocolVer string `json:"protocol_ver,omitempty"`
	RemoteDisplay *objects.Display `json:"remote_display,omitempty"`
	// The client request in an RDP network connection.
	Request *objects.Request `json:"request,omitempty"`
	// The server response in an RDP network connection.
	Response *objects.Response `json:"response,omitempty"`
	// The target user associated with the RDP activity.
	User *objects.User `json:"user,omitempty"`
}

// Activity IDs for RDP Activity
const (
	RdpActivityActivityInitialRequest = 1 // The initial RDP request.
	RdpActivityActivityInitialResponse = 2 // The initial RDP response.
	RdpActivityActivityConnectRequest = 3 // An RDP connection request.
	RdpActivityActivityConnectResponse = 4 // An RDP connection response.
	RdpActivityActivityTLSHandshake = 5 // The TLS handshake.
	RdpActivityActivityTraffic = 6 // Network traffic report.
	RdpActivityActivityDisconnect = 7 // An RDP connection disconnect.
	RdpActivityActivityReconnect = 8 // An RDP connection reconnect.
)

// NewRdpActivity creates a new RDP Activity event
func NewRdpActivity(activityID int) *RdpActivity {
	return &RdpActivity{
		Event: ocsf.Event{
			CategoryUID: 4,
			ClassUID:    4005,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(4, 4005, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "network",
			Class:       "rdp_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

