// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package network

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Tunnel Activity - Tunnel Activity events report secure tunnel establishment (such as VPN), teardowns, renewals, and other network tunnel specific actions.
// OCSF Class UID: 4014
//
// This is a generated struct representing the OCSF event class.
type TunnelActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	// The tunnel connection information.
	ConnectionInfo *objects.NetworkConnectionInfo `json:"connection_info,omitempty"`
	// The device that reported the event.
	Device *objects.Device `json:"device,omitempty"`
	// The server responding to the tunnel connection.
	DstEndpoint *objects.NetworkEndpoint `json:"dst_endpoint,omitempty"`
	// The networking protocol associated with the tunnel. E.g. `IPSec`, `SSL`, `GRE`.
	ProtocolName string `json:"protocol_name,omitempty"`
	// The session associated with the tunnel.
	Session *objects.Session `json:"session,omitempty"`
	// The initiator (client) of the tunnel connection.
	SrcEndpoint *objects.NetworkEndpoint `json:"src_endpoint,omitempty"`
	// Traffic refers to the amount of data moving across the tunnel at a given point of time. Ex: `bytes_in` and `bytes_out`.
	Traffic *objects.NetworkTraffic `json:"traffic,omitempty"`
	// The information about the virtual tunnel interface, e.g. `utun0`. This is usually associated with the private (rfc-1918) ip of the tunnel.
	TunnelInterface *objects.NetworkInterface `json:"tunnel_interface,omitempty"`
	// The tunnel type. Example: `Split` or `Full`.
	TunnelType string `json:"tunnel_type,omitempty"`
	// The normalized tunnel type ID.
	TunnelTypeId int `json:"tunnel_type_id,omitempty"`
	// The user associated with the tunnel activity.
	User *objects.User `json:"user,omitempty"`
}

// Activity IDs for Tunnel Activity
const (
	TunnelActivityActivityUnknown = 0 // The event activity is unknown.
	TunnelActivityActivityOpen = 1 // Open a tunnel.
	TunnelActivityActivityClose = 2 // Close a tunnel.
	TunnelActivityActivityRenew = 3 // Renew a tunnel.
	TunnelActivityActivityOther = 99 // The event activity is not mapped. See the <code>activity_name</code> attribute, which contains a data source specific value.
)

// NewTunnelActivity creates a new Tunnel Activity event
func NewTunnelActivity(activityID int) *TunnelActivity {
	return &TunnelActivity{
		Event: ocsf.Event{
			CategoryUID: 4,
			ClassUID:    4014,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(4, 4014, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "network",
			Class:       "tunnel_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

