// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package network

import (
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
	"time"
)

type TunnelActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	ConnectionInfo  *objects.NetworkConnectionInfo `json:"connection_info,omitempty"`
	Device          *objects.Device                `json:"device,omitempty"`
	DstEndpoint     *objects.NetworkEndpoint       `json:"dst_endpoint,omitempty"`
	ProtocolName    string                         `json:"protocol_name,omitempty"`
	Session         *objects.Session               `json:"session,omitempty"`
	SrcEndpoint     *objects.NetworkEndpoint       `json:"src_endpoint,omitempty"`
	Traffic         *objects.NetworkTraffic        `json:"traffic,omitempty"`
	TunnelInterface *objects.NetworkInterface      `json:"tunnel_interface,omitempty"`
	TunnelType      string                         `json:"tunnel_type,omitempty"`
	TunnelTypeId    int                            `json:"tunnel_type_id,omitempty"`
	User            *objects.User                  `json:"user,omitempty"`
}

const (
	TunnelActivityActivityUnknown = 0
	TunnelActivityActivityOpen    = 1
	TunnelActivityActivityClose   = 2
	TunnelActivityActivityRenew   = 3
	TunnelActivityActivityOther   = 99
)

func NewTunnelActivity(activityID int) *TunnelActivity {
	return &TunnelActivity{
		Event: ocsf.Event{
			CategoryUID: 4,
			ClassUID:    4014,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(4, 4014, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "network",
			Class:       "tunnel_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}
