package main

import (
	"strings"
)

// generateHeader returns the standard header for generated files
func generateHeader() string {
	return `// Code generated by normalizer-generator. DO NOT EDIT.
//
// This file was automatically generated from OCSF schema and field mappings.

`
}

// toGoStructName converts snake_case to PascalCase for Go struct names
func toGoStructName(name string) string {
	parts := strings.Split(name, "_")
	for i, part := range parts {
		parts[i] = strings.Title(part)
	}
	return strings.Join(parts, "")
}

// mapFieldToGoPath maps an OCSF field name to its likely Go struct path
func mapFieldToGoPath(fieldName string) string {
	// This is a simplified mapping - real implementation would need complete mapping
	fieldMap := map[string]string{
		"user":         "Actor.User",
		"src_endpoint": "SrcEndpoint",
		"dst_endpoint": "DstEndpoint",
		"activity_id":  "ActivityID",
		"category_uid": "CategoryUID",
		"class_uid":    "ClassUID",
		"severity_id":  "SeverityID",
		"status_id":    "StatusID",
		"time":         "Time",
		"metadata":     "Metadata",
	}

	if path, ok := fieldMap[fieldName]; ok {
		return path
	}
	return toGoStructName(fieldName)
}
