// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package remediation

import (
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
	"time"
)

type FileRemediationActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	File *objects.File `json:"file"`
}

func NewFileRemediationActivity(activityID int) *FileRemediationActivity {
	return &FileRemediationActivity{
		Event: ocsf.Event{
			CategoryUID: 7,
			ClassUID:    7002,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(7, 7002, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "remediation",
			Class:       "file_remediation_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}
