// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package remediation

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// File Remediation Activity - File Remediation Activity events report on attempts at remediating files. It follows the MITRE countermeasures defined by the D3FEND™ <a target='_blank' href='https://d3fend.mitre.org/'>Matrix</a>. Sub-techniques will include File, such as File Removal or Restore File.
// OCSF Class UID: 7002
//
// This is a generated struct representing the OCSF event class.
type FileRemediationActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	// The file that pertains to the remediation event.
	File *objects.File `json:"file"`
}

// NewFileRemediationActivity creates a new File Remediation Activity event
func NewFileRemediationActivity(activityID int) *FileRemediationActivity {
	return &FileRemediationActivity{
		Event: ocsf.Event{
			CategoryUID: 7,
			ClassUID:    7002,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(7, 7002, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "remediation",
			Class:       "file_remediation_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

