// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package remediation

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Network Remediation Activity - Network Remediation Activity events report on attempts at remediating computer networks. It follows the MITRE countermeasures defined by the D3FEND™ <a target='_blank' href='https://d3fend.mitre.org/'>Matrix</a>. Techniques and Sub-techniques will include Network, such as Network Isolation or Network Traffic Filtering.
// OCSF Class UID: 7004
//
// This is a generated struct representing the OCSF event class.
type NetworkRemediationActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	// The network connection that pertains to the remediation event.
	ConnectionInfo *objects.NetworkConnectionInfo `json:"connection_info"`
}

// NewNetworkRemediationActivity creates a new Network Remediation Activity event
func NewNetworkRemediationActivity(activityID int) *NetworkRemediationActivity {
	return &NetworkRemediationActivity{
		Event: ocsf.Event{
			CategoryUID: 7,
			ClassUID:    7004,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(7, 7004, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "remediation",
			Class:       "network_remediation_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

