// Code generated by ocsf-generator. DO NOT EDIT.

package remediation

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Process Remediation Activity - Process Remediation Activity events report on attempts at remediating processes. It follows the MITRE countermeasures defined by the D3FEND™ <a target='_blank' href='https://d3fend.mitre.org/'>Matrix</a>. Sub-techniques will include Process, such as Process Termination or Kernel-based Process Isolation.
// OCSF Class UID: 7003
//
// This is a generated struct representing the OCSF event class.
type ProcessRemediationActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	// The process that pertains to the remediation event.
	Process *objects.Process `json:"process"`
}

// NewProcessRemediationActivity creates a new Process Remediation Activity event
func NewProcessRemediationActivity(activityID int) *ProcessRemediationActivity {
	return &ProcessRemediationActivity{
		Event: ocsf.Event{
			CategoryUID: 7,
			ClassUID:    7003,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(7, 7003, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "remediation",
			Class:       "process_remediation_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

