// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package remediation

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Remediation Activity - Remediation Activity events report on attempts at remediating a compromised device or computer network. It follows the MITRE countermeasures defined by the D3FEND™ <a target='_blank' href='https://d3fend.mitre.org/'>Matrix</a>.
// OCSF Class UID: 7001
//
// This is a generated struct representing the OCSF event class.
type RemediationActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	// The unique identifier of the remediation command that pertains to this event.
	CommandUid string `json:"command_uid"`
	Countermeasures []*objects.D3fend `json:"countermeasures,omitempty"`
	Remediation *objects.Remediation `json:"remediation,omitempty"`
	// The remediation scan that pertains to this event.
	Scan *objects.Scan `json:"scan,omitempty"`
}

// Activity IDs for Remediation Activity
const (
	RemediationActivityActivityIsolate = 1 // Creates logical or physical barriers in a system which reduces opportunities for adversaries to create further accesses. Defined by D3FEND™ <a target='_blank' href='https://d3fend.mitre.org/tactic/d3f:Isolate/'>d3f:Isolate</a>.
	RemediationActivityActivityEvict = 2 // Removes an adversary or malicious resource from a device or computer network. Defined by D3FEND™ <a target='_blank' href='https://d3fend.mitre.org/tactic/d3f:Evict/'>d3f:Evict</a>.
	RemediationActivityActivityRestore = 3 // Returns the system to a better state. Defined by D3FEND™ <a target='_blank' href='https://d3fend.mitre.org/tactic/d3f:Restore/'>d3f:Restore</a>.
	RemediationActivityActivityHarden = 4 // Increases the opportunity cost of computer network exploitation. Defined by D3FEND™ <a target='_blank' href='https://d3fend.mitre.org/tactic/d3f:Harden/'>d3f:Harden</a>.
	RemediationActivityActivityDetect = 5 // Further identify adversary access to or unauthorized activity on computer networks. Defined by D3FEND™ <a target='_blank' href='https://d3fend.mitre.org/tactic/d3f:Detect/'>d3f:Detect</a>.
)

// NewRemediationActivity creates a new Remediation Activity event
func NewRemediationActivity(activityID int) *RemediationActivity {
	return &RemediationActivity{
		Event: ocsf.Event{
			CategoryUID: 7,
			ClassUID:    7001,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(7, 7001, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "remediation",
			Class:       "remediation_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

