// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package network

import (
	"fmt"
	"time"
	"github.com/telhawk-systems/telhawk-stack/common/ocsf"
	"github.com/telhawk-systems/telhawk-stack/common/ocsf/objects"
)

type EmailFileActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	EmailUid string `json:"email_uid"`
	File *objects.File `json:"file"`
}

const (
	EmailFileActivityActivitySend = 1
	EmailFileActivityActivityReceive = 2
	EmailFileActivityActivityScan = 3
)

func NewEmailFileActivity(activityID int) *EmailFileActivity {
	return &EmailFileActivity{
		Event: ocsf.Event{
			CategoryUID: 4,
			ClassUID:    4011,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(4, 4011, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "network",
			Class:       "email_file_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

// Validate checks that all required fields are properly set
func (e *EmailFileActivity) Validate() error {
	if e.EmailUid == "" {
		return fmt.Errorf("required field email_uid is empty")
	}
	return nil
}

