// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package network

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/common/ocsf"
	"github.com/telhawk-systems/telhawk-stack/common/ocsf/objects"
)

type FtpActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Codes []int `json:"codes,omitempty"`
	Command string `json:"command,omitempty"`
	CommandResponses []string `json:"command_responses,omitempty"`
	File *objects.File `json:"file,omitempty"`
	Name string `json:"name,omitempty"`
	Port int `json:"port,omitempty"`
	Type string `json:"type,omitempty"`
}

const (
	FtpActivityActivityPut = 1
	FtpActivityActivityGet = 2
	FtpActivityActivityPoll = 3
	FtpActivityActivityDelete = 4
	FtpActivityActivityRename = 5
	FtpActivityActivityList = 6
)

func NewFtpActivity(activityID int) *FtpActivity {
	return &FtpActivity{
		Event: ocsf.Event{
			CategoryUID: 4,
			ClassUID:    4008,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(4, 4008, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "network",
			Class:       "ftp_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

// Validate checks that all required fields are properly set
func (e *FtpActivity) Validate() error {
	// No required string fields to validate
	return nil
}

