// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package network

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/common/ocsf"
	"github.com/telhawk-systems/telhawk-stack/common/ocsf/objects"
)

type SshActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	AuthType string `json:"auth_type,omitempty"`
	AuthTypeId int `json:"auth_type_id,omitempty"`
	ClientHassh *objects.Hassh `json:"client_hassh,omitempty"`
	File *objects.File `json:"file,omitempty"`
	ProtocolVer string `json:"protocol_ver,omitempty"`
	ServerHassh *objects.Hassh `json:"server_hassh,omitempty"`
}

const (
	SshActivityActivityOpen = 1
	SshActivityActivityClose = 2
	SshActivityActivityReset = 3
	SshActivityActivityFail = 4
	SshActivityActivityRefuse = 5
	SshActivityActivityTraffic = 6
	SshActivityActivityListen = 7
)

func NewSshActivity(activityID int) *SshActivity {
	return &SshActivity{
		Event: ocsf.Event{
			CategoryUID: 4,
			ClassUID:    4007,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(4, 4007, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "network",
			Class:       "ssh_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

// Validate checks that all required fields are properly set
func (e *SshActivity) Validate() error {
	// No required string fields to validate
	return nil
}

