// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package system

import (
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
	"time"
)

type EventLogActvity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Actor        *objects.Actor           `json:"actor,omitempty"`
	Device       *objects.Device          `json:"device,omitempty"`
	DstEndpoint  *objects.NetworkEndpoint `json:"dst_endpoint,omitempty"`
	File         *objects.File            `json:"file,omitempty"`
	LogName      string                   `json:"log_name,omitempty"`
	LogProvider  string                   `json:"log_provider,omitempty"`
	LogType      string                   `json:"log_type,omitempty"`
	LogTypeId    int                      `json:"log_type_id,omitempty"`
	SrcEndpoint  *objects.NetworkEndpoint `json:"src_endpoint,omitempty"`
	StatusCode   string                   `json:"status_code,omitempty"`
	StatusDetail string                   `json:"status_detail,omitempty"`
}

const (
	EventLogActvityActivityClear   = 1
	EventLogActvityActivityDisable = 10
	EventLogActvityActivityDelete  = 2
	EventLogActvityActivityExport  = 3
	EventLogActvityActivityArchive = 4
	EventLogActvityActivityRotate  = 5
	EventLogActvityActivityStart   = 6
	EventLogActvityActivityStop    = 7
	EventLogActvityActivityRestart = 8
	EventLogActvityActivityEnable  = 9
)

func NewEventLogActvity(activityID int) *EventLogActvity {
	return &EventLogActvity{
		Event: ocsf.Event{
			CategoryUID: 1,
			ClassUID:    1008,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(1, 1008, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "system",
			Class:       "event_log_actvity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}
