// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package system

import (
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
	"time"
)

type KernelExtensionActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Actor  *objects.Actor        `json:"actor"`
	Driver *objects.KernelDriver `json:"driver"`
}

const (
	KernelExtensionActivityActivityLoad   = 1
	KernelExtensionActivityActivityUnload = 2
)

func NewKernelExtensionActivity(activityID int) *KernelExtensionActivity {
	return &KernelExtensionActivity{
		Event: ocsf.Event{
			CategoryUID: 1,
			ClassUID:    1002,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(1, 1002, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "system",
			Class:       "kernel_extension_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}
