// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the Apache
// License 2.0 as-is, without warranty of any kind.

package system

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Kernel Extension Activity - Kernel Extension events report when a driver/extension is loaded or unloaded into the kernel
// OCSF Class UID: 1002
//
// This is a generated struct representing the OCSF event class.
type KernelExtensionActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	// The actor process that loaded or unloaded the driver/extension.
	Actor *objects.Actor `json:"actor"`
	Driver *objects.KernelDriver `json:"driver"`
}

// Activity IDs for Kernel Extension Activity
const (
	KernelExtensionActivityActivityLoad = 1 // A driver/extension was loaded into the kernel
	KernelExtensionActivityActivityUnload = 2 // A driver/extension was unloaded (removed) from the kernel
)

// NewKernelExtensionActivity creates a new Kernel Extension Activity event
func NewKernelExtensionActivity(activityID int) *KernelExtensionActivity {
	return &KernelExtensionActivity{
		Event: ocsf.Event{
			CategoryUID: 1,
			ClassUID:    1002,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(1, 1002, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "system",
			Class:       "kernel_extension_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

