// Code generated by ocsf-generator. DO NOT EDIT.

package system

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Kernel Activity - Kernel Activity events report when an process creates, reads, or deletes a kernel resource.
// OCSF Class UID: 1003
//
// This is a generated struct representing the OCSF event class.
type KernelActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	// The target kernel resource.
	Kernel *objects.Kernel `json:"kernel"`
}

// Activity IDs for Kernel Activity
const (
	KernelActivityActivityCreate = 1 // 
	KernelActivityActivityRead = 2 // 
	KernelActivityActivityDelete = 3 // 
	KernelActivityActivityInvoke = 4 // 
)

// NewKernelActivity creates a new Kernel Activity event
func NewKernelActivity(activityID int) *KernelActivity {
	return &KernelActivity{
		Event: ocsf.Event{
			CategoryUID: 1,
			ClassUID:    1003,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(1, 1003, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "system",
			Class:       "kernel_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

