// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// Generated from OCSF Schema: https://github.com/ocsf/ocsf-schema
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package system

import (
	"fmt"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
	"time"
)

type KernelActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	Kernel *objects.Kernel `json:"kernel"`
}

const (
	KernelActivityActivityCreate = 1
	KernelActivityActivityRead   = 2
	KernelActivityActivityDelete = 3
	KernelActivityActivityInvoke = 4
)

func NewKernelActivity(activityID int) *KernelActivity {
	return &KernelActivity{
		Event: ocsf.Event{
			CategoryUID: 1,
			ClassUID:    1003,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(1, 1003, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "system",
			Class:       "kernel_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

// Validate checks that all required fields are properly set
func (e *KernelActivity) Validate() error {
	// No required string fields to validate
	return nil
}
