// Code generated by TelHawk OCSF Generator. DO NOT EDIT.
//
// This generated code contains no original authorship and is released into the
// public domain. For convenience, TelHawk Systems provides it under the TelHawk
// Systems Source Available License (TSSAL) v1.0 as-is, without warranty of any kind.

package system

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Module Activity - Module Activity events report when an endpoint process acts on a <code>module</code>.
// OCSF Class UID: 1005
//
// This is a generated struct representing the OCSF event class.
type ModuleActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	// The actor that performed the activity on the target `module`. For example, the process that loaded a module into memory.
	Actor *objects.Actor `json:"actor"`
	// The module that was loaded, unloaded, or invoked.
	Module *objects.Module `json:"module"`
}

// Activity IDs for Module Activity
const (
	ModuleActivityActivityLoad = 1 // The target module was loaded.
	ModuleActivityActivityUnload = 2 // The target module was unloaded.
	ModuleActivityActivityInvoke = 3 // A function exported from the target module was invoked.
)

// NewModuleActivity creates a new Module Activity event
func NewModuleActivity(activityID int) *ModuleActivity {
	return &ModuleActivity{
		Event: ocsf.Event{
			CategoryUID: 1,
			ClassUID:    1005,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(1, 1005, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "system",
			Class:       "module_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

