// Code generated by ocsf-generator. DO NOT EDIT.

package system

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Peripheral Activity - Peripheral Activity events log a system's interactions with external, connectable, and detachable hardware. These events provide visibility into the external devices connected to and used by a system.
// OCSF Class UID: 1010
//
// This is a generated struct representing the OCSF event class.
type PeripheralActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	// The peripheral device that is the subject of the activity.
	PeripheralDevice *objects.PeripheralDevice `json:"peripheral_device"`
}

// Activity IDs for Peripheral Activity
const (
	PeripheralActivityActivityConnect = 1 // A peripheral device was connected to the system.
	PeripheralActivityActivityDisconnect = 2 // A peripheral device was disconnected from the system.
	PeripheralActivityActivityEnable = 3 // A peripheral device was enabled on the system.
	PeripheralActivityActivityDisable = 4 // A peripheral device was disabled on the system.
	PeripheralActivityActivityEject = 5 // A peripheral device was ejected from the system. This is typically used for removable media devices. Note: For <code>Mount</code> and <code>Unmount</code> events, see the <a target='_blank' href='file_activity'>File System Activity</a> event class.
)

// NewPeripheralActivity creates a new Peripheral Activity event
func NewPeripheralActivity(activityID int) *PeripheralActivity {
	return &PeripheralActivity{
		Event: ocsf.Event{
			CategoryUID: 1,
			ClassUID:    1010,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(1, 1010, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "system",
			Class:       "peripheral_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

