// Code generated by ocsf-generator. DO NOT EDIT.

package system

import (
	"time"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf"
	"github.com/telhawk-systems/telhawk-stack/core/pkg/ocsf/objects"
)

// Script Activity - Script Activity events report when a process executes a script.
// OCSF Class UID: 1009
//
// This is a generated struct representing the OCSF event class.
type ScriptActivity struct {
	// Embed base OCSF event
	ocsf.Event

	// Class-specific attributes
	// The script that was the target of the activity.
	Script *objects.Script `json:"script"`
}

// Activity IDs for Script Activity
const (
	ScriptActivityActivityExecute = 1 // 
)

// NewScriptActivity creates a new Script Activity event
func NewScriptActivity(activityID int) *ScriptActivity {
	return &ScriptActivity{
		Event: ocsf.Event{
			CategoryUID: 1,
			ClassUID:    1009,
			ActivityID:  activityID,
			TypeUID:     ocsf.ComputeTypeUID(1, 1009, activityID),
			Time:        time.Now(),
			SeverityID:  ocsf.SeverityUnknown,
			Category:    "system",
			Class:       "script_activity",
			Severity:    "Unknown",
			Metadata: ocsf.Metadata{
				Product: ocsf.Product{
					Name:   "TelHawk Stack",
					Vendor: "TelHawk Systems",
				},
				Version: "1.1.0",
			},
		},
	}
}

